### ISSUE TITLE
集成gateway时 以 “uri: lb://service name” 这种方式配置时

### ISSUE THREAD

**Issue by XiFYuW** [alibaba/nacos#10247]
当我集成gateway 如下配置：
```
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        # 路由id，建议配合服务名
        - id: admin
          #匹配路由名
          uri: lb://meta-admin-app
          predicates:
            # 断言，路径相匹配的进行路由
            - Path=/admin/**
          filters:
            - StripPrefix=1
```
服务列表如图：
![image](https://user-images.githubusercontent.com/33598203/229286101-4f5ec496-5f22-41e5-8515-4049093cdac6.png)
会出现如下情况：
![image](https://user-images.githubusercontent.com/33598203/229286162-2358ad0e-0f45-46b0-b1b4-28bb9f36c5d8.png)

**当我把服务列表的分组名改成一样时是可以正常访问的，所以能不能优化一下这种情况，例如：uri: lb://分组名称@@meta-admin-app这样也可以正常的查询到服务。**
