### ISSUE TITLE
nacos配置中心共享配置无法读取配置

### ISSUE THREAD

**Issue by MaLuxray** [alibaba/nacos#10590]
springboot version `2.6.0`
springcloud version `3.1.4`
nacosconfig version `2021.1`

bootstrap.yml
``` yaml
    spring:
       application:
           name: config-app
       cloud:
         nacos:
            server-addr: locahost:8848
            config:
               group: DEFAULT_GROUP
               prefix: ${spring.application.name}
               file-extension: yaml
               extension-configs:
                - data-id: redis
```

配置中心 `redis` 配置
``` yaml
    redis:
       host: 127.0.0.1
       username: amdin
       password: admin
    name: redis
```

配置中心 config-app` 配置
``` yaml
   server:
      port: 15555
```

java code
``` java
   @RestController
    public class RedisController {
       @Value("${redis.host}")
       private String redisValue;

       @GetMapping(value = "/redis")
        public String redis() {
           return redisValue;
       }
   }
```

启动服务时报错
```
   Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'redis.host' in value "${redis.host}"
```

当把`reids.host`改成`name`又可以正常启动
