### ISSUE TITLE
容器化部署nacos集群，日志频繁出现Server check fail, please check server ip

### ISSUE THREAD

**Issue by wonkp** [alibaba/nacos#10611]
一，使用docker compose部署nacos集群（特殊情况部署双节点）
节点1
```
version: '3.0'
services:
  nacos:
    image:  'nacos:2.1.0'
    ports:
      - '26901:26901'      
      - '25901:25901'      
      - '27901:27901'      
      - '27902:27902'
    container_name: 'nacos'
    network_mode: 'host'
    user: root
    volumes:
      - '/usr/log/public/nacos26901:/usr/public/nacos/logs'
      - '/usr/public/nacos26901/data:/usr/public/nacos/data'
      - '/usr/public/nacos26901/conf:/usr/public/nacos/conf'
      - '/etc/localtime:/etc/localtime'
    logging:
      driver: 'json-file'
      options:
        max-size: '500M'
        max-file: '10'
    environment:
      - JAVA_OPTS='-Xmx4096m'
    command: cluster
```

节点2
```
version: '3.0'
services:
  nacos:
    image:  'nacos:2.1.0'
    ports:
      - '26903:26903'      
      - '25903:25903'      
      - '27903:27903'      
      - '27904:27904'
    container_name: 'nacos'
    network_mode: 'host'
    user: root
    volumes:
      - '/usr/log/public/nacos26903:/usr/public/nacos/logs'
      - '/usr/public/nacos26903/data:/usr/public/nacos/data'
      - '/usr/public/nacos26903/conf:/usr/public/nacos/conf'
      - '/etc/localtime:/etc/localtime'
    logging:
      driver: 'json-file'
      options:
        max-size: '500M'
        max-file: '10'
    environment:
      - JAVA_OPTS='-Xmx4096m'
    command: cluster
```

cluster.conf文件内容
```
10.74.128.212.:26903
10.74.128.216:26901
```

二，一开始集群是正常的，一段时间会就会出现Server check fail, please check server ip异常日志，频繁出现
日志信息如下
![image](https://github.com/alibaba/nacos/assets/104979297/b141b362-c129-405b-8351-db50f823be4c)

![image](https://github.com/alibaba/nacos/assets/104979297/eb1580c5-98d7-42b9-ab31-31d6c0dd61aa)

三，我想知道一些问题的答案
1.这个异常日志是我集群部署问题还是普遍的问题？
2.这个异常会不会影响nacos的服务注册和发现，会不会出现服务无法访问的问题，临时实例，无永久实例？
3.双节点的集群会不会是导致这个问题的原因？

四，如果需要其他信息请联系我，我会在第一时间提供，希望大家可以给我提供一些想法和思路
