### ISSUE TITLE
springboot 3.0.7 use nacos as config center，controller use is null

### ISSUE THREAD

**Issue by yanlongma** [alibaba/nacos#10664]
I do it in the order of the documents:  https://nacos.io/zh-cn/docs/quick-start-spring-boot.html

version
- nacos server 2.2.2
- springboot 3.0.7

pom.xml 
```
<dependency>
      <groupId>com.alibaba.boot</groupId>
      <artifactId>nacos-config-spring-boot-starter</artifactId>
      <version>0.2.12</version>
  </dependency>
```

application.yml
```
nacos:
  config:
    server-addr: 127.0.0.1:8848
    group: DEFAULT_GROUP
    data-id: example
    auto-refresh: true
    bootstrap:
      enable: true
    type: properties
```

I edit config in nacos，springboot console is change，but controller `@NacosValue(value = "${name}", autoRefreshed = true)` is always `null`, why ?  
<img width="700" alt="image" src="https://github.com/alibaba/nacos/assets/7803462/ef40495c-1ef9-415f-90ae-dd50187fbdc6">
<img width="700" alt="image" src="https://github.com/alibaba/nacos/assets/7803462/c6090454-2f74-4eb5-b776-ce5393722549">

think you!
