### ISSUE TITLE
When nacos client use endpoint, the registration center should support configuring context-path and cluster-name like the configuration center

### ISSUE THREAD

**Issue by huhongjie2014** [alibaba/nacos#10792]
**Describe the bug**
When nacos clients use nacos endpoint, the registration center should support configuring context-path and cluster-name like the configuration center
当nacos client使用endpoint时，注册中心应该像配置中心一样支持配置 context-path and cluster-name

When I use the following configuration, application launch failed， please note that I am using the nacos endpoint.
当我使用如下配置时，程序启动失败，请注意我使用了 nacos endpoint

```yml
spring:
  application:
    name: test-service
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        endpoint: localhost:8080
        context-path: /nacos
        cluster-name: china
        namespace:
        username: nacos
        password: nacos
        group: test
      discovery:
        endpoint: localhost:8080
        context-path: /nacos
        cluster-name: china
        namespace:
        username: nacos
        password: nacos
        group: test
```

configuration center - The address is correct
配置中心 - 地址正确

```java
com.alibaba.nacos.client.config.impl.ServerListManager#initAddressServerUrl
private void initAddressServerUrl(NacosClientProperties properties) {
        ...
        StringBuilder addressServerUrlTem = new StringBuilder(
                String.format("http://%s:%d%s/%s", this.endpoint, this.endpointPort,
                        ContextPathUtil.normalizeContextPath(this.contentPath), this.serverListName));
        ...
    }

addressServerUrlTem=http://localhost:8080/nacos/china      
```

registration center - The address is incorrect
注册中心 - 地址错误
```java
com.alibaba.nacos.client.naming.core.ServerListManager#getServerListFromEndpoint
private List<String> getServerListFromEndpoint() {
        ...
        // Hard coded, configuration not supported  此处硬编码，不支持配置
        String urlString = HTTP_PREFIX + endpoint + "/nacos/serverlist";
        ...
}
urlString=http://localhost:8080/nacos/serverlist
```

**Expected behavior**
When nacos client use endpoint, the registration center should support configuring context-path and cluster-name like the configuration center
当nacos client使用endpoint时，注册中心应该像配置中心一样支持配置 context-path and cluster-name

**Actually behavior**
When nacos client use endpoint, the registration center not support configuring context-path and cluster-name
当nacos client使用endpoint时，注册中心不支持配置 context-path and cluster-name
