### ISSUE TITLE
Build Nacos2.2.3 Authentication Bug in Docker

### ISSUE THREAD

**Issue by Tokgos** [alibaba/nacos#10969]
# docker-compose.yaml
```
version: "3"
services:

  nacos:
    image: nacos/nacos-server
    container_name: nacos
    environment:
      MODE: cluster
      NACOS_SERVERS: xxx:8848 xxx:8848 xx:8848
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: 'xxx'
      MYSQL_SERVICE_PORT: "xxx"
      MYSQL_SERVICE_DB_NAME: "xxx"
      MYSQL_SERVICE_USER: "xxx"
      MYSQL_SERVICE_PASSWORD: "xxx"
      MYSQL_SERVICE_DB_PARAM: "characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true"
      JVM_XMS: 256m
      JVM_XMX: 512m
      JVM_XMN: 256m
      NACOS_AUTH_ENABLE: true
      NACOS_AUTH_TOKEN_EXPIRE_SECONDS: 86400
      NACOS_AUTH_TOKEN: xxx(base64)
      NACOS_AUTH_CACHE_ENABLE: true
      NACOS_AUTH_IDENTITY_KEY: xxx
      NACOS_AUTH_IDENTITY_VALUE: xxx
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    networks:
      - develop
    restart: always

networks:
  develop:
    external: true
```

# When building with a shell
Shell: ```docker-compose -f docker-compose.yaml up -d```
Result: ```ERROR: The Compose file 'docker-compose.yaml' is invalid because:
services.nacos.environment.NACOS_AUTH_ENABLE contains true, which is an invalid type, it should be a string, number, or a null```
# Nacos Document Configuration Description
 - https://nacos.io/zh-cn/docs/v2/quickstart/quick-start-docker.html
 - ![image](https://github.com/alibaba/nacos/assets/39108225/f91d57a3-dc17-4d1f-8a3b-d358051e298d)

So I checked and entered the internal system of Nacos to view the application.properties

There is no environment variable of ${NACOS_AUTH_ENABLE: false} and ${NACOS_AUTH_CACHE_ENABLE: false}
