### ISSUE TITLE
Nacos authentication

### ISSUE THREAD

**Issue by freemankevin** [alibaba/nacos#11107]
After Nacos turns on authentication, there is a problem in passing the environment variable of the user password.
---

**Invalid**
```Dockerfile
ENTRYPOINT ["java", "-jar", "app.jar", \
    "--spring.profiles.active=$SPRING_PROFILES_ACTIVE", \
    "--spring.cloud.nacos.discovery.server-addr=$SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR", \
    "--spring.cloud.nacos.config.server-addr=$SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR", \
    "--spring.cloud.nacos.username=$SPRING_CLOUD_NACOS_USERNAME", \
    "--spring.cloud.nacos.password=$SPRING_CLOUD_NACOS_PASSWORD"]
```

**Effective**
```Dockerfile
CMD java  -jar app.jar \
    --spring.profiles.active=$SPRING_PROFILES_ACTIVE \
    --spring.cloud.nacos.discovery.server-addr=$SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR \
    --spring.cloud.nacos.config.server-addr=$SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR \
    --spring.cloud.nacos.username=$SPRING_CLOUD_NACOS_USERNAME \
    --spring.cloud.nacos.password=$SPRING_CLOUD_NACOS_PASSWORD
```

The Endpoint method seems to discard all environment variables and cannot find Nacos normally. However, CMD is completely OK, and ENV transfer does not work. 

Here is the JAVA code:
```java
...
       Properties props = System.getProperties();
        props.setProperty("spring.cloud.nacos.discovery.server-addr", LauncherConstant.nacosAddr(profile));
        props.setProperty("spring.cloud.nacos.config.server-addr", LauncherConstant.nacosAddr(profile));
        props.setProperty("spring.cloud.nacos.config.shared-dataids", LauncherConstant.sharedDataIds(profile));
        props.setProperty("spring.cloud.nacos.config.refreshable-dataids", LauncherConstant.sharedDataIds(profile));
        props.setProperty("spring.cloud.nacos.username", "nacos");
        props.setProperty("spring.cloud.nacos.password", "nacos");
        builder.properties(props);
```

Here is compose.yaml: 
```yaml
version: '3'
x-service-template: &x-service-template
  restart: always
  extra_hosts:
    - "nacos-dev:10.1.1.1"
  environment:
    - SPRING_PROFILES_ACTIVE=dev
    - SPRING_CLOUD_NACOS_USERNAME=nacos
    - SPRING_CLOUD_NACOS_PASSWORD=!SoV7E8enp
  volumes:
    - /etc/localtime:/etc/localtime:ro
  networks:
    - app

services:
  gateway:
    <<: *x-service-template
    image: myharbor.mydomain.com/demo/gateway:v1
    container_name: gateway
    ports:
      - 80:80
...
```

Here is Dockerfile:
```Dockerfile
FROM myharbor.mydomain.com/demo/adoptopenjdk/openjdk8-openj9:alpine-slim

WORKDIR /home
ADD ./target/*.jar ./app.jar

#RUN useradd -ms /bin/bash appuser
#USER appuser

CMD java -Djava.security.egd=file:/dev/./urandom -jar app.jar \
    --spring.profiles.active=$SPRING_PROFILES_ACTIVE \
    --spring.cloud.nacos.discovery.server-addr=$SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR \
    --spring.cloud.nacos.config.server-addr=$SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR \
    --spring.cloud.nacos.username=$SPRING_CLOUD_NACOS_USERNAME\
    --spring.cloud.nacos.password=$SPRING_CLOUD_NACOS_PASSWORD
```

The strange thing is how to disable authentication, the Endpoint method is no different from the CMD method, and Nacos can be found normally.
