### ISSUE TITLE
nacos权限控制

### ISSUE THREAD

**Issue by lixianli1987** [alibaba/nacos#11413]
需求：
部署一台nacos，开启鉴权，配置管理与服务管理可以采用不同的命名空间么？具体如下：
1.创建多个nameSpace，如public、nm1、nm2
2.client1的config连接nm1(因此需要创建用户user1设置权限绑定nm1)，client1的discovery连接public(需要创建用户userpublic设置权限绑定public)
3.所有的应用(client)注册到服务端(server)时，都采用账号userpublic
4.每个应用的配置中心都对应自己的账号，如user1(绑定nm1)、user2(绑定nm2)
验证：
实际测试的过程中，获取配置与服务注册始终报错403！
理论：
请问如上的设想，目前nacos支持么?

**Comment by 985492783** [comment]
![image](https://github.com/alibaba/nacos/assets/73023513/ef499255-0d13-4d9e-b5dd-ab897f339d13)
![image](https://github.com/alibaba/nacos/assets/73023513/9b429812-a9ff-48f4-94fb-9b13ffb163ab)
```yaml
spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: prod
        username: prod
        password: prod
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  config:
    import:
      - nacos:server.yaml?refresh=true
  application:
    name: prod
```
拿springcloudAlibaba和springboot Nacos验证过后是没问题的，403可能是权限没给全，更多问题需要提供nacos-server和client的日志以及配置的权限，理论上这个也是可行的，本身config和naming是没有耦合关系的
