### ISSUE TITLE
about nacos api

### ISSUE THREAD

**Issue by wxywizard** [alibaba/nacos#11538]
**How to Reproduce**

When I use the api provided by nacos to publish my configurations the content parameter can only write part of my configurations to nacos successfully, is there a parameter size limitation done by the api?
> this is my command
```
    local content=$(<"./seata-nacos.conf")

    curl -X POST "$NACOS_SERVER/nacos/v2/cs/config" \
         -H "Content-Type: application/x-www-form-urlencoded" \
         -d "namespaceId=dev" \
         -d "group=SEATA_GROUP" \
         -d "dataId=seataServer.properties" \
         -d "content=$content"
```
> My file seata-nacos.conf has 20 lines of data, but it only transfers 9 configurations, of which the 9th one is only half of it

**Desktop (please complete the following information):**
 - OS: centos stream 9
 - Version nacos-server 2.3.0

**Comment by KomachiSion** [comment]
The problem is not relative to nacos, the API only receive part of data.

Maybe you should echo $content to see whether the content has some special word make the curl command send before content read finish.

**Comment by wxywizard** [comment]
> The problem is not relative to nacos, the API only receive part of data.
> 
> Maybe you should echo $content to see whether the content has some special word make the curl command send before content read finish.

hello，I am deploying nacos using docker compose and I want to send the configuration center data via the script mentioned above after nacos starts, but I can't call the script successfully after trying both command and entrypoint, is there any way to fix it?

this is my compose.yaml
```
nacos:
    image: nacos/nacos-server:v2.3.0
    container_name: nacos
    restart: on-failure:3
    networks:
      dev_network:
    volumes:
      - ./deploy-data/nacos-data/logs/:/home/nacos/logs
      - ./deploy/seata-server:/root/seata-server
    command: ["/bin/sh", "-c", "/root/seata-server/import-seata-config.sh"] 
    #entrypoint: ["/root/seata-server/import-seata-config.sh"] 
    ports:
      - "8848:8848"
      - "9848:9848"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/v2/core/cluster/node/self/health"]
      interval: 30s
      timeout: 10s
      retries: 3  
    environment:
      - PREFER_HOST_MODE=ip
      - NACOS_SERVER_IP=192.168.200.28
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=192.168.200.28
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      - NACOS_AUTH_IDENTITY_KEY=nacos
      - NACOS_AUTH_IDENTITY_VALUE=nacos
      - NACOS_AUTH_TOKEN=SecretKey0...
    depends_on:
      mysql:
        condition: service_healthy
```
