### ISSUE TITLE
spring.cloud.nacos.config.prefix配置无效

### ISSUE THREAD

**Issue by yibird** [alibaba/nacos#11547]
环境JDK21
Nacos Server:NACOS2.3.0
Spring Cloud Alibaba:2022.0.0.0
SpringBoot:3.2.0,由于SCA不支持SB3.2,启动项目会报错,为此我禁用了兼容性验证器配置。

application.yml配置如下:
```yaml
server:
  port: 9003
spring:
  application:
    name: config
  cloud:
    # Spring Cloud 兼容性验证器配置,由于SpringCloudAlibaba不支持SpringBoot3.2.0,因此需要禁用禁用兼容性验证器配置
    compatibility-verifier:
      # 禁用兼容性验证器配置
      enabled: false

    # Nacos配置
    nacos:
      config:
        # 服务器地址
        server-addr: 127.0.0.1:8848
        # 分组名
        group: DEFAULT_GROUP
        # 配置前缀,prefix是构成dataid的成员之一,如果不指定prefix,则默认使用spring.application.name
        prefix: config
        # 文件后缀
        file-extension: properties
        # 读取配置超时时间,默认3000ms
        timeout: 3000
        # 是否开启子自动刷新,默认true
        refresh-enabled: true
```
启动类如下:
```java
package com.fly;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.context.config.annotation.RefreshScope;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * @Description
 * @Author zchengfeng
 * @Date 2023/12/24 05:53:02
 */
@SpringBootApplication
@RestController
@RefreshScope // 开启自动刷新
public class NacosConfigApplication {
    public static void main(String[] args) {
        SpringApplication.run(NacosConfigApplication.class, args);
    }
    
    @Value("${configName}")
    private String configName;

    @Value("${configPort:0}")
    private int port;

    @GetMapping("/getName")
    public String getName() {
        return "configName:" + configName;
    }
    @GetMapping("/getPort")
    public String getPort() {
        return "port:" + port;
    }
}
```
在Nacos 控制台创建了config.properties dataid,如果不配置 spring.application.name 启动项目 Could not resolve placeholder 'configName' in value "${configName}", 但是添加  spring.application.name=config 项目正常启动,配置也能正常读取。而且Nacos 的extension-configs和shared-configs 也存在问题,明明创建对应的 dataid了,并且也指定dataid了仍无法读取。配置如下:

```yaml
server:
  port: 9003
spring:
  application:
    name: config
  cloud:
    # Spring Cloud 兼容性验证器配置,由于SpringCloudAlibaba不支持SpringBoot3.2.0,因此需要禁用禁用兼容性验证器配置
    compatibility-verifier:
      # 禁用兼容性验证器配置
      enabled: false

    # Nacos配置
    nacos:
      config:
        # 服务器地址
        server-addr: 127.0.0.1:8848
        # 分组名
        group: DEFAULT_GROUP
        # 配置前缀,prefix是构成dataid的成员之一,如果不指定prefix,则默认使用spring.application.name
        prefix: config
        # 文件后缀
        file-extension: properties
        # 读取配置超时时间,默认3000ms
        timeout: 3000
        # 是否开启子自动刷新,默认true
        refresh-enabled: true

        # 应用特有配置
        extension-configs:
          # dataid名称,dataid必须包含扩展名,spring.cloud.nacos.config.file-extension的配置对自定义扩展配置的 Data Id 文件扩展名没有影响
          - data-id: config-app.properties
            # 分组名
            group: DEFAULT_GROUP
            # 是否开启自动刷新
            refresh: true

        # 应用共享配置
        shared-configs:
          - data-id: common.yaml
            # 分组名
            group: DEFAULT_GROUP
            # 是否开启自动刷新
            refresh: true
#
#        # 用于控制配置文件导入检查的开关。该配置项的作用是检查在使用 Nacos 配置中心时,是否导入了 Spring Cloud Alibaba Nacos Config 的相关配置类,禁用此配置会导致N无法拉取Nacos配置
##        import-check:
##          enabled: false
#
```
