### ISSUE TITLE
k8sv1.24.2+nacos2.1.0 Inconsistency between the data displayed on the cluster page and the data pulled by the application service

### ISSUE THREAD

**Issue by youzizzz** [alibaba/nacos#11574]
**Describe the bug**
I've set up a three-node cluster environment on k8s, and I've made a change to one of the configurations via the admin page, but the project I've created via the spring-cloud-for-alibaba framework pulls the same configuration from nacos as it did prior to the change

**Expected behavior**
The data that the application service pulls from the nacos cluster should be consistent with the data displayed on the page

**Actually behavior**
The data that the application service pulls from the nacos cluster should not match the data displayed on the page
page
app server
![image](https://github.com/alibaba/nacos/assets/28948945/ebabc09f-fe80-45d3-98ac-98d6edd43500)

Below I post my nacos k8s build cluster yaml

```
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  namespace: scs
  labels:
    app: nacos-headless
spec:
  type: NodePort
  ports:
    - port: 8848
      name: server
      targetPort: 8848
      nodePort: 31848
    - port: 9848
      name: client-rpc
      targetPort: 9848
    - port: 9849
      name: raft-rpc
      targetPort: 9849
    ## 兼容1.4.x版本的选举端口
    - port: 7848
      name: old-raft-rpc
      targetPort: 7848
  selector:
    app: nacos
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
  namespace: scs
spec:
  serviceName: nacos-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: nacos-pod
          imagePullPolicy: IfNotPresent
          image: 192.168.40.19:81/cloud/nacos:v2.1.0
          resources:
            requests:
              memory: "256Mi"
              cpu: "256m"
          ports:
            - containerPort: 8848
              name: client
            - containerPort: 9848
              name: client-rpc
            - containerPort: 9849
              name: raft-rpc
            - containerPort: 7848
              name: old-raft-rpc
          env:
            - name: NACOS_REPLICAS
              value: "3"
            - name: SPRING_DATASOURCE_PLATFORM
              valueFrom:
                configMapKeyRef:
                  name: base-config
                  key: db.platform
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: base-config
                  key: db.host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: base-config
                  key: db.name
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: base-config
                  key: db.port
            - name: DB_CURRENT_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: base-config
                  key: db.schema
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: base-config
                  key: db.user
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: base-config
                  key: db.password
            - name: MODE
              value: "cluster"
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: NACOS_APPLICATION_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_SERVERS
              value: "nacos-0.nacos-headless.scs.svc.cluster.local:8848 nacos-1.nacos-headless.scs.svc.cluster.local:8848 nacos-2.nacos-headless.scs.svc.cluster.local:8848"
  selector:
    matchLabels:
      app: nacos
```
Please help me to troubleshoot what could be the cause of this, whenever I restart the nacos cluster and rollback the config file after that, the data is normal!
