### ISSUE TITLE
k8s 中部署了 3 个 nacos 节点，spring cloud alibaba 应该怎么配置

### ISSUE THREAD

**Issue by benfromchina** [alibaba/nacos#11623]
k8s 中部署了 3 个 nacos 节点，对应三个 headless 地址：

- nacos-0.nacos-headless.nacos.svc.cluster.local
- nacos-1.nacos-headless.nacos.svc.cluster.local
- nacos-2.nacos-headless.nacos.svc.cluster.local

Spring Cloud Alibaba 配置 nacos 地址有两种方式：

- 方式一：

```yml
spring:
  cloud:
    nacos:
      config:
        server-addr: nacos-headless.nacos.svc.cluster.local:8848
```

- 方式二：

```yml
spring:
  cloud:
    nacos:
      config:
        server-addr: nacos-0.nacos-headless.nacos.svc.cluster.local:8848,nacos-1.nacos-headless.nacos.svc.cluster.local:8848,nacos-2.nacos-headless.nacos.svc.cluster.local:8848
```

请问应该采用哪一种方式配置？这两种的区别是什么？
