### ISSUE TITLE
prometheus error 500 

### ISSUE THREAD

**Issue by 1148260649** [alibaba/nacos#11732]
# nacos 2.3.0 接入普罗米修斯(prometheus) 无法监控

* nacos 为伪集群配置（本地不同端口），节点信息如下
![nacos](https://github.com/alibaba/nacos/assets/45970803/80714fdc-7185-44fe-8e16-34c0cb877248)

* 错误页面如下 
![error](https://github.com/alibaba/nacos/assets/45970803/31ac2478-707f-402e-b593-76c9467a3a4f)

* 普罗米修斯 配置如下 
```yml
  - job_name: 'nacos-cluster'
    metrics_path: '/nacos/actuator/prometheus'
    static_configs:
      - targets: ["127.0.0.1:8848","127.0.0.1:8850","127.0.0.1:8852"]
        labels:
          instance: naocs cluster

```
* nacos/actuator/prometheus 信息如下
```txt
# HELP tomcat_global_request_max_seconds  
# TYPE tomcat_global_request_max_seconds gauge
tomcat_global_request_max_seconds{name="http-nio-8850",} 0.077
# HELP http_server_requests_seconds Duration of HTTP server request handling
# TYPE http_server_requests_seconds summary
http_server_requests_seconds_count{exception="HttpMediaTypeNotAcceptableException",method="GET",outcome="SERVER_ERROR",status="500",uri="root",} 4.0
http_server_requests_seconds_sum{exception="HttpMediaTypeNotAcceptableException",method="GET",outcome="SERVER_ERROR",status="500",uri="root",} 0.0648806
# HELP http_server_requests_seconds_max Duration of HTTP server request handling
# TYPE http_server_requests_seconds_max gauge
http_server_requests_seconds_max{exception="HttpMediaTypeNotAcceptableException",method="GET",outcome="SERVER_ERROR",status="500",uri="root",} 0.0540382
```

**Comment by KomachiSion** [comment]
如果手动执行curl 127.0.0.1:8848/nacos/actuator/prometheus 可以获取到数据， 那就说明和nacos无关，环境问题需要自行排查解决。

**Comment by 1148260649** [comment]
> 如果手动执行curl 127.0.0.1:8848/nacos/actuator/prometheus 可以获取到数据， 那就说明和nacos无关，环境问题需要自行排查解决。

虽然 这个地址可以访问，不过该页面还是存在错误信息500
![error](https://github.com/alibaba/nacos/assets/45970803/6061785a-2e49-4e3c-b911-b1de52588e89)

**Comment by KomachiSion** [comment]
本地能curl出来说明nacos-server是没问题的， 如果采集器始终报错500， 有可能是采集器发起的参数有问题，导致server端解析http请求出错， 这种问题常见于使用了vpn等网络中转设施时。

**Comment by 1148260649** [comment]
> 本地能curl出来说明nacos-server是没问题的， 如果采集器始终报错500， 有可能是采集器发起的参数有问题，导致server端解析http请求出错， 这种问题常见于使用了vpn等网络中转设施时。

"采集器发起的参数"  这个是指nacos 启动的 服务端 存在问题吗？  是配置文件的内容吗？

**Comment by KomachiSion** [comment]
> > 本地能curl出来说明nacos-server是没问题的， 如果采集器始终报错500， 有可能是采集器发起的参数有问题，导致server端解析http请求出错， 这种问题常见于使用了vpn等网络中转设施时。
> 
> "采集器发起的参数" 这个是指nacos 启动的 服务端 存在问题吗？ 是配置文件的内容吗？

你截图里的第二个截图

**Comment by KomachiSion** [comment]
nacos只是数据的exporter，你能curl到数据， 说明nacos 是正常的， 能够export数据。

是采集监控数据的那个节点或者程序存在问题，看报错应该是Http 的 media-type有问题。

**Comment by 1148260649** [comment]
> nacos只是数据的exporter，你能curl到数据， 说明nacos 是正常的， 能够export数据。
> 
> 是采集监控数据的那个节点或者程序存在问题，看报错应该是Http 的 media-type有问题。

这个 "Http 的 media-type" 是需要在 prometheus 上进行配置吗？还是如何操作？

>> 我看 nacos/actuator/prometheus 这个页面提供的信息 存在500 的错误 老是感觉是nacos 在启动的时候存在问题导致的 

prometheus 是直接官网下载的 配置的信息只有下面的内容 没有做什么其他调整
```yml
  - job_name: 'nacos-cluster'
    metrics_path: '/nacos/actuator/prometheus'
    static_configs:
      - targets: ["127.0.0.1:8848","127.0.0.1:8850","127.0.0.1:8852"]
        labels:
          instance: naocs cluster

```
