### ISSUE TITLE
Spring Cloud 整合 Nacos 内网穿透问题

### ISSUE THREAD

**Issue by tcscat** [alibaba/nacos#11789]
```yml
spring:
  cloud:
    nacos:
      server-addr: https://tcscat-nacos.com
```

在使用第三方内网穿透服务时，server-addr 所填写的地址只能穿透 8848端口，但是 还需要grpc还需要9848端口。这时应该怎么办呢，能否使用其他配置 指定 grpc的地址+端口呢
