### ISSUE TITLE
Services in the same NS, but can't find services in another group.

### ISSUE THREAD

**Issue by youyinnn** [alibaba/nacos#11962]
## Issue Description

Type: Question

### Describe what happened (or what feature you want)

I have the following services:
1. Service B: a spring cloud gateway in NS: dev, Group: infra;
2. Service A: a business service in NS: dev, Group: svc;

I can't access the service B through the gateway service A.

But when I put then into the same group (default one), it works.

### Describe what you expected to happen

Any request to service B should be passed to service A based on the gateway configuration.

### How to reproduce it (as minimally and precisely as possible)

Gateway bootstrap
``` yml
spring:
  application:
    #    this should be the same as the data.id configuration
    name: ${SWC_TARGET}
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR}
      username: ${NACOS_SERVER_USERNAME}
      password: ${NACOS_SERVER_PASSWORD}
      discovery:
        group: infra
        namespace: ${SPRING_ENV}
        ephemeral: false
      config:
        group: infra
        namespace: ${SPRING_ENV}
        file-extension: yaml
```

app config:
``` yml
server:
  servlet:
    context-path: /${SWC_TARGET}
  port: ${SWC_SERVICE_PORT:8081}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri:  lb://auth
          predicates: Path=/auth/**
```

Service A bootstrap
``` yml
spring:
  application:
    #    this should be the same as the data.id configuration
    name: ${SWC_TARGET}
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR}
      username: ${NACOS_SERVER_USERNAME}
      password: ${NACOS_SERVER_PASSWORD}
      discovery:
        group: svc
        namespace: ${SPRING_ENV}
        ephemeral: false
      config:
        group: svc
        namespace: ${SPRING_ENV}
        file-extension: yaml
```

### Configure Practice

I use the `SPRING_ENV` to define the namespace, and use namespace to separate the dev/prod/test.
Then I use Group to separate different services: infrastructure, business service, etc.

### Tell us your environment

Nacos SDK version in both services
``` xml
<!-- https://mvnrepository.com/artifact/com.alibaba.cloud/spring-cloud-starter-alibaba-nacos-discovery -->
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
    <version>2023.0.0.0-RC1</version>
</dependency>

<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
    <version>2023.0.0.0-RC1</version>
</dependency>
```

Gateway versions, should be 4.1.2 under spring-boot 3.2.4
``` XML
  <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-gateway</artifactId>
  </dependency>

  <!-- https://github.com/alibaba/nacos/issues/2568#issuecomment-868399381 -->
  <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-loadbalancer</artifactId>
  </dependency>
```

Nacos Server version: nacos/nacos-server:v2.3.2

### More

There are similar questions being asked, but closed without clear solutions, e.g: https://github.com/alibaba/nacos/issues/3193

**Comment by youyinnn** [comment]
I follow the solution at https://www.cnblogs.com/sun2020/p/17159435.html. Now the gateway can access the service in other groups. I wonder are there any potential issues with this solution?



The rewrite `NacosServiceDiscovery` class:
``` java
@Slf4j
public class NacosServiceDiscoveryRemake extends NacosServiceDiscovery {

    private final NacosDiscoveryProperties discoveryProperties;
    private final NacosServiceManager nacosServiceManager;
    private final NacosDiscoveryAutoConfig nacosDiscoveryAutoConfig;

    public NacosServiceDiscoveryRemake(
            NacosDiscoveryProperties discoveryProperties,
            NacosServiceManager nacosServiceManager,
            NacosDiscoveryAutoConfig nacosDiscoveryAutoConfig) {
        super(discoveryProperties, nacosServiceManager);
        this.nacosDiscoveryAutoConfig = nacosDiscoveryAutoConfig;
        this.discoveryProperties = discoveryProperties;
        this.nacosServiceManager = nacosServiceManager;
    }

    @Override
    public List<ServiceInstance> getInstances(String serviceId) throws NacosException {
        List<ServiceInstance> groupInstances = super.getInstances(serviceId);
        List<String> routeServiceIds = nacosDiscoveryAutoConfig.routes().stream().map(r -> r.get("id").toString()).toList();
        String toAlsoGroups = discoveryProperties.getMetadata().get("toAlsoGroups");
        List<ServiceInstance> instancesOfOuterGroups = new ArrayList<>();
        if (toAlsoGroups != null) {
            String[] groups = toAlsoGroups.split(",");
            for (String group : groups) {
                for (String routeServiceId : routeServiceIds) {
                    List<Instance> healthyAndRoutedInstanceOfGroup = nacosServiceManager
                            .getNamingService().selectInstances(routeServiceId, group, true);
                    instancesOfOuterGroups.addAll(hostToServiceInstanceList(healthyAndRoutedInstanceOfGroup, serviceId));
                }
            }
        }
        if (!instancesOfOuterGroups.isEmpty()) {
            instancesOfOuterGroups.forEach(nsi -> {
                log.info("Look also: InstanceId %s at %s:%s".formatted(nsi.getInstanceId(), nsi.getHost(), nsi.getPort()));
            });
        }
        groupInstances.addAll(instancesOfOuterGroups);
        return groupInstances;
    }
}
```

The Additional Config:

``` java
@Configuration
@AutoConfigureBefore(NacosDiscoveryAutoConfiguration.class)
public class NacosDiscoveryAutoConfig {

    @Bean
    @ConfigurationProperties(prefix = "spring.cloud.gateway.routes")
    public List<Map<String, Object>> routes() {
        return new ArrayList<>();
    }

    @Bean
    @ConditionalOnMissingBean
    public NacosServiceDiscovery nacosServiceDiscovery(
            NacosDiscoveryProperties discoveryProperties, NacosServiceManager nacosServiceManager
    ) {
        return new NacosServiceDiscoveryRemake(discoveryProperties,
                nacosServiceManager, this);
    }
}
```

I use metadata to define outer groups to be searched in the bootstrap.yml:
``` yml
spring:
  application:
    #    this should be the same as the data.id configuration
    name: ${SWC_TARGET}
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR}
      username: ${NACOS_SERVER_USERNAME}
      password: ${NACOS_SERVER_PASSWORD}
      discovery:
        namespace: ${SPRING_ENV}
        ephemeral: false
        metadata:
          # look also the service in the svc group
          toAlsoGroups: svc
      config:
        group: infra
        namespace: ${SPRING_ENV}
        file-extension: yaml
```

I also got the logs indicating that the gateway traffic has been successfully load-balanced to the two authentication services I have.

``` log
24-04-14 19:36:35 - INFO 31760 [         boundedElastic-7] [:55  ] i.s.g.c.NacosServiceDiscoveryRemake      : Look also: InstanceId 192.168.2.33#8087#DEFAULT#svc@@auth at 192.168.2.33:8087
24-04-14 19:36:35 - INFO 31760 [         boundedElastic-7] [:55  ] i.s.g.c.NacosServiceDiscoveryRemake      : Look also: InstanceId 192.168.2.33#8080#DEFAULT#svc@@auth at 192.168.2.33:8080
```
