### ISSUE TITLE
【将服务从nacos上下线后一直还能接收到请求】Requests continue to be received after the service is offline from nacos

### ISSUE THREAD

**Issue by dxiyang** [alibaba/nacos#12077]
【微服务架构，上层网关，下面有个服务A，服务A启动了两个实例，nacos是集群部署的】The microservice architecture, the upper gateway, has A service A underneath it, and Service A starts two instances, nacos is deployed in clusters

1、【用jemter一直模拟请求，然后将服务A的某个示例下线，按理来说过30秒左右该实例不会收到请求】
Using jemter to simulate requests all the time, and then taking an example of service A offline, the instance should not receive requests after 30 seconds or so
2、【但是经过几轮jmeter测试，只有一两次下线后是正常的，其余的轮次在下线后还会有请求】
However, after several rounds of jmeter tests, only one or two offline are normal, and the rest of the rounds will still have requests after offline

**备注：nacos和服务不在一个局域网内**

**Comment by KomachiSion** [comment]
1. 网关是否自身有地址缓存，更新频率比较低？
2. 看nacos的client日志，看下是否已经获取到了新地址。

**Comment by dxiyang** [comment]
你好，网关没有地址缓存；

我通过设置如下参数解决了该问题
```
spring:  
  cloud:
    nacos:
      discovery:
        metadata:
          preserved.heart.beat.interval: 1000 #心跳间隔。时间单位:毫秒。心跳间隔
          preserved.heart.beat.timeout: 3000 #心跳暂停。时间单位:毫秒。 
          preserved.ip.delete.timeout: 3000 #Ip删除超时。时间单位:毫秒。 
```

有个疑问 ，将上面的参数时间设置变小，会不会影响到naocs，生产用这些参数会产生什么影响？？谢谢
