### ISSUE TITLE
Nacos Docker Container Fails to Connect to MySQL with "No DataSource set" Error

### ISSUE THREAD

**Issue by lijie123bes** [alibaba/nacos#12209]
**Describe the bug**
I am trying to set up the Nacos server with MySQL using Docker and Docker Compose, but I'm running into a connection issue where Nacos fails to start with a No DataSource set error. I've checked my configurations multiple times, but I'm stuck and could use some fresh eyes on it.
```yaml
version: "3"
services:
  nacos:
    image: nacos/nacos-server:v2.3.1
    container_name: nacos-standalone-mysql
    env_file:
      - ./env/nacos-standlone-mysql.env
    volumes:
      - ./logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    restart: always
    privileged: true
    networks:
      nacos_net:
        ipv4_address: 172.172.172.2
  mysql-nacos:
    hostname: mysql-nacos
    image: mysql:8.0.30
    container_name: mysql-nacos
    privileged: true
    command: --character-set-server=utf8mb4 --max_connections=2000 --max_allowed_packet=64M
    env_file: 
      - ./env/mysql-nacos.env
    volumes: 
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/
    expose: 
      - "3306"
    networks: 
      nacos_net:
        ipv4_address: 172.172.172.3
networks:
  nacos_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.172.0.0/16
```

Here is my docker-compose YAML file named standalone-mysql-8.yaml:
```yaml
# Nacos-related configurations
PREFER_HOST_MODE=ip
MODE=standalone
SPRING_DATASOURCE_PLATFORM=mysql
MYSQL_SERVICE_HOST=172.172.172.3
MYSQL_SERVICE_DB_NAME=db_nacos        
MYSQL_SERVICE_PORT=3306
MYSQL_SERVICE_USER=nacos
MYSQL_SERVICE_PASSWORD=<PASSWORD>
MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&userSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
NACOS_AUTH_IDENTITY_KEY=2222
NACOS_AUTH_IDENTITY_VALUE=2xxx
NACOS_AUTH_TOKEN=<TOKEN>
JVM_XMS=128m
JVM_XMX=128m
JVM_XMN=128m
```

**Expected behavior**

**Actually behavior**
When I start the containers, the Nacos container fails with the following error message in the logs:
```yaml
Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure : No DataSource set
```

**How to Reproduce**
I have verified that the MySQL container starts properly and that the db_nacos database exists with the correct permissions for the nacos user. The network settings seem correct, and the containers are running on the same Docker network. Despite this, Nacos cannot connect to MySQL.

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
