### ISSUE TITLE
Dubbo uses Nacos as the registration center, and the consumer side will not appear in the service list

### ISSUE THREAD

**Issue by Lake-zhang** [alibaba/nacos#12345]
The project dependency information is as follows:
<java.version>17</java.version>
<spring-boot.version>3.0.13</spring-boot.version>
<dubbo.version>3.2.9</dubbo.version>
<nacos-client.version>2.2.2</nacos-client.version>
Nacos Server Version: 2.2.2
I have created two services, provider and consumer, locally using Java code. The provider is responsible for providing DubboService interface for Dubbo, while the consumer calls the provider interface through DubboReference. The project has started normally, and consumers can also retrieve provider information from Nacos. Then I was able to successfully call the data of the provider service by calling the HTTP interface exposed by the consumer, indicating that Dubbo is working properly. But in the Nacos console, the service list only contains information about providers, but not about consumers. I don't know if it's normal.

Here is the configuration information:
privider:
```
server:
  port: 14511
spring:
  application:
    name: provider-service
  main:
    allow-bean-definition-overriding: true
dubbo:
  application:
    name: provider-service
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    base-packages: com.test.provider.service.impl
  protocol:
    name: dubbo
    port: 15511
```

consumer:
```
server:
  port: 14510
spring:
  application:
    name: consumer-serivce
  main:
    allow-bean-definition-overriding: true
dubbo:
  application:
    name: consumer-serivce
  registry:
    address: nacos://127.0.0.1:8848
```
Nacos Console Service List:
![image](https://github.com/user-attachments/assets/d0014938-fd29-476b-9826-3a942f34c199)

But if I lower the springboot version to version 2. x and the dubbo version to version 2. x, both provider and consumer information will appear in the Nacos console service list. So I don't know if this is a compatibility issue or where in my project I need to modify or configure it.
