### ISSUE TITLE
After the service provider passes the nginx proxy port, it reports 400 when accessing through the gateway.

### ISSUE THREAD

**Issue by wangyang1749** [alibaba/nacos#12480]
**Describe the bug**

I want a service to be registered on two Nacos with public IP addresses but no local network connection. One of the nacos in this service is together, another nacos needs to access the service through a public IP address. So I think of the public network IP of the service through Nginx agent. But when I configured, I got 400 through the spring cloud gateway access.

**Expected behavior**
I hope the port of this nginx proxy pretends to be a service provider, and the public network address of this proxy is managed by Nacos.

```
    server {
        listen 30040;
        location / {
                proxy_pass http://192.168.10.30:30040;
                proxy_set_header Host $http_host;
        }
    }
```
There is no problem accessing directly on the proxy's host
```
curl  http://192.168.10.176:30040/hello
```

**Actually behavior**
Obtained 400 through spring cloud gateway access

```
curl http://192.168.10.176:30000/service-message/hello
```
Configuration of spring cloud gateway 
```
        - id: mbiolance-service-message
          uri: lb://mbiolance-service-message
          predicates:
            - Path=/service-message/**
          filters:
            - StripPrefix=1
```

 - OS:Ubuntu
 - nacos-server:v2.3.0
 
```
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.alibaba.cloud</groupId>
        <artifactId>spring-cloud-alibaba-dependencies</artifactId>
        <version>2.2.5.RELEASE</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>Hoxton.SR8</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
  </dependencyManagement>
```
