### ISSUE TITLE
Nacos unable to publish flow control rules to Sentinel Dashboard

### ISSUE THREAD

**Issue by Zengwenliang0416** [alibaba/nacos#12543]
**Describe the bug**
Nacos unable to publish flow control rules to Sentinel Dashboard

**Expected behavior**
Nacos releases flow control rules that can be synchronized to Sentinel Dashboard

**Actually behavior**
# 【Bug】Nacos unable to publish flow control rules to Sentinel Dashboard

> Version Description:nacos=2.4.0、Sentinel Dashborad=1.8.8、spring.cloud.alibaba.version=2023.0.1.2

## dependencies

```xml
<!-- sentinel-gateway依赖 -->
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-alibaba-sentinel-gateway</artifactId>
</dependency>
<!-- sentinel-datasource-nacos依赖 -->
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-datasource-nacos</artifactId>
</dependency>
```

## application.yaml

```yaml
spring:
  cloud:
    nacos:
      server-addr:  # Nacos server address
      username: # Nacos username
      password: # Nacos password
      discovery: #  [Configuration Center] Configuration Items
        namespace: dev # Namespace. We use the dev development environment here
        group: DEFAULT_GROUP # The Nacos configuration group used defaults to DEFAULT_GROUP
      config: # [Registration Center] Configuration Items
        namespace: dev # Namespace. We use the dev development environment here
        group: DEFAULT_GROUP # The Nacos configuration group used defaults to DEFAULT_GROUP
    sentinel:
      datasource:
        r1:
          nacos:
            username: 
            password: 
            namespace: dev
            server-addr: # Nacos server address
            data-id: ${spring.application.name}-sentinel
            group-id: DEFAULT_GROUP
            rule-type: flow
      transport:
        dashboard: 127.0.0.1:8080
        client-ip: 127.0.0.1
```

## Nacos configuration flow control

Since microservices are created using the 'dev' namespace, configurations need to be created in the 'dev' namespace.

```json
[
	{
        "resource": "system-admin-api",
        "resourceMode": 0,
        "count": 10,
        "grade": 1,
		"controlBehavior": 0,
        "intervalSec": 10,
        "burst": 0,
        "maxQueueingTimeoutMs": 1000
	}
]
```

<img width="1495" alt="image-20240823110214338" src="https://github.com/user-attachments/assets/96114a53-ad2f-4208-970c-c5bf927472e5">
<img width="1511" alt="image-20240823110601723" src="https://github.com/user-attachments/assets/2dd61699-c014-407c-9523-6cda5ed25b89">

At this point, we can see that the QPS we have set is 10, and then start Sentinel Dashboard, gateway, and corresponding business microservices.

When accessing the system admin API service, it can be seen that there is no problem accessing when QPS is set to 10.

<img width="1506" alt="image-20240823111259823" src="https://github.com/user-attachments/assets/391cb8eb-f8e9-4531-9897-05287b9b9441">

Modify Nacos configuration for current limiting (change count to 2)

<img width="1189" alt="image-20240823111430213" src="https://github.com/user-attachments/assets/92b02445-524e-4a45-90af-7c33f294021e">
By checking the record log of Sentinel, it can be seen that the modification has been successful.

<img width="1347" alt="image-20240823111604519" src="https://github.com/user-attachments/assets/566133f4-74bf-425b-88d4-0c76b4358e37">

After testing, it was found that it has already taken effect. If three requests are sent within 1 second, one will be intercepted.

<img width="1225" alt="image-20240823111854845" src="https://github.com/user-attachments/assets/c8f5bf58-030d-45fa-a0c7-b6b9e5640846">
However, the Sentinel Dashboard did not display the corresponding value.

<img width="1489" alt="image-20240823112005888" src="https://github.com/user-attachments/assets/d6bc989b-0bac-450d-9b6e-4e71d0dba421">

### Situation 1

In the above situation, we directly added flow control rules and set the threshold of QPS to 10.

<img width="1510" alt="image-20240823112259985" src="https://github.com/user-attachments/assets/e1ef236d-cd6d-478d-b786-6629e451b7bd">
It can be seen that it has not taken effect yet

<img width="1224" alt="image-20240823112409493" src="https://github.com/user-attachments/assets/8b2e15b8-0da0-4f57-8f27-d6b6066081dd">
But the dashboard console shows that the modification was successful.

<img width="1329" alt="image-20240823112548749" src="https://github.com/user-attachments/assets/ebc11721-c066-48dc-b148-d829df169af8">

### Situation 2

Restart the gateway and other services, first configure from the dashboard and then from Nacos

At this point, the configuration in Nacos is as follows

```json
[
	{
        "resource": "system-admin-api",
        "resourceMode": 0,
        "count": 2,
        "grade": 1,
		"controlBehavior": 0,
        "intervalSec": 10,
        "burst": 0,
        "maxQueueingTimeoutMs": 1000
	}
]
```

The flow control rule interface of the dashboard is as follows. As it is read from memory, each flow control rule needs to be reconfigured.

<img width="1270" alt="image-20240823112842025" src="https://github.com/user-attachments/assets/a4ed33f1-e494-4df8-ae8e-7e9c36d72cd8">
But from the real-time monitoring panel, it can be seen that the configuration in Nacos has already taken effect

<img width="1222" alt="image-20240823112958524" src="https://github.com/user-attachments/assets/0392970d-f132-454a-81b3-62a18d757043">
At this point, configure the flow control rules through the dashboard to set QPS to 1.

<img width="1249" alt="image-20240823113314096" src="https://github.com/user-attachments/assets/4678d222-dfa7-42ea-bf4b-590264b5170e">
You can see that it has already taken effect

<img width="1266" alt="image-20240823113406477" src="https://github.com/user-attachments/assets/63c9f5d6-c007-4bf7-97f8-007755237412">
Then go to Nacos to release the following configuration

<img width="1191" alt="image-20240823113444349" src="https://github.com/user-attachments/assets/bd3e8d0e-f13c-4e25-84ec-37fc0fd9c513">
In the sentinel record log, it can be seen that the update has been made

<img width="1349" alt="image-20240823113542232" src="https://github.com/user-attachments/assets/06b9e282-94fe-4244-af83-dcca53d1b6c4">
But in actual testing, the update failed

<img width="1234" alt="image-20240823113653367" src="https://github.com/user-attachments/assets/02c7ab9e-c284-4aeb-afa9-001612065dd4">
At the same time, the QPS of the flow control rules displayed in the dashboard has not changed.

<img width="1238" alt="image-20240823113717103" src="https://github.com/user-attachments/assets/f2c48ddd-dd74-44a0-8324-39154c8b5381">

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version nacos-server 2.4.0
 - Module config
 - SDK spring-cloud-alibaba-nacos
**Additional context**
