### ISSUE TITLE
Naccos 进入后台任何页面报错

### ISSUE THREAD

**Issue by leilei542** [alibaba/nacos#12694]
我根据官网发文档在下载的
然后进入nacos管理界面后 任何一个页面 刷新都会报错：caused: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;;caused: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;;
Nacos版本：NACOS V2.4.2
模式：standalone
日志：
[standalone-logs.zip](https://github.com/user-attachments/files/17132793/standalone-logs.zip)

报错图：
![微信图片_20240925223215](https://github.com/user-attachments/assets/f3166610-2eae-400e-9286-888b8f141ed1)
Yml: 
```
version: "3.8"
services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone-mysql
    env_file:
      - ../env/nacos-standlone-mysql.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    networks:
      - mysql_default  # 加入现有的 mysql_default 网络
```
