### ISSUE TITLE
基于bootstrap.yml的配置方式和基于application.yml的配置方式， Nacos配置user.name的行为差异

### ISSUE THREAD

**Issue by DJX-A** [alibaba/nacos#12712]
**Describe the bug**
基于bootstrap.yml的配置方式和基于application.yml的配置方式，Nacos配置项user.name的行为差异

```java
public static void main(String[] args) throws Exception {
      ConfigurableApplicationContext run = SpringApplication.run(DemoApplication.class, args);
      while (true) {
          String name = run.getEnvironment().getProperty("user.name");
          String age = run.getEnvironment().getProperty("user.age");
          log.info("user name: {} ", name);
          log.info("user age: {}", age);
          Thread.sleep(1000);
      }
  }
```

bootstrap.yml:
```yaml
spring:
  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848
      config:
        name: main
        namespace: 0ca68ca8-33be-4990-aaf3-d17b04e72cc6
        group: dev
        file-extension: yaml
        refresh-enabled: true
```

application.yml:
```yaml
spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: 0ca68ca8-33be-4990-aaf3-d17b04e72cc6
        name: main
        file-extension: yaml
        group: dev
        refresh-enabled: true

  config:
    import:
      - nacos:main?refreshEnabled=true&group=dev
```

```xml
<dependencyManagement>
      <dependencies>
          <dependency>
              <groupId>org.springframework.boot</groupId>
              <artifactId>spring-boot-dependencies</artifactId>
              <version>2.6.13</version>
              <type>pom</type>
              <scope>import</scope>
          </dependency>
          <dependency>
              <groupId>org.springframework.cloud</groupId>
              <artifactId>spring-cloud-dependencies</artifactId>
              <version>2021.0.5</version>
              <type>pom</type>
              <scope>import</scope>
          </dependency>
          <dependency>
              <groupId>com.alibaba.cloud</groupId>
              <artifactId>spring-cloud-alibaba-dependencies</artifactId>
              <version>2021.0.6.0</version>
              <type>pom</type>
              <scope>import</scope>
          </dependency>
      </dependencies>
  </dependencyManagement>
```
![image](https://github.com/user-attachments/assets/70d0c613-6a5d-467c-8d49-af976d730519)
实测发现：
 在main中配置
```yaml
user:
  name: 测试
 age: 20
```
在基于bootstrap.yml的配置方式下生效，并且能正确输出，在修改相应值后也会实时输出修改后的值
在基于application.yml的配置下，只会输出本机电脑用户名，并且修改后，日志会输出检测到修改了，但是实际输出的值依旧是本机电脑的用户名，而user.age能正确输出且能响应修改

目前仅发现user.name这个配置项有这个问题

**Desktop (please complete the following information):**
 - OS: win11[23H2]
 - Version [nacos-server 2.3.2, nacos-client 2.2.0]
