### ISSUE TITLE
k8s部署的nacos集群，开启metircs，无法通过变量传递配置给application.properties

### ISSUE THREAD

**Issue by Umbrallerstackcode** [alibaba/nacos#12780]
无论是监控k8s集群的nacos集群pod，还是通过接口Open API获取集群状态信息，都是需要开始metrics，但是这时候发现开启metres需要修改application.properties，参数为nacos.metrics.exporter.prometheus.enabled=true和management.endpoints.web.exposure.include=*

查看pod中的application.properties配置，也是需要直接修改，那要是在nacos集群节点多的情况下，手动修改的量就很大，有没有为pod传递变量的形式，例如：NACOS_SERVICE_PORT像这种变量传递给pod，那这样就可以为nacos集群的多个节点开启metrics

application.properties配置如下图：
![image](https://github.com/user-attachments/assets/8b99d454-1b9f-4290-8aee-ab768b847f2a)

官方文档说明：
https://nacos.io/docs/v2/guide/admin/monitor-guide/#deploy-nacos-cluster-to-expose-metrics-data

请问各位大佬，有没有为pod传递变量的方式开启metrics？？

**Comment by Umbrallerstackcode** [comment]
好的，感谢，我试试

**Comment by Umbrallerstackcode** [comment]
还有一个问题，k8s部署的nacos集群，如何获取每个pod的监控数据，我看http://192.168.123.240:60028/nacos/actuator/prometheus这样获取的数据无法看出关于pod ID的相关信息，大佬能否提供下方法，非常感谢

**Comment by Umbrallerstackcode** [comment]
![image](https://github.com/user-attachments/assets/8e6f21b5-a199-43c2-a734-54cb810ded2a)
你好，按照你说的配置，改完，重启pod之后，无法访问
![image](https://github.com/user-attachments/assets/18d46d11-42c3-499b-983c-a1b58359fa80)

**Comment by Umbrallerstackcode** [comment]
![image](https://github.com/user-attachments/assets/fe25d252-e7b9-449e-8a7e-e69e330aa679)
![image](https://github.com/user-attachments/assets/db03c0ad-39d1-4cb6-beab-671a5cc0953b)
![image](https://github.com/user-attachments/assets/8f7be60c-53be-495f-8838-38fde73806f0)
上面是启动日志截图

下面是容器pod的容器内环境变量
![image](https://github.com/user-attachments/assets/280998ef-e14d-4a35-9630-9c9951ea33ea)
![image](https://github.com/user-attachments/assets/0f4823a3-f645-47d5-8b8f-0ba6f263d3f9)

**Comment by fuhouyu** [comment]
> ![image](https://private-user-images.githubusercontent.com/102168892/379764593-fe25d252-e7b9-449e-8a7e-e69e330aa679.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NzMyMTgsIm5iZiI6MTcyOTc3MjkxOCwicGF0aCI6Ii8xMDIxNjg4OTIvMzc5NzY0NTkzLWZlMjVkMjUyLWU3YjktNDQ5ZS04YTdlLWU2OWUzMzBhYTY3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxMjI4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTUyOGQ1MTU2MTE1NWMyOGY5MDZhZWE3NDY1Zjk3Y2Q5MDlmMDM4N2YzOTY1MzY2ZmI0ODI1MTg2YWI2MzhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oF9w9igRjPa4zNs6PWWtpROpJZqmivJrrqQr_VDeb2I) ![image](https://private-user-images.githubusercontent.com/102168892/379764837-db03c0ad-39d1-4cb6-beab-671a5cc0953b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NzMyMTgsIm5iZiI6MTcyOTc3MjkxOCwicGF0aCI6Ii8xMDIxNjg4OTIvMzc5NzY0ODM3LWRiMDNjMGFkLTM5ZDEtNGNiNi1iZWFiLTY3MWE1Y2MwOTUzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxMjI4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDc4YzgwMmI0ZGUxZThhMTA0MWE4ZTEyNzcxMjJjNTBkNTFlMzFmZTJmYjIzMjZjMzU4OTE4OTNmMTQyNWE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NUcJsXH47Hcd6qvXYTUF_iboAQy2zAkm2DHA_VisfYA) ![image](https://private-user-images.githubusercontent.com/102168892/379764990-8f7be60c-53be-495f-8838-38fde73806f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NzMyMTgsIm5iZiI6MTcyOTc3MjkxOCwicGF0aCI6Ii8xMDIxNjg4OTIvMzc5NzY0OTkwLThmN2JlNjBjLTUzYmUtNDk1Zi04ODM4LTM4ZmRlNzM4MDZmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxMjI4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGU0NjY4NWU4ODFiYWEzMDE5ODNiODI5NThhOWY5NjNkOGRhNGY0ZWE4MDkyMjYyYWI5ODAxYjk3ZmY0YjViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SEYo6KtRsh0_agdfQ0Y4s2m2RRxPTKTC82Ce12NjKqU) 上面是启动日志截图
> 
> 下面是容器pod的容器内环境变量 ![image](https://private-user-images.githubusercontent.com/102168892/379765719-280998ef-e14d-4a35-9630-9c9951ea33ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NzMyMTgsIm5iZiI6MTcyOTc3MjkxOCwicGF0aCI6Ii8xMDIxNjg4OTIvMzc5NzY1NzE5LTI4MDk5OGVmLWUxNGQtNGEzNS05NjMwLTljOTk1MWVhMzNlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxMjI4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDc0YmExYjVmZmY4MTkxMzY1MzBlZDc2Y2RiZjMxMzQ4MGE3ZmM3OWVlZTY3M2UzOTMxYmIzZjdjYzg4NzMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2GDpK1qa124nlL0In2zBHmJEvIavVFVgQ8MI_mP85GY) ![image](https://private-user-images.githubusercontent.com/102168892/379765852-0f4823a3-f645-47d5-8b8f-0ba6f263d3f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NzMyMTgsIm5iZiI6MTcyOTc3MjkxOCwicGF0aCI6Ii8xMDIxNjg4OTIvMzc5NzY1ODUyLTBmNDgyM2EzLWY2NDUtNDdkNS04YjhmLTBiYTZmMjYzZDNmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxMjI4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTc2NGI0M2NkZGY5ZWQ1NGMwMzZkZGMzMWVkMTg2OWMwZjZhMDE3ZTU1NjM5ZTk3NzE3MTY5YWIxN2ZhMTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.s-2xrnaRUoaSJmeFoeznWavB-KhpReaAcXS5f14oloQ)

从你的截图来看，JAVA_OPT变量并未传递进去。nacos日志打印没有这个参数，系统变量里面也没有。

找了个k8s环境，测试如下：
<img width="1888" alt="image" src="https://github.com/user-attachments/assets/018114de-6114-491e-b966-3bff34006321">
请求返回：
<img width="877" alt="image" src="https://github.com/user-attachments/assets/960d9e9a-665f-4c9d-ac9a-2a13a536cfa1">

k8s yaml
<img width="1085" alt="image" src="https://github.com/user-attachments/assets/10968b57-5621-4ac6-a96a-5691d1f08b46">

**Comment by fuhouyu** [comment]
> 我的k8s是1.28.2版本，用的是containerd的运行时，你的是什么版本

这个是1.31版本，看截图你的yaml像是未生效，环境变量未传递进去
以下是完整的yaml，你可以参考下。

```
apiVersion: v1
kind: Service
metadata:
  name: nacos-nodeport
  namespace: default
  labels:
    app: nacos-headless
spec:
  type: NodePort
  ports:
    - port: 8848
      name: server
      targetPort: 8848
      nodePort: 30048
    - port: 9848
      name: client-rpc
      targetPort: 9848
      nodePort: 31048
  selector:
    app: nacos
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  namespace: default
  labels:
    app: nacos-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8848
      name: server
      targetPort: 8848
    - port: 9848
      name: client-rpc
      targetPort: 9848
    - port: 9849
      name: raft-grpc
      targetPort: 9849
    - port: 7848
      name: raft-rpc
      targetPort: 7848
  clusterIP: None
  selector:
    app: nacos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
  namespace: default
data:
  db.url: "jdbc:postgresql://ip:port/database"
  db.username: "username"
  db.password: "password"
  db.driver.name: "org.postgresql.Driver"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
  namespace: default
spec:
  serviceName: nacos-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
        - name: nacos
          imagePullPolicy: Always
          image: fuhouyu/nacos-server:2.4.3-postgresql
          env:
            - name: JAVA_OPT
              value: -Dmanagement.endpoints.web.exposure.include=*
            - name: NACOS_REPLICAS
              value: "1"
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: db.url
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: db.username
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: db.password
            - name: DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: db.driver.name
            - name: MODE
              value: "cluster"
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: nacos.naming.data.warmup
              value: "false"
            - name: NACOS_SERVERS
              value: "nacos-0.nacos-headless.default.svc.cluster.local:8848" 
            - name: NACOS_AUTH_TOKEN
              value: NkQzNUUwMjlCOTdGNDk4Mjg2QTJEN0E4RDYzM0EyMzE=
            - name: NACOS_AUTH_IDENTITY_KEY
              value: AE84C5193B6C44728C76AEB73D1A3037
            - name: NACOS_AUTH_IDENTITY_VALUE
              value: D3D2F9F96E58435E802FC34017722057
            - name: SPRING_DATASOURCE_PLATFORM  
              value: "postgresql"
            - name: NACOS_AUTH_ENABLE
              value: "true"
  selector:
    matchLabels:
      app: nacos

```
