### ISSUE TITLE
namespace error

### ISSUE THREAD

**Issue by Lost135** [alibaba/nacos#12910]
**配置文件:**
```
spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: public
```
**nacos 版本: 2.2.3**
```
    java 项目连接nacos ，指定namespace名为public会导致疯狂拉取配置文件。
    如config-pull-check.log日志所显示: gateway.json+DEFAULT_GROUP|10.10.1.1|16c8xxxxxxxxxxx|2024-11-03 17:0:00
    按设计是应该配置为空，缺省值直接找到public保留的命名空间, 或直接只当namespace 的Data ID。

    但是如果意外配置为public，且后端服务比较多的时候，会导致相关方法一直调用，还会引起连锁反应，比如请求mysql连接数过多导致连接失败，jvm异常等，是否应该考虑一下这个情况，最起码进行一个配置验证。
    并且是否验证过还有其他的方法也会因此异常调用，比如服务发现discovery或其他功能。
```
