### ISSUE TITLE
[Nacos 2.5.0]Auth failed Without permission to access public namespace

### ISSUE THREAD

**Issue by BgaSol** [alibaba/nacos#13092]
After logging in, it prompts me with 'Auth failed Without permission to access public namespace!'.
![Image](https://github.com/user-attachments/assets/43432b07-6421-474d-86dc-1f9961b7096a)
![Image](https://github.com/user-attachments/assets/2c2c6ef9-f1aa-4ef7-9ad7-96aab12a658d)

The ROLE_ADMIN has already been automatically created in the database.
![Image](https://github.com/user-attachments/assets/c649c347-113b-419b-a787-900ff9b88edf)

docker compose.yml
```
version: '3'

networks:
  cloud-app:
    driver: bridge

services:
  # Nacos
  cloud-app-nacos:
    image: nacos/nacos-server:v2.5.0
    container_name: cloud-app-nacos
    restart: unless-stopped
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    environment:
      MODE: standalone
      NACOS_SERVER_IP:
      NACOS_APPLICATION_PORT: 8848
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: cloud-app-nacos-mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_USER: ${NACOS_MYSQL_USER}
      MYSQL_SERVICE_PASSWORD: ${NACOS_MYSQL_PASSWORD}
      NACOS_AUTH_ENABLE: true
      NACOS_AUTH_TOKEN: ${NACOS_AUTH_TOKEN}
      # NACOS_AUTH_IDENTITY_KEY: ${NACOS_AUTH_IDENTITY_KEY}
      # NACOS_AUTH_IDENTITY_VALUE: ${NACOS_AUTH_IDENTITY_SECRET}
      NACOS_AUTH_USER_AGENT_AUTH_WHITE_ENABLE: true
    networks:
      - cloud-app
    volumes:
      - ./docker/nacos/logs:/home/nacos/logs
    depends_on:
      - cloud-app-nacos-mysql

  # MySQL 
  cloud-app-nacos-mysql:
    image: mysql:5.7
    container_name: cloud-app-nacos-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SYSTEM_PASSWORD}
      MYSQL_DATABASE: nacos
      MYSQL_USER: ${SYSTEM_USER}
      MYSQL_PASSWORD: ${SYSTEM_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/logs:/var/log/mysql
      - ./config/mysql/initdb:/docker-entrypoint-initdb.d
    networks:
      - cloud-app
    restart: unless-stopped
```
I haven't customized or overridden the default /home/nacos/conf/application.properties in the container.
```
# spring
server.servlet.contextPath=${SERVER_SERVLET_CONTEXTPATH:/nacos}
server.contextPath=/nacos
server.port=${NACOS_APPLICATION_PORT:8848}
server.tomcat.accesslog.max-days=30
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D %{User-Agent}i %{Request-Source}i
server.tomcat.accesslog.enabled=${TOMCAT_ACCESSLOG_ENABLED:false}
server.error.include-message=ALWAYS
# default current work dir
server.tomcat.basedir=file:.
#*************** Config Module Related Configurations ***************#
### Deprecated configuration property, it is recommended to use `spring.sql.init.platform` replaced.
#spring.datasource.platform=${SPRING_DATASOURCE_PLATFORM:}
spring.sql.init.platform=${SPRING_DATASOURCE_PLATFORM:}
nacos.cmdb.dumpTaskInterval=3600
nacos.cmdb.eventTaskInterval=10
nacos.cmdb.labelTaskInterval=300
nacos.cmdb.loadDataAtStart=false
db.num=${MYSQL_DATABASE_NUM:1}
db.url.0=jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT:3306}/${MYSQL_SERVICE_DB_NAME}?${MYSQL_SERVICE_DB_PARAM:characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false}
db.user.0=${MYSQL_SERVICE_USER}
db.password.0=${MYSQL_SERVICE_PASSWORD}
## DB connection pool settings
db.pool.config.connectionTimeout=${DB_POOL_CONNECTION_TIMEOUT:30000}
db.pool.config.validationTimeout=10000
db.pool.config.maximumPoolSize=20
db.pool.config.minimumIdle=2
### The auth system to use, currently only 'nacos' and 'ldap' is supported:
nacos.core.auth.system.type=${NACOS_AUTH_SYSTEM_TYPE:nacos}
### worked when nacos.core.auth.system.type=nacos
### The token expiration in seconds:
nacos.core.auth.plugin.nacos.token.expire.seconds=${NACOS_AUTH_TOKEN_EXPIRE_SECONDS:18000}
### The default token:
nacos.core.auth.plugin.nacos.token.secret.key=${NACOS_AUTH_TOKEN:}
### Turn on/off caching of auth information. By turning on this switch, the update of auth information would have a 15 seconds delay.
nacos.core.auth.caching.enabled=${NACOS_AUTH_CACHE_ENABLE:false}
nacos.core.auth.enable.userAgentAuthWhite=${NACOS_AUTH_USER_AGENT_AUTH_WHITE_ENABLE:false}
nacos.core.auth.server.identity.key=${NACOS_AUTH_IDENTITY_KEY:}
nacos.core.auth.server.identity.value=${NACOS_AUTH_IDENTITY_VALUE:}
## spring security config
### turn off security
nacos.security.ignore.urls=${NACOS_SECURITY_IGNORE_URLS:/,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**}
# metrics for elastic search
management.metrics.export.elastic.enabled=false
management.metrics.export.influx.enabled=false
nacos.naming.distro.taskDispatchThreadCount=10
nacos.naming.distro.taskDispatchPeriod=200
nacos.naming.distro.batchSyncKeyCount=1000
nacos.naming.distro.initDataRatio=0.9
nacos.naming.distro.syncRetryDelay=5000
nacos.naming.data.warmup=true
nacos.console.ui.enabled=true
nacos.core.param.check.enabled=true
```
System environment:
 - Docker Compose
 - nacos-server-2.5.0
 - mysql-5.7

After rolling back the nacos-server version to 2.4.3, the issue disappeared.
