### ISSUE TITLE
请问一个项目中既有yaml配置，又有json格式配置文件，如何同时读取不同格式的配置文件

### ISSUE THREAD

**Issue by thinkcodee** [alibaba/nacos#13097]
我的想象中一些配置放到json格式的配置文件中，但是不清楚如何读取，
其中`bootstrap.yml`配置如下
```yaml

# Tomcat
server:
  port: 32021

# Spring
spring:
  application:
    # 应用名称
    name: msp-demo
  profiles:
    # 环境配置
    active: dev
  cloud:
    nacos:
      server-addr: 192.168.1.10:8848
      username: nacos
      password: nacos
      discovery:
        watch:
          enabled: true
        watch-delay: 1000
      config:
        # 指定命名空间
        namespace: msp-demo
        # 开启注册中心
        enabled: true
        # 开启监听和自动刷新
        refresh-enabled: true
        # 配置文件格式
        file-extension: yaml
        # 其他配置
        shared-configs:
          # 数据源配置
          - user.json
          - org.json
          - role.json
          - menu.json
          - user-role.json
          - user-org.json
```

user.json配置是一个json数据，在nacos配置
```json
[ {
        "id": "263764ed-fcf2-46d0-ac07-4ede5a11a024",
        "name": "abc",
        "loginName": "abc",
        "gender": 1
   }, {
        "id": "9743828b-fcf5-46d0-ac02-4ede5a11a028",
        "name": "test",
        "loginName": "test",
        "gender": 1  
    }
]
```

我怎么读取这个user.json配置啊？
