### ISSUE TITLE
nacos docker集群模式部署，程序无法连接

### ISSUE THREAD

**Issue by pptfz** [alibaba/nacos#13121]
使用官方示例文件启动
```
version: "3.8"
services:
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:v2.5.0
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs
    ports:
      - "7848:7848"
      - "8848:8848"
      - "9868:9848"
      - "9850:9849"
    env_file:
      - ../env/nacos-hostname.env
    restart: always

  nacos2:
    hostname: nacos2
    image: nacos/nacos-server:v2.5.0
    container_name: nacos2
    volumes:
      - ./cluster-logs/nacos2:/home/nacos/logs
    ports:
      - "7849:7848"
      - "8849:8848"
      - "9869:9848"
      - "9851:9849"
    env_file:
      - ../env/nacos-hostname.env
    restart: always

  nacos3:
    hostname: nacos3
    image: nacos/nacos-server:v2.5.0
    container_name: nacos3
    volumes:
      - ./cluster-logs/nacos3:/home/nacos/logs
    ports:
      - "7850:7848"
      - "8850:8848"
      - "9870:9848"
      - "9852:9849"
    env_file:
      - ../env/nacos-hostname.env
    restart: always
```

`../env/nacos-hostname.env` 文件内容
```
PREFER_HOST_MODE=hostname
NACOS_SERVERS=nacos1:8848 nacos2:8848 nacos3:8848
SPRING_DATASOURCE_PLATFORM=mysql
MYSQL_SERVICE_HOST=xxx
MYSQL_SERVICE_DB_NAME=nacos
MYSQL_SERVICE_PORT=3306
MYSQL_SERVICE_USER=xxx
MYSQL_SERVICE_PASSWORD=xxx
MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
#NACOS_AUTH_IDENTITY_KEY=nacos-test
#NACOS_AUTH_IDENTITY_VALUE=xxx
#NACOS_AUTH_TOKEN=xxx
```

容器启动成功
```
docker ps -a
CONTAINER ID   IMAGE                                       COMMAND                  CREATED          STATUS          PORTS                                                                                            NAMES
fa3b6e754a1a   nacos-server:v2.5.0   "sh bin/docker-start…"   14 minutes ago   Up 14 minutes   0.0.0.0:7849->7848/tcp, 0.0.0.0:8849->8848/tcp, 0.0.0.0:9869->9848/tcp, 0.0.0.0:9851->9849/tcp   nacos2
a2dfd696ed47   nacos-server:v2.5.0   "sh bin/docker-start…"   14 minutes ago   Up 14 minutes   0.0.0.0:7848->7848/tcp, 0.0.0.0:8848->8848/tcp, 0.0.0.0:9868->9848/tcp, 0.0.0.0:9850->9849/tcp   nacos1
0b607a3c3cd3   nacos-server:v2.5.0   "sh bin/docker-start…"   14 minutes ago   Up 14 minutes   0.0.0.0:7850->7848/tcp, 0.0.0.0:8850->8848/tcp, 0.0.0.0:9870->9848/tcp, 0.0.0.0:9852->9849/tcp   nacos3
```

每个容器的日志输出如下
```
2025-02-19 11:04:53,828 INFO Nacos is starting...

2025-02-19 11:04:54,858 INFO Nacos is starting...

2025-02-19 11:04:55,886 INFO Nacos is starting...

2025-02-19 11:04:56,892 INFO Nacos is starting...

2025-02-19 11:04:57,895 INFO Nacos is starting...

2025-02-19 11:04:58,904 INFO Nacos is starting...

2025-02-19 11:04:59,906 INFO Nacos is starting...

2025-02-19 11:05:00,636 INFO Nacos started successfully in cluster mode. use external storage
```

程序报错如下

![Image](https://github.com/user-attachments/assets/73beb88b-224b-4651-a8c9-f2700a9554c7)

有解决方法么？
