### ISSUE TITLE
Does zipkin not support?

### ISSUE THREAD

**Issue by mgw1986** [alibaba/nacos#1392]
尝试了所有Issues中关于zipkin的方法,`failed to update serviceName: DEFAULT_GROUP@@x.x.x.x`,这个错误都没有解决。
确认下是否现在版本不支持zipkin?
目前使用的环境：
nacos-1.0.0
spring-cloud Finchley.SR1

**Comment by chuntaojun** [comment]
支持的呀，我目前的项目中已经使用了zipkin+spring-cloud-alibaba+nacos，正常运行

**Comment by mgw1986** [comment]
我的问题和#1300是一样的，你没有碰到这个问题？

**Comment by mgw1986** [comment]
我的问题[#1300](https://github.com/alibaba/nacos/issues/1300)是一样的，你没有碰到这个问题吗？
启动不会报错，只要一请求，控制台就一直报错！

**Comment by chuntaojun** [comment]
启动当然不会报错，你的zipkin设置是什么样的？zipkin与spring-cloud的继承中，存在spring-seluth自动已服务名的形式调用zipkin-server

**Comment by mgw1986** [comment]
我的配置参数如下：`discovery-client-enabled: false`是参考之前Issues的回答加的，没有作用！
pom.xml 依赖
`
 <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-zipkin</artifactId>
 </dependency>
`
`
zipkin:
    base-url: http://192.168.2.6:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
    trace-id128: true
`

**Comment by mgw1986** [comment]
`xml
 <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-zipkin</artifactId>
</dependency>
`

**Comment by mgw1986** [comment]
我的配置参数如下：`discovery-client-enabled: false`是参考Issues加的，没什么用！
pom.xml
``` xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-sleuth-zipkin</artifactId>
</dependency>
```
application.yml
``` yaml
spring:
  application:
    name: nacos-discovery-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.6:8848
  zipkin:
    base-url: http://192.168.2.6:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
    trace-id128: true
```
