### ISSUE TITLE
Support init mysql tables and data when nacos start up?

### ISSUE THREAD

**Issue by zhanjiejun** [alibaba/nacos#1460]
Can nacos support execute schema.sql automatically when nacos start up?
Just like spring-boot-jdbc :
```yaml
spring:
  datasource:
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always
    continue-on-error: true
    sql-script-encoding: UTF-8
```
