### ISSUE TITLE
nacos-1.1.0 beat interval

### ISSUE THREAD

**Issue by levin950825** [alibaba/nacos#1567]
```
nacos-client 1.1.0  metadata 的 preserved.heart.beat.interval  
it's without effect

spring:
  application:
    name: supply-chain-baseinfo
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.13:7777
        metadata:
          preserved:
            ip:
              delete:
                timeout: 180
            heart:
              beat:
                interval: 30
                timeout: 120
```

```
2019-07-18 15:55:02.689  INFO 16032 --- [.naming.updater] com.alibaba.nacos.client.naming          : current ips:(1) service: DEFAULT_GROUP@@supply-chain-baseinfo -> [{"clusterName":"DEFAULT","enabled":true,"ephemeral":true,"healthy":true,"instanceHeartBeatInterval":30,"instanceHeartBeatTimeOut":120,"instanceId":"192.168.1.41#8001#DEFAULT#DEFAULT_GROUP@@supply-chain-baseinfo","ip":"192.168.1.41","ipDeleteTimeout":180,"metadata":{"preserved.heart.beat.timeout":"120","preserved.ip.delete.timeout":"180","preserved.register.source":"SPRING_CLOUD","preserved.heart.beat.interval":"30"},"port":8001,"serviceName":"DEFAULT_GROUP@@supply-chain-baseinfo","weight":1.0}]
2019-07-18 15:55:12.695  INFO 16032 --- [.naming.updater] com.alibaba.nacos.client.naming          : current ips:(1) service: DEFAULT_GROUP@@supply-chain-baseinfo -> [{"clusterName":"DEFAULT","enabled":true,"ephemeral":true,"healthy":true,"instanceHeartBeatInterval":30,"instanceHeartBeatTimeOut":120,"instanceId":"192.168.1.41#8001#DEFAULT#DEFAULT_GROUP@@supply-chain-baseinfo","ip":"192.168.1.41","ipDeleteTimeout":180,"metadata":{"preserved.heart.beat.timeout":"120","preserved.ip.delete.timeout":"180","preserved.register.source":"SPRING_CLOUD","preserved.heart.beat.interval":"30"},"port":8001,"serviceName":"DEFAULT_GROUP@@supply-chain-baseinfo","weight":1.0}]
```
