### ISSUE TITLE
multi env profile question

### ISSUE THREAD

**Issue by kaybinwong** [alibaba/nacos#1577]
## Issue Description
i created 3 namespaces(dev, test, prod),
then create a dataId serviceA.yaml in the public namespace, 
serviceA-test.yaml in the test namespace. 
**but it seem nerver load the dataId under public namespace with active profile test.**

![image](https://user-images.githubusercontent.com/5570216/61576004-7013a580-ab06-11e9-9289-6a70cc43cd56.png)

```
spring:
  application:
    name: serviceA
  cloud:
    nacos:
      config:
        file-extension: yaml
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.namespace}
        shared-dataids: actuator.yaml,log.yaml,mail.yaml
        refreshable-dataids: actuator.yaml,log.yaml,mail.yaml
      discovery:
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.namespace}
```

### Tell us your environment
version 1.0.0

### Anything else we need to know?
something i had done wrongly? 
thx in advanced.
