### ISSUE TITLE
Nacos configuration center， The specified environment does not take effect

### ISSUE THREAD

**Issue by zhangsongyang** [alibaba/nacos#1757]
**bootstrap.yaml**

```
spring:
  profiles:
    active: check
  application:
    name: thremos-provider
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        ext-config[0]:
          data-id: application.yaml
          group: xxx_GROUP
          refresh: true
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 127.0.0.1:8848
```

**application.yaml**
```
dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.thermos
  protocols:
    dubbo:
      # dubbo 协议
      name: dubbo
      # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
      port: -1
  cloud:
    subscribed-services: ${provider.application.name}

provider:
  application:
    name: thermos-server-provider

feign:
  hystrix:
    enabled: true

server:
  port: 8087
  servlet:
    context-path: /thermos

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profiles: prod

  datasource:
    druid:
      web-stat-filter:
        enabled: true
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,*.htm,*.html,/druid/*"
      stat-view-servlet:
        enabled: true
        login-username: 123
        login-password: 123
        allow:
      aop-patterns: com.thermos.*
      xxxx:
        # 连接池的配置信息
        url: jdbc:mysql://xxxxxxxxxx?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: xxx
        password: xxxxx
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        max-active: 20
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
      ccc:
        url: jdbc:mysql://xxxxxx/xxx?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: xxxx
        password: xxxxxxxx
        driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    sentinel:
      transport:
        dashboard: localhost:8085
      datasource:
        ds:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: sentinel-flow-rules
            groupId: THRMOS_GROUP
            rule-type: flow
    stream:
      bindings:
        output1:
          destination: UPLUS_SERVER_TOPIC
          content-type: application/json
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          output1:
            producer:
              group: PRODUCER

com:
  # redis 配置begin
  redisHosts:
    - xxxx:222
    - xxxxx:2222
  redisMasters:
    - xxx
    - xxx
  redisPassword: sssssss
  redisMaxTotal: 200
  redisDatabase: 1
  redisMinIdle: 8
  redisMaxIdle: 40
  redisMaxWait: 10000
  redisTimeout: 5000
  # redis 配置end

---
spring:
  profiles: check

  # 验收环境
  datasource:
    druid:
      web-stat-filter:
        enabled: true
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,*.htm,*.html,/druid/*"
      stat-view-servlet:
        enabled: true
        login-username: xxx
        login-password: xxx
        allow:
      aop-patterns: com.*
      xxxx:
        # 连接池的配置信息
        url: jdbc:mysql://xxxxx:3306/xxx?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: xxxx
        password: xxxxx
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        max-active: 20
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
      ccc:
        url: jdbc:mysql://xxxxxxxxxx?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: xxx
        password: xxxxx
        driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    sentinel:
      transport:
        dashboard: localhost:8085
      datasource:
        ds:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: sentinel-flow-rules
            groupId: xxx_GROUP
            rule-type: flow
    stream:
      bindings:
        output1:
          destination: xxxxxTOPIC
          content-type: application/json
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          output1:
            producer:
              group: xxxxx_PRODUCER

dubbo:
  metadata-report:
    address: nacos://127.0.0.1:8848
    group: xxxxxx_GROUP

com:
  # redis 配置begin
  redisHosts:
    - xxxxxx:4200
    - xxxxxx:4200
  redisMasters:
    - xx
    - xxx
  redisPassword: xxxxxxx
  redisMaxTotal: 200
  redisDatabase: 1
  redisMinIdle: 8
  redisMaxIdle: 40
  redisMaxWait: 10000
  redisTimeout: 5000
  # redis 配置end

```

定义了prod和check2个环境，在bootstrap.yaml中指定不同环境idea中正常，但是把application.yaml放到nacos的配置中心，只有最下面的环境生效，不按照指定的环境来。

Defined the environment of prod and check, specify different environments in bootstrap.yaml, start the project idea normal, but put application.yaml in the configuration center of nacos, only the lowest environment is effective, not according to the specified environment.
