### ISSUE TITLE
Leader and follower's service list is inconsistent

### ISSUE THREAD

**Issue by VolcanoOves** [alibaba/nacos#1852]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)

In the test environment, a cluster of three nodes was set up. The IP suffixes were 104/105/106 and 104 were the leaders. The service could be registered to three nodes normally. After two weeks of normal use, it was found that 106 nodes could not be registered normally.
```
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 88.88.16.104:8848,88.88.16.105:8848,88.88.16.106:8848
        namespace: 755f3570-7223-47bd-860b-693b23066014
```
As configured above, only the 104/105 node has a list of services, and 106 does not have any services, resulting in a chance that the call will not be called successfully.

```
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 88.88.16.106:8848
        namespace: 755f3570-7223-47bd-860b-693b23066014
```

The service is only registered to 106, and the 106 node still shows no service registration. Interestingly, the 104 and 105 nodes are already registered.

在测试环境搭建了三个节点的集群，IP后缀分别是104/105/106，最开始104位领导者，服务能够正常注册到三个节点，正常使用了两周之后，发现106节点无法正常注册。
```
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 88.88.16.104:8848,88.88.16.105:8848,88.88.16.106:8848
        namespace: 755f3570-7223-47bd-860b-693b23066014
```
如上配置，只有104/105节点有服务列表，而106没有任何服务，导致调用的过程中有几率出现无法正常调用成功。

改成如下配置后
```
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 88.88.16.106:8848
        namespace: 755f3570-7223-47bd-860b-693b23066014
```
将服务只注册到106上，106节点还是还是展示无服务注册，有趣的是，104与105节点展示的已经注册上。

### Describe what you expected to happen

Normally able to register on all nodes, even if there is a time delay between the nodes, but should not be like this, can not be registered to a node.

正常能够注册到所有节点之上，就算节点之间展示有时间延迟，但是不应该像这样，一直无法注册到某个节点。

### How to reproduce it (as minimally and precisely as possible)

I am deploying according to the official documentation, I don't know how to reproduce the bug.
But 106 nodes have some error logs as follows：
2019-09-16 10:17:31,284 INFO receive config info: unknown#88.88.16.104:8848#1568600286691#2

2019-09-16 10:17:39,113 INFO receive config info: unknown#88.88.16.105:8848#1568600293082#2

2019-09-16 10:17:40,072 INFO receive config info: unknown#88.88.16.106:8848#1568600260072#2

### Tell us your environment

java 1.8
centos 7.3
mysql
spring-cloudali-baba2.1.0.RELEASE

### Anything else we need to know?

我认为106节点与其他节点是能够正常通讯的，因为住将服务只注册到106之上，虽然106无法正常展示并提供使用，但是105/104节点却能够正常的展示与提供使用。我希望能够得到帮助。
