### ISSUE TITLE
nacos不能使用ribbon的listOfServers

### ISSUE THREAD

**Issue by JunRzz** [alibaba/nacos#2047]
我看了下NacosServerList中的getServers方法，是直接从nacos读取的配置，直接忽略了我在配置中设置的：
```
service-cloud-xxx:
  ribbon:
    listOfServers: localhost:8080
    ServerListRefreshInterval: 15000
```
这样对本地调试非常不友好啊
