### ISSUE TITLE
nacos 修改配置不生效

### ISSUE THREAD

**Issue by yqbboy** [alibaba/nacos#2071]
#1552  Issue Description

### Describe what happened (or what feature you want)
使用nacos 1.1.4 docker mysql 单机版部署，总共遇到两个问题
1、修改配置后，配置不能及时生效，必须手动重启nacos(该问题每次都能复现)
2、当增加dataID 大于11条时，再次增加第12个配置时，新增的dataID 不能在列表上显示

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
docker-compose -f example/standalone-mysql.yaml up

### Anything else we need to know?
docker compose
```
nacos:
    image: '10.30.161.199:5000/nacos/nacos-server:1.1.4'
    container_name: nacos-standalone
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_MASTER_SERVICE_HOST=mysql
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos-config
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_MASTER_SERVICE_USER=root
      - MYSQL_MASTER_SERVICE_PASSWORD=tKWH0FQGZmNjgQRyNq9stDS0IXDtxXmx
      - MYSQL_DATABASE_NUM=1
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: on-failure
    deploy:
      placement:
        constraints: [node.labels.nacos==true]
```
