### ISSUE TITLE
@NacosConfigurationProperties cannot bind yaml to javabean

### ISSUE THREAD

**Issue by gxw19874** [alibaba/nacos#2224]
## Issue Description

Type: *bug report*

@NacosConfigurationProperties cannot bind yaml to javabean

####  My javabean like that:
```

@ConfigurationProperties(prefix = "ebtce.services")
@Configuration
@Data
public class ServicesYaml {
    private String crm ;
    private String app ;
    private Mileage mileage;
}

@Configuration
@Data
public class Mileage {
	private String url;
	private String min;
	private String system;
	private String office;
	private String agent;
}
```

#### My yaml like that:
```
ebtce:
    services:
        crm: 161121
        app: 21212
        mileage:
            url: http://ebtce-service-open/crm_interface
            min: 100
            system: 1111
            office: 111
            agent: 90666
```

the variable crm can bind “161121” and  app can bind “21212”，but mileage is null.

### Describe what you expected to happen

I expected  the variable mileage can bind the yaml .

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
```
        <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.1</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-api</artifactId>
            <version>1.1.0</version>
            <scope>compile</scope>
        </dependency>
````
