### ISSUE TITLE
nacos 权限认证

### ISSUE THREAD

**Issue by 1556837534** [alibaba/nacos#2499]
## Issue Description
<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Fri Mar 20 14:10:12 CST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
nacos 在application.yaml 文件中配置了 对应的用户与密码 服务可以注册进去，但是提示获取dataId 报403错误 无法获取到对应的 配置文件信息

### Describe what you expected to happen
日志信息
[fixed-127.0.0.1_8848-dev] [check-update] get changed dataId error, code: 403

**Comment by chuntaojun** [comment]
发一下你的cloud配置

**Comment by 1556837534** [comment]
```
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.128:8848  #服务注册地址
        group: DEV_GROUP
        namespace: b84cbc16-bfb4-4912-a89c-bb66ffb8603a
      config:
        server-addr: 192.168.1.128:8848  #服务注册中心地址
        file-extension: yaml #指定文件格式
        group: DEV_GROUP
        namespace: b84cbc16-bfb4-4912-a89c-bb66ffb8603a
    sentinel:
      transport:
        # 配置Sentinel dashboard 地址
        dashboard: 192.168.1.128:8988
        # 默认8719 假如被占用会依次+1 扫描可用端口
        port: 8719
      eager: true
```
1. SpringCloud版本是 Hoxton.SR1
2. spring-cloud-alibaba 版本是2.1.0.RELEASE
3. 因为之前强制替换升级nacos，可以配置用户密码
