### ISSUE TITLE
nacos开启认证之后，服务就无法注册了

### ISSUE THREAD

**Issue by wenming5112** [alibaba/nacos#2549]
# 我的配置是这样的
```yaml
spring:
  cloud:
    nacos:
      discovery:
        # username: nacos
        # password: nacos
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        prefix: fabric-nacos-discovery
```
开启nacos认证之后，服务就无法注册了,以上注释掉的那种方式去设置用户名和密码貌似也没有用。
但是nacos控制台能正常登录进去。
> <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Sun Mar 29 23:58:38 CST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
