### ISSUE TITLE
在被rancher管理的k8s集群中,服务无法访问?

### ISSUE THREAD

**Issue by superlyao** [alibaba/nacos#2559]
注册中心和服务都是部署在k8s同一个命名空间下,通过网关访问的时候找不到服务地址,报错如下
```
{"timestamp":"2020-03-31T11:02:43.758+0000","status":404,"error":"Not Found","message":"No message available","path":"/*.query"}
```
> 地址是处理过了的

但是在eureka做为注册中心的时候是可以正常访问的,暂时怀疑是配置了`prefer-ip-address: true`这个参数

>以eureka为注册中心的相关配置

```yml
eureka:
  instance:
    prefer-ip-address: true ## 以ip的形式去注册
  client:
    service-url:
      defaultZone: http://eureka.dev:8080/eureka/
```

> 以nacos为注册中心的相关配置
```yml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos.dev
```

我看下了一下nacos中的配置`spring.cloud.nacos.discovery.ip`这个参数,虽然是可以填写ip,但是在k8s中pod每次可能是部署在不同的机器上的,这个也不能满足需求,想问下有类似eureka这种自动解析ip注册吗?
