### ISSUE TITLE
nacos中的MD5和服务收到的MD5不一致，导致日志不断打印

### ISSUE THREAD

**Issue by caohongliang92** [alibaba/nacos#2722]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
nacos中的MD5和服务收到的MD5不一致，导致日志不断打印

### How to reproduce it (as minimally and precisely as possible)

1. 在nacos中配置 gateway.yaml 配置
```yaml
gateway:
  api:
    security:
      request:
        sign: false
      response:
        sign: true
```
2. 发布之后，可以看到对应的服务中不断打印出日志：
日志打印的MD5为：07e0cc99f8dde57e7f013d5d544d88a0
![image](https://user-images.githubusercontent.com/48972121/80793468-c8192580-8bc9-11ea-804d-1c52f17c3b60.png)
![image](https://user-images.githubusercontent.com/48972121/80793486-d36c5100-8bc9-11ea-92b9-343940b3d9dd.png)

3. 查看nacos中的配置的MD5：7e0cc99f8dde57e7f013d5d544d88a0
![image](https://user-images.githubusercontent.com/48972121/80793559-0b739400-8bca-11ea-89f2-c9001e396f15.png)

4. 对比两个MD5，发现nacos中的MD5比服务收到的MD5前面少了个0
5. 尝试将配置文件中相关值修改为其他值，不会不断打印日志
