### ISSUE TITLE
spring cloud gateway Unable to find instance for [my-service]

### ISSUE THREAD

**Issue by NineSwordsMonster** [alibaba/nacos#2876]
## Issue Description

bug report

使用spring cloud gateway 整合，访问链接
返回
>  "path": "/x/xx/xxx",
    "status": 503,
    "error": "Service Unavailable",
    "message": "Unable to find instance for my-service",
>

### Describe what happened (or what feature you want)
无法查到已注册服务

### Describe what you expected to happen
正常路由到注册的服务

### How to reproduce it (as minimally and precisely as possible)

1.  注册服务
2.  使用gateway 路由
3.  访问

### Tell us your environment
```xml
<spring-cloud-alibaba.version>2.2.1.RELEASE</spring-cloud-alibaba.version>
<spring-cloud.version>Hoxton.SR4</spring-cloud.version>
<dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
```

### Anything else we need to know?
服务配置 
```yaml
# common config
spring:
  cloud:
    # nacosdiscovery config
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: dev
        password: dev

        namespace: e8a87655-33f5-4c7a-a575-baf37ad30530
        group: dev
        service: my-service
```
gateway 配置

```yaml
spring:
  # common config
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
```

动态监听nacos 配置 加载路由

```yaml
    - id: my-service
      uri: lb://my-service
      predicates:
        - name: Path
          args: 
            pattern: /x/xx/xxx/user/**
      filters:
        - name: StripPrefix
          args: 
            _genkey_0: 3
```

![image](https://user-images.githubusercontent.com/10054584/82759416-e9afaa80-9e1f-11ea-9c03-325ab99bd18b.png)
