### ISSUE TITLE
Nacos上某个配置文件内引用naocs上其他配置文件的问题

### ISSUE THREAD

**Issue by AllenPKX** [alibaba/nacos#2930]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

nacos上在一个配置文件中引用nacos上另一配置文件，该怎么写

>首先 未使用nacos之前配置文件是这样写的
application-dev.yml
```
 redisson:
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: 8
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 8
        # 最小空闲连接数（默认为0，该值只有为正数才有作用）
        min-idle: 0
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: -1
      config: classpath:redisson-dev.yml
```
使用nacos时，ps:redisson-dev.yaml 这个也上传到nacos了.
此时我的bootsrtap.yml是这么写的：
```
config:
        server-addr: 127.0.0.1:8848
        extension-configs[1]:
          data-id: application-dev.yaml
          group: DEFAULT_GROUP
          refresh: true
        extension-configs[0]:
          data-id: redisson-dev.yaml
          group: DEFAULT_GROUP
          refresh: true
```
此时我的application-dev.yaml 这一段该怎么写呢?
下面这个是nacos上的application-dev.yaml
```
redisson:
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: 8
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 8
        # 最小空闲连接数（默认为0，该值只有为正数才有作用）
        min-idle: 0
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: -1
      config:  
```
这个config这个该怎么写呢？

> [](url)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.
