### ISSUE TITLE
nacos dashboard 权限管理新增user namespace 后登陆403

### ISSUE THREAD

**Issue by Starbucksstar** [alibaba/nacos#2945]
## Issue Description
nacos 1.2.1和1.3.0-beta版本 dashboard新增用户，分配读写权限后，分配新namespace，新用户登陆报403，authorization failed!

### Describe what you expected to happen
新用户登陆后dashboard只显示分配的namespace配置和服务，不弹出authorization failed!

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
nacos1.2.1/nacos1.3.0-Beta
mac 本地standlone模式
本地mysql--使用nacos-mysql.sql初始化

**Comment by chuntaojun** [comment]
应该是在public的命名空间在显示的吧？可以直接点击对应的命名空间，前端显示问题我们会优化下的

**Comment by EasonFeng5870** [comment]
@i will solve it@

**Comment by Force-King** [comment]
nacos1.3.0-Beta，开启了nacos.core.auth.enabled=true，和nacos.core.cacheing.enabled=true 两个配置。 项目启动连不上nacos了,报错如下：
`com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Mon Jun 22 11:29:27 CST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>`

application.yml 配置如下：
```
spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos.com
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
      config:
        group: DEFAULT_GROUP
        file-extension: properties
        username: nacos
        password: nacos
        contextPath: /nacos
```
