### ISSUE TITLE
nacos1.2.1搞了个docker集群，没有用户名密码也能服务注册跟读取配置，为什么？

### ISSUE THREAD

**Issue by huajiawen** [alibaba/nacos#2974]
nacos1.2.1我单机模式，服务注册跟配置读取，用户名密码错误是不行的
搞了个docker集群，没有用户名密码也能服务注册跟读取配置，乱输入的用户名和密码也能。
**nacos.core.auth.enabled=true** 也配置了
控制台需要正确的用户名和密码才能登录，是正常的
nacos-client版本也是1.2.1
有经验的朋友，请提示下。。。

集群拉取：**docker pull nacos/nacos-server:1.2.1**
集群数库据是直接用单机模式时候建好的数据库
集群通过docker-compose编排，三个集群，基本如下：
```
version: "3"
services:
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:1.2.1
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs
      - ./conf/application.properties:/home/nacos/conf/application.properties
      - ./conf/cluster.conf:/home/nacos/conf/cluster.conf:ro
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    environment: 
      PREFER_HOST_MODE: hostname      
    restart: always
```
