### ISSUE TITLE
自定义namespace在配置中不生效 

### ISSUE THREAD

**Issue by Force-King** [alibaba/nacos#3029]
自定义了命名空间 DEV ， TEST , 但是使用DEV环境启动项目后依然是从 public 下获取配置文件。
修改 public 下的 对应dataid 配置文件，可以动态生效。修改 DEV 下配置，无效。
使用jar :
```
<dependency>
         <groupId>com.alibaba.cloud</groupId>
         <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
         <version>2.1.0.RELEASE</version>
</dependency>
```

**Comment by chuntaojun** [comment]
你需要输入的命名空间是命名空间的ID信息，以及贴一下你的spring-cloud的配置

**Comment by Force-King** [comment]
我用的就是命名空间ID,配置如下：
bootstrap.properties
```
spring.cloud.nacos.config.server-addr=nacos.com
spring.application.name=demoApp
```
application.yml
```
spring:
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: nacos.com
        group: DEFAULT_GROUP
      config:
        group: DEFAULT_GROUP
        file-extension: properties
```
开发环境配置：
application-dev.properties
```
spring.cloud.nacos.discovery.namespace=8b4cd4e4-**************-c724d80b
spring.cloud.nacos.config.namespace=8b4cd4e4-***********8888-c72480b
```
测试环境：
application-test.properties
```
spring.cloud.nacos.discovery.namespace=a80359c6-2***********-f0bdd52ae7d6
spring.cloud.nacos.config.namespace=a80359c6-2************-f0bdd52ae7d6
```
配置如上，但是无论 dev 还是 test 环境启动项目， 修改dev 和 test 命名空间下的 dataid 对应配置，都不生效，我试了，public 下对应的配置 却可以生效，感觉还是获取的默认命名空间。
