### ISSUE TITLE
启动微服务后nacos要10-30秒才识别到, 要怎么马上识别到?

### ISSUE THREAD

**Issue by gclsoft** [alibaba/nacos#3225]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 微服务开发中,经常代码改了不生效,就要重启, 重启完又要等很久才能让nacos识别到,想加快这个速度
2. 
3.

**Comment by KomachiSion** [comment]
我一注册就能看到。不知道你的环境信息，没法判断问题。一般等这么久才识别到是不正常的。还是提供更多相关信息看下吧

**Comment by gclsoft** [comment]
其实就是7到15秒之内,微服务启动后,才在nacos里的服务列表里显示. 您那边是启动完spring boot后直接nacos一秒内就识别到吗? @KomachiSion

**Comment by fisherwangcn** [comment]
服务启动是不是还没完事呢，你要看到 application started ... 才能算成功

**Comment by gclsoft** [comment]
是的,是看到application started才开始算的,要过10秒才会被nacos认到.
nacos-server版本是-1.2.1
nacos yaml配置是:
```
#服务器配置
server:
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 16
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 400
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

#spring配置
spring:
  cloud:
    sentinel:
      eager: true
  devtools:
    restart:
      log-condition-evaluation-delta: false
    livereload:
      port: 23333

#feign配置
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false

#hystrix配置
hystrix:
  threadpool:
    default:
      coreSize: 300
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 65000

#ribbon配置
ribbon:
  #对当前实例的重试次数
  MaxAutoRetries: 1
  #切换实例的重试次数
  MaxAutoRetriesNextServer: 2
  #请求处理的超时时间
  ReadTimeout: 60000
  #请求连接的超时时间
  ConnectTimeout: 60000
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true

#对外暴露端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#blade配置
blade:
  xss:
    enabled: true
    skip-url:
      - /notice/submit
  secure:
    skip-url:
      - /test/**
      
    client:
      - client-id: sword
        path-patterns:
          - /sword/**
      - client-id: saber
        path-patterns:
          - /saber/**
  tenant:
    enhance: true
    column: org_id
    exclude-tables:
      - t_sys_user
```
