### ISSUE TITLE
bug: Application failed to connect to Nacos server: ""

### ISSUE THREAD

**Issue by geektcp** [alibaba/nacos#3395]
## Issue Description
```
Connected to the target VM, address: '127.0.0.1:51867', transport: 'socket'
2020-07-20 21:41:54.696  INFO 8684 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@2663e964: startup date [Mon Jul 20 21:41:54 CST 2020]; root of context hierarchy
2020-07-20 21:41:55.349  INFO 8684 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$29a47a3e] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.4.RELEASE)

2020-07-20 21:41:56.858 ERROR 8684 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Application failed to connect to Nacos server: ""

Action:

Please check your Nacos server config

Disconnected from the target VM, address: '127.0.0.1:51867', transport: 'socket'

Process finished with exit code 1
```

### Describe what happened (or what feature you want)
application.yml:
```
server:
  port: 9000
  context-path: /api

spring:
  application:
    name: example
  cloud:
    nacos:
      config:
        enabled: false
        server-addr: 127.0.0.1:8848
```

maven:
```
 <properties>
        <compiler.version>1.8</compiler.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <spring-cloud.version>1.5.1.RELEASE</spring-cloud.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>1.5.1.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>1.5.1.RELEASE</version>
        </dependency>
    </dependencies>
```
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
win7
idea IDE
jdk1.8
nacos-server-1.3.1

### Anything else we need to know?
Can not startup this application!

**Comment by KomachiSion** [comment]
`enabled: false`?

**Comment by geektcp** [comment]
use bootstrap.yml ,but not application.yml
```
server:
  port: 9000
  context-path: /api

spring:
  application:
    name: example
  cloud:
    nacos:
      config:
        enabled: false
        server-addr: 127.0.0.1:8848
```
