### ISSUE TITLE
When the mysql configuration information is in yaml format, spring boot does not work properly

### ISSUE THREAD

**Issue by liuzhenyulive** [alibaba/nacos#3753]
**Describe the bug**
When the mysql configuration information is in yaml format, spring boot does not work properly，while it can work normally when using Properties format

**Expected behavior**
It should work fine regardless of the format.

**How to Reproduce**
1.Use yaml format to configure mysql connection information
![image](https://user-images.githubusercontent.com/23184470/92140555-d7dc9b00-ee43-11ea-91ec-fa9222aedd20.png)
spring boot will throw exception.
![image](https://user-images.githubusercontent.com/23184470/92140637-f347a600-ee43-11ea-84d8-6d694bb496a3.png)
2. Use Properties format to configure it.
![image](https://user-images.githubusercontent.com/23184470/92140769-1eca9080-ee44-11ea-9faf-6944cdade898.png)
it will work normally.
![image](https://user-images.githubusercontent.com/23184470/92140877-4588c700-ee44-11ea-8020-1426717864f9.png)

**Desktop (please complete the following information):**
 - Server-OS: Centos7 docker env
 - Client-OS: Win10
 - Version: nacos/nacos-server:latest
 - SDK: nacos-config-spring-boot-starter:0.2.7

**Comment by neighbor-uncleWang** [comment]
Hi, can I help you @KomachiSion

**Comment by liuzhenyulive** [comment]
Thanks @neighbor-uncleWang @KomachiSion 
This problem is solved by specifying the type to `yaml` in application.yaml

``` yaml
nacos:
  config:
    server-addr: ****:8848
    namespace: ****
    group: DEFAULT_GROUP
    auto-refresh: true
    data-id: ****
    bootstrap:
      enable: true
      log-enable: true
    max-retry: 10
    type: yaml
```
I suggest to declare this in the official documentation.  
https://nacos.io/zh-cn/docs/quick-start-spring-boot.html
