### ISSUE TITLE
k8s部署重启服务器后会导致管理页面访问不了，直接报错

### ISSUE THREAD

**Issue by zxiaozhou** [alibaba/nacos#3869]
**Describe the bug**
k8s部署重启服务器后会导致访问管理页面报错，只有启动号k8s后重新部署一次才正常

**How to Reproduce**
1. k8s部署(使用下面Deployment文件或直接用nacos-quick-start.yaml)
2. 部署后访问管理页面正常
3. 重启主机，等待k8s重启完成
4. 再次访问nacos管理页面报错，无法访问。

**Desktop (please complete the following information):**
 - OS: [e.g. Centos] centos7
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1] 1.3.2
 - Module [e.g. naming/config]

**Additional context**
1. 重启主机后访问浏览器截图：
![image](https://user-images.githubusercontent.com/62740686/93660312-041d2c00-fa80-11ea-88ba-d6d4a5c1f073.png)
![image](https://user-images.githubusercontent.com/62740686/93660309-febfe180-fa7f-11ea-9f31-1125b09c0a47.png)
![image](https://user-images.githubusercontent.com/62740686/93660305-e8b22100-fa7f-11ea-90e2-fd222d7c2f21.png)

2. 部署Deployment文件(直接使用nacos-quick-start.yaml文件部署一样的效,只要重启服务器就会导致访问不了，必须重新部署)
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nacos-standalone-v1
  namespace: common-projects
  labels:
    app: nacos-standalone
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos-standalone
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nacos-standalone
        version: v1
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-vy7pwg
          persistentVolumeClaim:
            claimName: common-pvc
      containers:
        - name: container-9r030f
          image: 'nacos/nacos-server:1.3.2'
          ports:
            - name: tcp-8848
              containerPort: 8848
              protocol: TCP
          env:
            - name: MODE
              value: standalone
            - name: SPRING_DATASOURCE_PLATFORM
              value: mysql
            - name: MYSQL_SERVICE_HOST
              value: mysql.database-projects
            - name: MYSQL_SERVICE_DB_NAME
              value: nacos_system
            - name: MYSQL_SERVICE_PORT
              value: '3306'
            - name: MYSQL_SERVICE_USER
              value: root
            - name: MYSQL_SERVICE_PASSWORD
              value: root
            - name: NACOS_AUTH_ENABLE
              value: 'false'
          resources: {}
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: volume-vy7pwg
              mountPath: /home/nacos/logs
              subPath: nacos/logs
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      affinity: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

```

3. 如果每次重启都需要重新部署，这个也太麻烦了吧
