### ISSUE TITLE
Using the remote server as the registration center and configuration center, an error is reported when the project is started

### ISSUE THREAD

**Issue by 13721549833** [alibaba/nacos#4114]
Type: *bug report*

### Describe what happened (or what feature you want)

Using version 2.2.3.release, when configuring the registry and configuration center at the same time, an error is reported when the business project is started, and the service is not successfully registered with Nacos. What else should be configured?

### The project configuration is shown in the figure below：

1. pom.xml

```xml
<dependency>
      <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
      <version>2.2.3.RELEASE</version>
</dependency>
<dependency>
      <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
      <version>2.2.3.RELEASE</version>
</dependency>
```

2. bootstrap.yml

```yml
server:
  port: 8081
spring:
  application:
    name: learning2think-edu-user
  cloud:
    # nacos配置
    nacos:
      discovery:
        # 集群中各节点信息都配置在这（域名-VIP-绑定映射到各个实例的地址信息）
        server-addr: 106.75.165.152:8848
      # nacos config 配置
      config:
        server-addr: 106.75.165.152:8848
        # 锁定server端的配置文件（读取它的配置项）
        group: DEFAULT_GROUP # 默认分组就是DEFAULT_GROUP，如果使用默认分组可以不配置
        file-extension: yaml #默认properties
```

3. application.yml

```yml
spring:
  # mysql数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/learning2think_education?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
```
4. Nacos Management interface

![http://image.snowsea.com.cn/1604306761%281%29.png](http://image.snowsea.com.cn/1604306761(1).png)

### The error information is as follows:

`com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Mon Nov 02 16:16:33 CST 2020</div><div>There was an unexpected error (type=Bad Request, status=400).</div><div>receive invalid redirect request from peer 127.0.0.1</div></body></html>`

![image-20201102161813517](http://image.snowsea.com.cn/image-20201102161813517.png)

`com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([106.75.165.152:8848]) tried: ErrCode:400, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Mon Nov 02 16:16:34 CST 2020</div><div>There was an unexpected error (type=Bad Request, status=400).</div><div>receive invalid redirect request from peer 127.0.0.1</div></body></html>`

![image-20201102161945646](http://image.snowsea.com.cn/image-20201102161945646.png)

### Anything else we need to know?
