### ISSUE TITLE
Unable to override datasource

### ISSUE THREAD

**Issue by CloudyAnt** [alibaba/nacos#4190]
# The `spring.datasource` in actived profile can not override the datasource configured in `spring.cloud.nacos.config`

I want to run unit tests using H2 which configured in `bootstrap-test.yml`. The nomal code is using Mysql which configured in Nacos config center.

`bootstrap.yml`
```yml
spring:
  cloud:
    nacos:
      config:
        server-addr: '@nacos.server.addr@'
        namespace: '@nacos.namespace@'
        ...
```

`bootstrap-test.yml`
```yml
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
    schema: classpath*:init.sql
```

I wish the `bootstrap-test.yml` will override the datasource.

The real thing is that the tests will use the Mysql, which means the datasource was not overrided.

```txt
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '000' for key 'uni_mobile'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
```

And these are the annotations on the test class:
```java
@SpringBootTest
@ActiveProfiles("test")
@RunWith(SpringRunner.class)
```

**Comment by CloudyAnt** [comment]
I guess this because `spring.datasource` and `spring.cloud.nacos.config` are 2 different config, so that Spring didn't do the override operation. Meanwhile, Nacos didn't handle this scenario too.

**Comment by CloudyAnt** [comment]
I've found a easy method:

`bootstrap-test.yml`
```yml
...
cloud:
    nacos:
      config:
        server-addr: abc
     discovery:
        server-add: abc
```

The addr *abc* can not be reached, so that Nacos won't affect out test environment anymore.
