### ISSUE TITLE
The spring boot project uses the distributed configuration center (Alibaba / Nacos or spring cloud config), SpringApplication.addListeners Method does not work（sping boot 2.3.5.RELEASE，spring cloud Hoxton.SR8）

### ISSUE THREAD

**Issue by np7sky** [alibaba/nacos#4223]
##  The spring boot project uses the distributed configuration center (Alibaba / Nacos or spring cloud config), SpringApplication.addListeners Method does not work（sping boot 2.3.5.RELEASE，spring cloud Hoxton.SR8）

dependency version
```xml
 <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.5.RELEASE</version>
    </parent>

<spring.cloud.version>Hoxton.SR8</spring.cloud.version>
    <spring-cloud-alibaba.version>2.2.1.RELEASE</spring-cloud-alibaba.version>
```

#### background

I want to use the variables defined in bootstrap.yml in log4j2. I don't want to define the log file path repeatedly.

#### My solution

Custom Spring boot Lookup reference [log4j2 spring boot lookup](http://logging.apache.org/log4j/2.x/manual/lookups.html)

But log4j2 Spring boot Lookup can't be used, so I customized the spring lookup reference [log4j2 plugins]( http://logging.apache.org/log4j/2.x/manual/plugins.html)

code show as below：

Log4J2SpringEnvLookup.java

```java
import org.apache.logging.log4j.core.LogEvent;
import org.apache.logging.log4j.core.config.plugins.Plugin;
import org.apache.logging.log4j.core.lookup.AbstractLookup;
import org.apache.logging.log4j.core.lookup.StrLookup;
import org.springframework.core.env.ConfigurableEnvironment;
import org.springframework.core.env.Environment;

@Plugin(name = "spring", category = StrLookup.CATEGORY)
public class Log4J2SpringEnvLookup extends AbstractLookup  {

    private static Environment environment;
    @Override
    public String lookup(final LogEvent event, final String key) {
        if(environment != null){
            return environment.getProperty(key);
        }
        return null;
    }

    public static void setEnvironment(ConfigurableEnvironment environment) {
        Log4J2SpringEnvLookup.environment = environment;
    }

}
```

Log4J2SpringEnvListener.java

```java
import org.springframework.boot.SpringApplication;
import org.springframework.boot.context.event.ApplicationEnvironmentPreparedEvent;
import org.springframework.boot.context.logging.LoggingApplicationListener;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationEvent;
import org.springframework.context.event.SmartApplicationListener;

public class Log4J2SpringEnvListener implements SmartApplicationListener {

    private static final Class<?>[] EVENT_TYPES = {ApplicationEnvironmentPreparedEvent.class};
    private static final Class<?>[] SOURCE_TYPES = {SpringApplication.class, ApplicationContext.class};

    @Override
    public boolean supportsEventType(Class<? extends ApplicationEvent> eventType) {
        return isAssignableFrom(eventType, EVENT_TYPES);
    }

    @Override
    public boolean supportsSourceType(Class<?> sourceType) {
        return isAssignableFrom(sourceType, SOURCE_TYPES);
    }

    private boolean isAssignableFrom(Class<?> type, Class<?>... supportedTypes) {
        if(type == null){
            return false;
        }
        for (Class<?> supportedType : supportedTypes) {
            if (supportedType.isAssignableFrom(type)) {
                return true;
            }
        }
        return false;
    }

    @Override
    public void onApplicationEvent(ApplicationEvent event) {
       if(event instanceof ApplicationEnvironmentPreparedEvent){
           Log4J2SpringEnvLookup.setEnvironment(((ApplicationEnvironmentPreparedEvent) event).getEnvironment());
       }
    }

    @Override
    public int getOrder() {
        //Must be executed before LoggingApplicationListener is executed, because log4j2 lookup is needed when executing LoggingApplicationListener
        return LoggingApplicationListener.DEFAULT_ORDER - 1;
    }

}
```

Main class：

```java
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class GiantApplication {
    public static void main(String[] args) {
        SpringApplication application = new SpringApplication(GiantApplication.class);
        application.addListeners(new Log4J2SpringEnvListener());
        application.run(args);
    }
}
```

log4j2-dev.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration status="WARN" monitorInterval="120">

    <Properties>
        <Property name="LOG_HOME">./logs/${spring:spring.application.name}</Property>
        <!-- @formatter:off -->
        <Property name="LOG_PATTERN">${spring:spring.application.name}:${spring:server.port} %date{yyyy-MM-dd HH:mm:ss.SSS} %level [%X{X-B3-TraceId},%X{X-B3-SpanId},%X{X-B3-ParentSpanId},%X{X-Span-Export}][%thread-%logger] - %msg%n</Property>
        <!-- @formatter:on -->
    </Properties>
    <Appenders>

        <Console name="Console" target="SYSTEM_OUT">
            <Filters>
                <ThresholdFilter level="info" onMatch="ACCEPT" onMismatch="DENY"/>
            </Filters>
            <PatternLayout pattern="${LOG_PATTERN}"/>
        </Console>

 
        <RollingRandomAccessFile name="InfoFile"
                                 fileName="${LOG_HOME}/info/info.log"
                                 filePattern="${LOG_HOME}/info.log.%d{yyyyMMdd}.%i.gz">
            <Filters>
                <ThresholdFilter level="info" onMatch="ACCEPT" onMismatch="DENY"/>
            </Filters>
            <PatternLayout pattern="${LOG_PATTERN}"/>
            <Policies>
                <TimeBasedTriggeringPolicy interval="6"/>
                <SizeBasedTriggeringPolicy size="50MB"/>
            </Policies>

            <DefaultRolloverStrategy max="10" compressionLevel="5">
              
                <Delete basePath="${LOG_HOME}" maxDepth="1">
                    <IfFileName glob="*.gz"/>
                    <IfLastModified age="3d"/>
                </Delete>
            </DefaultRolloverStrategy>
        </RollingRandomAccessFile>

        
        <RollingRandomAccessFile name="ErrorFile"
                                 fileName="${LOG_HOME}/error/error.log"
                                 filePattern="${LOG_HOME}/error.log.%d{yyyyMMdd}.%i.gz">
            <Filters>
                <ThresholdFilter level="error" onMatch="ACCEPT" onMismatch="DENY"/>
            </Filters>
            <PatternLayout pattern="${LOG_PATTERN}"/>
            <Policies>
                <TimeBasedTriggeringPolicy interval="6"/>
                <SizeBasedTriggeringPolicy size="50MB"/>
            </Policies>

            <DefaultRolloverStrategy max="10" compressionLevel="5">

                <Delete basePath="${LOG_HOME}" maxDepth="1">
                    <IfFileName glob="*.gz"/>
                    <IfLastModified age="3d"/>
                </Delete>
            </DefaultRolloverStrategy>
        </RollingRandomAccessFile>

        <Async name="AsyncFile" bufferSize="10">
            <AppenderRef ref="InfoFile"/>
            <AppenderRef ref="ErrorFile"/>
            <LinkedTransferQueue/>
        </Async>
    </Appenders>

    <Loggers>
        <logger name="com.baomidou.mybatisplus" level="WARN"/>
        <logger name="org.springframework" level="WARN"/>
        <logger name="org.mybatis" level="WARN"/>
        <Root level="INFO">
            <AppenderRef ref="AsyncFile"/>
            <AppenderRef ref="Console"/>
        </Root>
    </Loggers>

</Configuration>
```

bootstrap.yml

```yaml
spring:
  application:
    name: fish-giant
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
  cloud:
    nacos:
      config:
        server-addr: 192.168.26.17:8848
        namespace: dev
      discovery:
        server-addr: 192.168.26.17:8848
        namespace: dev
  datasource:
    name: local
    druid:
      url: jdbc:p6spy:mysql://localhost:3306/fish-giant?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: root@mysql
      filters: stat
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      max-wait: 60000
      min-idle: 1
      max-active: 20
      initial-size: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20

logging:
#  config: classpath:log4j2-dev.xml
  config: http://${spring.cloud.nacos.config.server-addr}/nacos/v1/cs/configs?dataId=log4j2-dev.xml&group=DEFAULT_GROUP&tenant=dev
server:
  port: 8052

```

But the console prompts when starting：

```Java
2020-11-13 11:41:47,494 main ERROR Could not create plugin of type class org.apache.logging.log4j.core.appender.rolling.DefaultRolloverStrategy for element DefaultRolloverStrategy: java.nio.file.InvalidPathException: Illegal char <:> at index 15: ./logs/${spring:spring.application.name} java.nio.file.InvalidPathException: Illegal char <:> at index 15: ./logs/${spring:spring.application.name}
```

If: remove the dependency of nacos, change bootstrap.yml to application.yml, it will take effect, the console output is as follows

```java
Connected to the target VM, address: '127.0.0.1:60912', transport: 'socket'

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.5.RELEASE)

fish-giant:8052 2020-11-13 11:50:29.471 INFO [,,,][background-preinit-org.hibernate.validator.internal.util.Version] - HV000001: Hibernate Validator 6.1.0.Final
fish-giant:8052 2020-11-13 11:50:29.513 INFO [,,,][main-idv.np7sky.fish.giant.GiantApplication] - Starting GiantApplication on DESKTOP-P840P24 with PID 4244
```

The log directory is also generated as shown in the figure：

![image-20201113115219219](https://user-images.githubusercontent.com/13186540/99034804-fe901e00-25b8-11eb-85db-cca93acb63f7.png)

The debugging results of idea found that when use nacos or spring cloud config 

, the SpringApplication.run method was executed twice as shown in the figure:

the first：

SpringApplication.java

![image-20201113115903351](https://user-images.githubusercontent.com/13186540/99034911-457e1380-25b9-11eb-95f6-e4d87a7e7e49.png)

Second : Log4J2SpringEnvListener is gone.

BootstrapApplicationListener.java

![image-20201113135049598](https://user-images.githubusercontent.com/13186540/99034951-66466900-25b9-11eb-9c1b-4a72dfedd4c2.png)

SpringApplication.java

![image-20201113115955251](https://user-images.githubusercontent.com/13186540/99034982-8118dd80-25b9-11eb-9653-92f0dffad3bc.png)

### I want the result

How to make Log4J2SpringEnvListener take effect so that variables in bootstrap.yml can be used in log4j2.xml.

or：

Do something so that Log4J2SpringEnvListener is called before LoggingApplicationListener. But Log4J2SpringEnvListener needs to be able to use the environment.

I used Google Translate and it may be difficult to understand,

Thank you for reading all this question!
