### ISSUE TITLE
nacos 1.4.0 与 xxl-job 2.0.0 同时使用，远程配置文件问题

### ISSUE THREAD

**Issue by wszpwsren** [alibaba/nacos#4398]
环境：nacos 1.4.0，xxl-job 2.0.0 ,springboot

nacos升级到1.4.0之后
远程配置值为空时，启动报错

远程配置

xxx.yaml
```
xxl:
  job:
    admin:
      addresses=: http://xxx.xxx/xxl-job-admin
    executor:
      appname: job-service
      address=:
      ip=:
      port: 5017
```
错误

`Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'xxl.job.executor.ip' in value "${xxl.job.executor.ip}"
        at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:178) ~[spring-core-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124) ~[spring-core-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239) ~[spring-core-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210) ~[spring-core-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:175) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:918) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1248) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        ... 26 common frames omitted
`

**Comment by KomachiSion** [comment]
查下nacos 客户端日志， 是不是收到了新配置。

**Comment by chuntaojun** [comment]
请先贴一下https://github.com/nacos-group/nacos-spring-boot-project/wiki/spring-boot-0.2.2-%E4%BB%A5%E5%8F%8A-0.1.2%E7%89%88%E6%9C%AC%E6%96%B0%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C 这个wiki中的配置内容

**Comment by wszpwsren** [comment]
> 请先贴一下https://github.com/nacos-group/nacos-spring-boot-project/wiki/spring-boot-0.2.2-%E4%BB%A5%E5%8F%8A-0.1.2%E7%89%88%E6%9C%AC%E6%96%B0%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C 这个wiki中的配置内容

```
spring:
  cloud:
      nacos:
        config:
          server-addr: x.x.x.x:3000
          shared-configs:
            - data-id: opentracing.yaml
          extension-configs:
            - data-id: job-service.yaml
              refresh: true
        discovery:
          server-addr: ${spring.cloud.nacos.config.server-addr}
          metadata:
            group: service-group
            version: 1.0.0
            region: test
  nacos:
    server-addr: ${spring.cloud.nacos.config.server-addr}
```

**Comment by wszpwsren** [comment]
> 查下nacos 客户端日志， 是不是收到了新配置。


是这个？

```
2020-12-04 15:31:31.315  WARN 32533 --- [main] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[idea-service] & group[DEFAULT_GROUP]
2020-12-04 15:31:31.323  WARN 32533 --- [main] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[idea-service.properties] & group[DEFAULT_GROUP]
```

**Comment by chuntaojun** [comment]
看你的配置的话，数据应该是可以正确拉下的，看下整个日志，有没有吧job-service.yaml配置拉下来，还是说还没到拉job-service.yaml配置，就已经报错了，这样的话，你可能需要看下xxl-job的初始化了，这个不是nacos的问题

**Comment by wszpwsren** [comment]
> 看你的配置的话，数据应该是可以正确拉下的，看下整个日志，有没有吧job-service.yaml配置拉下来，还是说还没到拉job-service.yaml配置，就已经报错了，这样的话，你可能需要看下xxl-job的初始化了，这个不是nacos的问题

配置拉下来了，排查之后似乎是远程配置中的空值都被转成 “” 了
现在的处理办法是在本地配置里把空值配置一下
就这样
bootstrap.yml
```
xxl:
  job:
    accessToken:
    executor:
      address:
```
