### ISSUE TITLE
配置列表自动出现很多以接口为group的配置文件，并且有非常多nacos线程，正常吗？

### ISSUE THREAD

**Issue by Sakuramaomao** [alibaba/nacos#4491]
### Describe what happened (or what feature you want)
1、项目启动时，配置列表中自动出现很多以application.name为DataId，以mapping-接口名称为Group的配置项。
![image](https://user-images.githubusercontent.com/18359870/102195984-411b8200-3efa-11eb-80b8-3e0ef4f55264.png)

2、整个项目大约有160个需要暴露的接口，但产生了2000左右线程，并且绝大部分是com.alibaba.nacos.naming.beat.sender、com.alibaba.nacos.naming.client.listener、com.alibaba.nacos.naming.failover以及com.alibaba.nacos.naming.push.receiver线程，估计有1800左右。
![image](https://user-images.githubusercontent.com/18359870/102196093-63ad9b00-3efa-11eb-8ba4-704942913f06.png)
![image](https://user-images.githubusercontent.com/18359870/102196116-6ad4a900-3efa-11eb-8098-0672eb9df73f.png)
![image](https://user-images.githubusercontent.com/18359870/102196132-70ca8a00-3efa-11eb-9599-bf33ec37e9a3.png)

3、项目启动后，上述绝大部分线程处于WAITING/TIMED_WAITING状态，CPU总占用率不高，10%左右（i7-8565U 4c8t）。

请问出现配置列表自动出现很多的情况、线程数量过多的情况正常吗？

### Describe what you expected to happen
我觉得只是单纯的把nacos当做注册中心使用，并没有使用配置中心功能，不应该产生那么多线程吧。不知道是不是我那里配置有问题。

### How to reproduce it (as minimally and precisely as possible)
===============Dubbo配置   start==================
```
dubbo:
  registry:
    # provider服务注册地址
    address: nacos://127.0.0.1:8849
    # 启动时检查注册中心
    check: false
  scan:
    # 扫描Services注解
    base-packages: com.datah.provider
  protocol:
    # 以dubbo协议暴露
    name: dubbo
    port: -1
  provider:
    # 重试
    retries: 0
    # 消费超时时间
    timeout: 60000
  application:
    qos-enable: false
```
===============Dubbo配置   end==================

===============pom配置   start==================
```
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter</artifactId>
<version>2.2.5.RELEASE</version>

<groupId>org.apache.dubbo</groupId>
<artifactId>dubbo-spring-boot-starter</artifactId>
<version>2.7.7</version>

<groupId>com.alibaba.nacos</groupId>
<artifactId>nacos-client</artifactId>
<version>1.2.1</version>
```
===============pom配置   end==================

### Tell us your environment
1、基础环境使用的springboot2.2.5+dubbo2.7.7+nacos1.2.1。
2、我目前只是用nacos作为注册中心使用，没有使用配置中心的任何功能。

### Anything else we need to know?
对了，我用jmap查看了对象的数量。如下图所示，com.alibaba.nacos.client.naming.NacosNamingService类在堆中有164个实例，com.alibaba.nacos.client.config.impl.ClientWorker只有一个。 此外，com.alibaba.nacos.api.naming.pojo.ServiceInfo有114582个， com.alibaba.nacos.api.naming.pojo.ServiceInfo有114568个。
![image](https://user-images.githubusercontent.com/18359870/102195503-a1f68a80-3ef9-11eb-8c4d-ff3a080c22d0.png)
