### ISSUE TITLE
无法通过API发布一个YAML类型配置

### ISSUE THREAD

**Issue by xfengfeng** [alibaba/nacos#4647]
**Is your feature request related to a problem? Please describe.**
作为一名运维，需要定期把开发环境的配置导出并导入到其它测试环境，导出配置后需要更改IP、密码这些，才能导入到其它环境。希望通过脚本定时自动处理。使用API无法发布yaml类型配置文件
```
curl -XPOST "http://192.168.0.90:8848/nacos/v1/cs/configs?dataId=test-dev.yml&type=yaml&group=DEFAULT_GROUP&content=内容"
```

内容大致如下
```
spring:
  datasource:
    name: mysql
    url: jdbc:mysql://192.168.0.9:3306/cloud?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
        minimum-idle: 10
        maximum-pool-size: 20
        idle-timeout: 500000
        max-lifetime: 540000
        connection-timeout: 60000
        connection-test-query: SELECT 1
```

**Describe the solution you'd like**
- 支持通过API导入压缩包
- 修改API，内容从文件里读取上传，类似如下：
```
  curl -XPOST -d @config.yml http://192.168.0.90:8848/nacos/v1/cs/configs?dataId=test-dev.yml&type=yaml&group=DEFAULT_GROUP
```

**Describe alternatives you've considered**
- 直接修改数据库，但需要重启nacos服务才能生效
- 对内容进行base64加密后再通过API发布，发布后的内容依然是加密后的内容 
- 对& / =等特殊符号转码，转码后请求API失败

**Additional context**
报错信息
```
<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>
```
