### ISSUE TITLE
The service could not register successfully！nacos 1.4.1 version

### ISSUE THREAD

**Issue by wxson** [alibaba/nacos#5057]
nacos：Running in stand alone mode, All function modules

版本依赖：（Version dependence）
nacos：v1.4.1
spring-boot：v2.3.2.RELEASE
spring-cloud-alibaba-dependencies：v2.2.5.RELEASE

服务无法注册成功！日志未提供任何内容帮助排查问题。
The service could not register successfully！The log does not provide anything to help troubleshoot the problem。

日志：（log）
![image](https://user-images.githubusercontent.com/17423455/110407965-ca88bd80-80bf-11eb-94b3-3996ae733ba3.png)

**Comment by KomachiSion** [comment]
${user.home}/logs/nacos/naming.log看下有没有日志，如果没有就说明打印到你的日志里了，再看下有没有什么信息。
如果还没有信息，可能是spring cloud alibaba的使用方法不对导致的，可以看下sca的wiki和example。

**Comment by wxson** [comment]
@KomachiSion 感谢您的回复：
首先：我成功启动nacos v1.4.1注册服务：Nacos started successfully in stand alone mode. use external storage
浏览器访问：http://localhost:8848/nacos/  成功
POSTMAN：http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=saas-gateway-dev.yaml&group=DEFAULT_GROUP 成功
> ${user.home}/logs/nacos/naming.log看下有没有日志，如果没有就说明打印到你的日志里了，再看下有没有什么信息。  
 
当我尝试启动nacos_client时，${user.home}/logs/nacos/naming.log文件未产生日志输出，当我停止nacos服务时，naming.log日志有输出：
```
NacosException: failed to req API:/nacos/v1/ns/instance/list after all servers([127.0.0.1:8848]) 
```
同级目录下的config.log日志：
```
2021-03-09 11:27:46.030 INFO [main :c.a.n.c.u.ParamUtil] [settings] [req-serv] nacos-server port:8848
2021-03-09 11:27:46.031 INFO [main :c.a.n.c.u.ParamUtil] [settings] [http-client] connect timeout:1000
2021-03-09 11:27:46.033 INFO [main :c.a.n.c.u.ParamUtil] PER_TASK_CONFIG_SIZE: 3000.0
2021-03-09 11:27:46.043 INFO [main :c.a.n.c.i.CredentialWatcher] null No credential found
```
> 如果还没有信息，可能是spring cloud alibaba的使用方法不对导致的，可以看下sca的wiki和example。  
  
Spring Cloud Version | Spring Cloud Alibaba Version | Spring Boot Version
-- | -- | --
Spring Cloud Hoxton.SR8 | 2.2.5.RELEASE | 2.3.2.RELEASE   

nacos_client配置：
```
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        prefix: ${spring.application.name}
        file-extension: yaml

  profiles:
    active: @profiles.active@
```
同时也启用了@EnableDiscoveryClient
不知道是不是我忽略掉了哪一个步骤导致的？如果你知道，还请帮忙解答一下，感谢！
