### ISSUE TITLE
nacos-1.4.1 : 服务端开启权限认证后无法使用 Dubbo 注册中心

### ISSUE THREAD

**Issue by rkzlym** [alibaba/nacos#5330]
**Describe the bug**

当我的 nacos 服务端打开下列这行配置的时候，客户端使用 dubbo 注册失败，返回结果 `unknown user`

```properties
nacos.core.auth.enabled=true
```

下面是我客户端的配置

```yaml
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        username: nacos
        password: nacos
dubbo:
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
  application:
    name: ${spring.application.name}
```

**Possible Bug**

查看源码

在 `com.alibaba.nacos.client.config.impl.ClientWorker` 中找到 440-442 行

请求失败，403，返回 `unknown user!`.

```java
HttpRestResult<String> result = agent
        .httpPost(Constants.CONFIG_CONTROLLER_PATH + "/listener", headers, params, agent.getEncode(),
                readTimeoutMs);
```

跟进发现鉴权的Token来自 `com.alibaba.nacos.client.security.SecurityProxy`，查看 89-94 行

```java
public SecurityProxy(Properties properties, NacosRestTemplate nacosRestTemplate) {
    username = properties.getProperty(PropertyKeyConst.USERNAME, StringUtils.EMPTY);
    password = properties.getProperty(PropertyKeyConst.PASSWORD, StringUtils.EMPTY);
    contextPath = ContextPathUtil.normalizeContextPath(properties.getProperty(PropertyKeyConst.CONTEXT_PATH, "/nacos"));
    this.nacosRestTemplate = nacosRestTemplate;
}
```

发现 username 和 password 来自 `properties` 追溯其来源至  `com.alibaba.nacos.client.naming.NacosNamingMaintainService` 的 53-57 行，发现 `properties` 里只 set 了一个 serverList ，并没有 set username & password，所以无论配置文件怎么配置，都无法在此场景下将服务注册到nacos，因此认为是一个BUG。

```java
public NacosNamingMaintainService(String serverList) throws NacosException {
    Properties properties = new Properties();
    properties.setProperty(PropertyKeyConst.SERVER_ADDR, serverList);
    init(properties);
}
```

**external context**

反观 `com.alibaba.nacos.client.config.http.ServerHttpAgent` ，它可以用 properties 里获取到 username 和 password

而且在278行时会调用 nacos 的登录接口，将 accessToken 存入到 SecurityProxy，后续调用无问题

猜测这才是正确写法

```java
this.securityProxy.login(this.serverListMgr.getServerUrls());
```
