### ISSUE TITLE
nacos:2.0.0的开启权限配置，但是无效，没有token都可以直接GET请求访问任何配置信息

### ISSUE THREAD

**Issue by hegphegp** [alibaba/nacos#5373]
##### 提供完整的docker-compose.yml测试脚本
```
version: "3.3"

services:
  nacos:
    image: nacos/nacos-server:2.0.0
    container_name: nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos_devtest
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
      - nacos.auth.enable=true
      - spring.security.enabled=true
      - security.basic.enabled=true
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: always

  mysql:
    container_name: mysql
    restart: always
    image: nacos/nacos-mysql:8.0.16
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nacos_devtest
      - MYSQL_USER=nacos
      - MYSQL_PASSWORD=nacos
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"

```
* 然后访问 http://localhost:8848/nacos/v1/cs/configs?dataId=&group=&appName=&config_tags=&pageNo=1&pageSize=10&tenant=&search=accurate 链接，没有token令牌，可以访问到该链接。那么登录校验有啥意义，多此一举，导致其他人都知道参数有没有用
