### ISSUE TITLE
NacosException: server is DOWN now, please try again later!

### ISSUE THREAD

**Issue by sbwfnhn** [alibaba/nacos#5497]
使用docker部署，服务能正常注册，业务与集群都一直正常，但是客户端就是会报如下错误
ERROR 11 [] [com.alibaba.nacos.naming.beat.sender] com.alibaba.nacos.client.naming [NA] failed to request
com.alibaba.nacos.api.exception.NacosException: server is DOWN now, please try again later!
后面发现通过添加hostname方式解决
```
--hostname docker003 \
--add-host docker001:172.16.100.65 \
--add-host docker002:172.16.100.64 \
--add-host docker003:172.16.100.63 \
```

完整的如下
```
docker run -d --restart=always -p 8848:8848 \
-p 9555:9555 \
-p 9848:9848 \
-p 7848:7848 \
-p 9849:9849 \
--hostname docker003 \
--add-host docker001:172.16.100.65 \
--add-host docker002:172.16.100.64 \
--add-host docker003:172.16.100.63 \
-e "NACOS_SERVER_IP=172.16.100.63" \
-e "NACOS_SERVERS=172.16.100.63,172.16.100.64,172.16.100.65" \
-e "NACOS_SERVER_PORT=8848" \
-e "MYSQL_DATABASE_NUM=1" \
-e "SPRING_DATASOURCE_PLATFORM=mysql" \
-e "MYSQL_SERVICE_HOST=rm-1111.mysql.rds.aliyuncs.com" \
-e "MYSQL_SERVICE_DB_NAME=nacos"  \
-e "MYSQL_SERVICE_PORT=3306"  \
-e "MYSQL_SERVICE_USER=nacos"  \
-e "MYSQL_SERVICE_PASSWORD=1111" \
--name  nacos3 nacos/nacos-server
```

也可以通过--network host方式解决
```
docker run -d --restart=always \
--network host \
-e "NACOS_SERVER_IP=172.16.100.63" \
-e "NACOS_SERVERS=172.16.100.63,172.16.100.64,172.16.100.65" \
-e "NACOS_SERVER_PORT=8848" \
-e "MYSQL_DATABASE_NUM=1" \
-e "SPRING_DATASOURCE_PLATFORM=mysql" \
-e "MYSQL_SERVICE_HOST=rm-1111.mysql.rds.aliyuncs.com" \
-e "MYSQL_SERVICE_DB_NAME=nacos"  \
-e "MYSQL_SERVICE_PORT=3306"  \
-e "MYSQL_SERVICE_USER=nacos"  \
-e "MYSQL_SERVICE_PASSWORD=1111" \
--name  nacos3 nacos/nacos-server
```

以前1.1.4版本是不用映射这么多端口的，升到2.0版本多了这么多端口，不映射集群起不来，所以都映射集群就起来了

k8s的如下配置可以正常运行
```
kind: Pod
apiVersion: v1
metadata:
  name: nacos3-pod
  namespace: default
  labels:
    k8s-app: nacos3-pod
spec:
  containers:
    - name: nacos3-pod
      image: 'nacos/nacos-server'
      imagePullPolicy: IfNotPresent
      ports:
        - name: port1
          containerPort: 8848
          hostPort: 8848
          protocol: TCP
          hostIP: 0.0.0.0
        - name: port2
          containerPort: 9848
          hostPort: 9848
          protocol: TCP
        - name: port3
          containerPort: 7848
          hostPort: 7848
          protocol: TCP
        - name: port4
          containerPort: 9849
          hostPort: 9849
          protocol: TCP
        - name: port5
          containerPort: 9555
          hostPort: 9555
          protocol: TCP
      env:
        - name: 'NACOS_SERVER_IP'
          value: '172.16.10.83'
        - name: 'NACOS_SERVERS'
          value: '172.16.10.81,172.16.10.82,172.16.10.83'
        - name: 'NACOS_SERVER_PORT'
          value: '8848'
        - name: 'SPRING_DATASOURCE_PLATFORM'
          value: 'mysql'
        - name: 'MYSQL_SERVICE_HOST'
          value: 'proxysql.aaa.com'
        - name: 'MYSQL_SERVICE_DB_NAME'
          value: 'nacos'
        - name: 'MYSQL_SERVICE_PORT'
          value: '8066'
        - name: 'MYSQL_SERVICE_USER'
          value: 'aa'
        - name: 'MYSQL_SERVICE_PASSWORD'
          value: '11111'
      #resources: {}
      resources:
        limits:
          cpu: '2'
          memory: 2248Mi
        requests:
          cpu: 500m
          memory: 512Mi
  restartPolicy: Always
  nodeName: master03
 ```
