### ISSUE TITLE
When using nacos custom grouping, Spring-Cloud-Gateway to open spring.cloud.gateway.discovery.locator=true cannot through the gateway service and the service name for the micro-service visit

### ISSUE THREAD

**Issue by langxyzzz** [alibaba/nacos#5710]
**Describe the bug**
Spring-Cloud-Gateway to open `spring.cloud.gateway.discovery.locator=true` configuration. When NACOS uses the default grouping, you can access the microservices through the gateway service and service name. When NACOS uses custom grouping, it will not be possible to use the gateway service and service name for microservice access.
Gateway micro-service configuration
```
server:
  port: 8090
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true    
      routes:
        - id: consumer
          uri: http://127.0.0.1:8081/consumer
          predicates:
            - Path=/consumer/**   
        - id: producer
          uri: http://127.0.0.1:8082/producer
          predicates:
            - Path=/producer/** 
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 688e15e0-4a5c-437d-b59f-840c1407c6ba
        group: SPRING_CLPOUD_GROUP
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        namespace: 688e15e0-4a5c-437d-b59f-840c1407c6ba
        group: SPRING_CLOUD_GROUP
        timeout: 3000            
```
Consumer micro-service configuration
```
server:
  port: 8081
  servlet:
    context-path: /consumer
  application:
    name: spring-cloud-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 688e15e0-4a5c-437d-b59f-840c1407c6ba
        group: SPRING_CLOUD_GROUP
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        group: SPRING_CLOUD_GROUP
        namespace: 688e15e0-4a5c-437d-b59f-840c1407c6ba
```
Producer micro-service configuration
```
server:
  port: 8082
  servlet:
    context-path: /producer
  application:
    name: spring-cloud-producer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 688e15e0-4a5c-437d-b59f-840c1407c6ba
        group: SPRING_CLOUD_GROUP
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        group: SPRING_CLOUD_GROUP
        namespace: 688e15e0-4a5c-437d-b59f-840c1407c6ba
```

**Expected behavior**
My expectation is that through `http://127.0.0.1:8090/spring-cloud-consumer/consumer/index` access to consumer micro-services, through `http://127.0.0.1:8090/spring-cloud-producer/producer/index` access to producer micro-services

**Acutally behavior**
`http://127.0.0.1:8090/spring-cloud-consumer/consumer/index` return 404
`http://127.0.0.1:8090/spring-cloud-producer/producer/index` return 404
`http://127.0.0.1:8090/consumer/index` can visit Consumer micro-services
`http://127.0.0.1:8090/producer/index` can visit Producer micro-services

**How to Reproduce**
After delete the `spring.cloud.nacos.discovery.group` configuration: 
`http://127.0.0.1:8090/spring-cloud-consumer/consumer/index` can visit Consumer micro-services
`http://127.0.0.1:8090/spring-cloud-producer/producer/index` can visit Producer micro-services
After my repeated experiments, the problem is only related to the `spring.cloud.nacos.discovery.group` configuration discovered by the NACOS service

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version nacos-server 1.4.1, nacos-client 1.4.1
 - Module nacos-discovery
 - SDK spring-cloud-alibaba 2021.1, spring-cloud 2020.0.2, spring-boot 2.4.2

**Additional context**
