### ISSUE TITLE
MCP-Over-XDS failed to synchronize the NACOS service to Istio Envoy XDS

### ISSUE THREAD

**Issue by CoderPoet** [alibaba/nacos#5779]
**Describe the bug**
MCP-Over-XDS failed to sync Nacos's service to Envoy XDS. The list of services cannot be pulled because the wrong ServiceManager was used

**Expected behavior**
MCP-Over-XDS successfully synced Nacos services to Istio Envoy XDS

**Acutally behavior**
![image](https://user-images.githubusercontent.com/19374680/118743591-34be9b00-b885-11eb-85d7-ff0b64101904.png)
![image](https://user-images.githubusercontent.com/19374680/118743599-39834f00-b885-11eb-8cca-f20c7bdc8dc1.png)

**How to Reproduce**
1. git clone https://github.com/nacos-group/nacos-k8s.git
2. performer ./quick-startup.sh
3. enable mcp server for nacos by configmap volume
```
nacos.istio.mcp.server.enabled=true
```

```
volumeMounts:
            - mountPath: /home/nacos/conf/application.properties
              name: nacos-application
              subPath: application.properties
```

4. install istio of 1.9.x version，add configSources to meshConfig
```
meshConfig:
    configSources:
      - address: xds://nacos-0.nacos-headless.nacos.svc.cluster.local:18848
```

**Desktop (please complete the following information):**
- OS: [kubernetes]
- Version [nacos-server 2.0.1]
- Module [istio]
- SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]
