### ISSUE TITLE
Nacos 2.0.2 config ERROR where use other namespaces

### ISSUE THREAD

**Issue by carl0804** [alibaba/nacos#6127]
**Describe the bug**

**Nacos 2.0.2 config ERROR where use other namespaces**

I create a new namespace: dev, under this ns, i copy the config yml file from public ns which can works fine.
But when i start the application, some errors occurs:
```
Could not resolve placeholder 'config.env' in value "${config.env}"
```
Don't know why.

**Environment:**
OS: Mac OS Catalina 10.15.7
Nacos version: 2.0.2, standalone
Spring-boot.version: 2.3.7.RELEASE
Spring-cloud-alibaba.version: 2.2.3.RELEASE

My application.yml is below:
```
spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        context-path: /nacos
        file-extension: yml
        namespace: dev
        group: DEFAULT_GROUP
```
