### ISSUE TITLE
nacos客户端连接远程服务端：NacosException: Client not connected,current status:STARTING 都为2.0.0版本

### ISSUE THREAD

**Issue by laxiangxiang** [alibaba/nacos#6154]
在远程Linux虚拟机上启动nacos 2.0.0服务端，可以正常访问管理页面，本地电脑运行springcloudAlibaba整合nacos的程序一直刷异常com.alibaba.nacos.api.exception.NacosException: Client not connected,current status:STARTING，程序启动后，服务注册是成功的，但是读取不了配置文件，启动的时候可以从nacos中读取配置文件。如果那nacos服务端运行在本地电脑上，则没有这个问题。

**Comment by solomonqbq** [comment]
遇到了同样的问题，版本2.0.1

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/docs/2.0.0-compatibility.html 
检查端口是否正确开放。

本地没有问题是因为没有端口拦截。

**Comment by laxiangxiang** [comment]
![图片](https://user-images.githubusercontent.com/20766822/123362252-f8c4d700-d5a2-11eb-9373-ff3da22502fb.png)
检查过了，telnet可以远程连接，防火墙全部关了，虚拟机使用的是桥接网络模式。应用远程连接貌似功能没有问题，刷新配置可以，服务注册也可以，但就是一直报这个错误。客户端配置一个地址：ip:8848还需要配置其它端口？服务端启动：./startup.sh -m standalone，使用docker启动命令：docker run --name nacos-server-2.0.0 --restart always -itd -e MODE=standalone -p 8848:8848 -p 9848:9848 -p9849:9849 -v /home/nacos/logs:/home/nacos/logs  nacos/nacos-server:2.0.0，这样有问题吗？

**Comment by laxiangxiang** [comment]
![图片](https://user-images.githubusercontent.com/20766822/123367930-6b3ab480-d5ad-11eb-9c0d-879110e1ab6f.png)

检查过了，telnet可以远程连接，防火墙全部关了，虚拟机使用的是桥接网络模式。应用远程连接貌似功能没有问题，刷新配置可以，服务注册也可以，但就是一直报这个错误。客户端配置一个地址：ip:8848还需要配置其它端口？服务端启动：./startup.sh -m standalone，使用docker启动命令：docker run --name nacos-server-2.0.0 --restart always -itd -e MODE=standalone -p 8848:8848 -p 9848:9848 -p9849:9849 -v /home/nacos/logs:/home/nacos/logs nacos/nacos-server:2.0.0，这样有问题吗？

**Comment by fangjing828** [comment]
> ![图片](https://user-images.githubusercontent.com/20766822/123367930-6b3ab480-d5ad-11eb-9c0d-879110e1ab6f.png)
> 
> 检查过了，telnet可以远程连接，防火墙全部关了，虚拟机使用的是桥接网络模式。应用远程连接貌似功能没有问题，刷新配置可以，服务注册也可以，但就是一直报这个错误。客户端配置一个地址：ip:8848还需要配置其它端口？服务端启动：./startup.sh -m standalone，使用docker启动命令：docker run --name nacos-server-2.0.0 --restart always -itd -e MODE=standalone -p 8848:8848 -p 9848:9848 -p9849:9849 -v /home/nacos/logs:/home/nacos/logs nacos/nacos-server:2.0.0，这样有问题吗？

检查下 nacos 地址前后是否有空格，这个在我本地也会触发错误。

**Comment by myifeng** [comment]
I have the same problem, how to solve it ？ I don't think this issue should be closed

**Comment by gengzhy** [comment]
最近也遇到同样的问题，请问该如何解决呢？

**Comment by KoalaBryson** [comment]
环境：Nacos版本 2.0.3，docker镜像，M1 Mac
问题描述：页面访问正常，curl -X POST正常，但是使用Java SDK集成发布失败
原因定位：跟踪源码，异常描述： Client not connected,current status:STARTING，客户端gRPC无法和服务端创建链接，在Nacos2.X版本中，增加了gRPC通信端口，需要由docker一并映射出来，否则就会出现无法初始化连接。
解决方案：在docker容器中映射9848端口

**Comment by iamforrest** [comment]
> 环境：Nacos版本 2.0.3，docker镜像，M1 Mac
> 问题描述：页面访问正常，curl -X POST正常，但是使用Java SDK集成发布失败
> 原因定位：跟踪源码，异常描述： Client not connected,current status:STARTING，客户端gRPC无法和服务端创建链接，在Nacos2.X版本中，增加了gRPC通信端口，需要由docker一并映射出来，否则就会出现无法初始化连接。
> 解决方案：在docker容器中映射9848端口

thx! saved my time when I tried to run on my m1 mbp

**Comment by xingyehuang** [comment]
记录一下，docker 启动nacos，需要同时映射9848端口。9848端口开通后，服务启动正常。

**Comment by 1806150981** [comment]
环境:腾讯云 centos8 nacos nacos-config-spring-boot-starter 0.2.12 
问题:springboot 读取单节点nacos 本地nacos可以读取 公网ip不可以读取
已解决 需要开放端口 8848 7848 9848 9849 端口后可以正常读取配置文件
如上述还未解决请联系我的邮箱 1806150981@qq.com

**Comment by weirongchen2012** [comment]
Yes. the same question happened to me, and recording the mentioned i added the 7848 9848 7849,8849,9849 than registered the nacos server;

**Comment by jeffreyji666** [comment]
> 环境:腾讯云 centos8 nacos nacos-config-spring-boot-starter 0.2.12 问题:springboot 读取单节点nacos 本地nacos可以读取 公网ip不可以读取 已解决 需要开放端口 8848 7848 9848 9849 端口后可以正常读取配置文件 如上述还未解决请联系我的邮箱 [1806150981@qq.com](mailto:1806150981@qq.com)

2022.0.0.0-RC2版本, 4个端口都可以telnet通, 但还是报错:
com.alibaba.nacos.api.exception.NacosException: Client not connected, current status:STARTING
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:643) ~[nacos-client-2.2.1.jar:?]
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:623) ~[nacos-client-2.2.1.jar:?]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:357) ~[nacos-client-2.2.1.jar:?]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:210) ~[nacos-client-2.2.1.jar:?]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:124) ~[nacos-client-2.2.1.jar:?]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:98) ~[nacos-client-2.2.1.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:143) ~[nacos-client-2.2.1.jar:?]

**Comment by MuChenMuXuan** [comment]
> 环境：Nacos版本 2.0.3，docker镜像，M1 Mac 问题描述：页面访问正常，curl -X POST正常，但是使用Java SDK集成发布失败 原因定位：跟踪源码，异常描述： Client not connected,current status:STARTING，客户端gRPC无法和服务端创建链接，在Nacos2.X版本中，增加了gRPC通信端口，需要由docker一并映射出来，否则就会出现无法初始化连接。 解决方案：在docker容器中映射9848端口

对头。我的问题原因和这个类似。

我是用nginx做nacos反向代理，最开始只配置了http代理，实际上还需要增加tcp代理。
我的http代理的端口是25015，还需要增加三个tcp代理，端口相对于25015 offset +/- 1000：
```
upstream nacos-7848 {
        server xxx:7848;
}
upstream nacos-9848 {
        server xxx:9848;
}
upstream nacos-9849 {
        server xxx:9849;
}

server {
        listen 26015;
        proxy_pass nacos-9848;
}
server {
        listen 26016;
        proxy_pass nacos-9849;
}
server {
        listen 24015;
        proxy_pass nacos-7848;
}
```

**Comment by myifeng** [comment]
邮件已收到，我会尽快处理！

**Comment by freemankevin** [comment]
watch the ports : `0.0.0.0:9848-9849->9848-9849/tcp`
```shell
root@deepin-1:~/nacos-cluster# docker-compose ps -a 
NAME      IMAGE                            COMMAND                  SERVICE   CREATED         STATUS                        PORTS
mysql     freemankevin/nacos-mysql:v8      "docker-entrypoint.s…"   mysql     2 minutes ago   Up About a minute (healthy)   0.0.0.0:3306->3306/tcp, 33060/tcp
nacos1    nacos/nacos-server:v2.3.0-slim   "bin/docker-startup.…"   nacos1    2 minutes ago   Up About a minute (healthy)   0.0.0.0:7848->7848/tcp, 0.0.0.0:8848->8848/tcp, 0.0.0.0:9848-9849->9848-9849/tcp
nacos2    nacos/nacos-server:v2.3.0-slim   "bin/docker-startup.…"   nacos2    2 minutes ago   Up About a minute (healthy)   0.0.0.0:7849->7848/tcp, 0.0.0.0:8849->8848/tcp, 0.0.0.0:9869->9848/tcp, 0.0.0.0:9851->9849/tcp
nacos3    nacos/nacos-server:v2.3.0-slim   "bin/docker-startup.…"   nacos3    2 minutes ago   Up About a minute (healthy)   0.0.0.0:7850->7848/tcp, 0.0.0.0:8850->8848/tcp, 0.0.0.0:9870->9848/tcp, 0.0.0.0:9852->9849/tcp
```

this is my yaml file and now it's work.
```yaml
version: "3.8"

x-nacos-common: &nacos-common
  image: nacos/nacos-server:${NACOS_VERSION}
  volumes:
    - ./conf/application.properties:/home/nacos/conf/application.properties
  env_file:
    - ./env/nacos-hostname.env
  restart: always
  depends_on:
    mysql:
      condition: service_healthy
  healthcheck:
    test: ["CMD-SHELL", "curl -f --head --connect-timeout 5 http://localhost:8848/nacos || exit 1"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 40s

services:
  nacos1:
    <<: *nacos-common
    hostname: nacos1
    container_name: nacos1
    volumes:
      - /data/nacos/cluster-logs/nacos1:/home/nacos/logs
    ports:
      - "7848:7848"
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"

  nacos2:
    <<: *nacos-common
    hostname: nacos2
    container_name: nacos2
    volumes:
      - /data/nacos/cluster-logs/nacos2:/home/nacos/logs
    ports:
      - "7849:7848"
      - "8849:8848"
      - "9869:9848"
      - "9851:9849"

  nacos3:
    <<: *nacos-common
    hostname: nacos3
    container_name: nacos3
    volumes:
      - /data/nacos/cluster-logs/nacos3:/home/nacos/logs
    ports:
      - "7850:7848"
      - "8850:8848"
      - "9870:9848"
      - "9852:9849"

  mysql:
    container_name: mysql
    image: freemankevin/nacos-mysql:v8
    restart: unless-stopped
    env_file:
      - ./env/mysql.env
    volumes:
      - /data/nacos/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

  #nginx:
  #  image: nginx:1.25.3-alpine
  #  hostname: nginx
  #  container_name: nginx-nacos
  #  volumes:
  #    - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
  #    - /data/nacos/nginx/logs:/var/log/nginx:rw 
  #  ports:
  #    - "37848:7848"
  #    - "38848:8848"
  #    - "39848:9848"
  #    - "39849:9849"
  #  depends_on:
  #    - nacos1
  #    - nacos2
  #    - nacos3
  #  restart: unless-stopped
  #  healthcheck:
  #    test: ["CMD-SHELL", "curl -f --head --connect-timeout 5 http://localhost:8848/nacos || exit 1"]
  #    interval: 30s
  #    timeout: 10s
  #    retries: 3
  #    start_period: 40s
```

**Comment by freemankevin** [comment]
add nginx.

```shell
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  4096;
    multi_accept on;
    use epoll;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout  65;
    keepalive_requests 100;

    # Buffer size settings
    client_header_buffer_size 1k;
    large_client_header_buffers 4 4k;
    client_body_buffer_size  128k;

    # Timeouts
    client_body_timeout 12;
    client_header_timeout 12;
    send_timeout 10;

    # Gzip Settings
    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;


    # Upstream configuration for Nacos cluster
    upstream nacos {
        server nacos1:8848 weight=1 max_fails=2 fail_timeout=5s;
        server nacos2:18848 weight=1 max_fails=2 fail_timeout=5s;
        server nacos3:28848 weight=1 max_fails=2 fail_timeout=5s;
        keepalive 32; # Keep a pool of connections open to each upstream
    }


    # HTTP Server
    server {
        listen       8848;
        listen  [::]:8848;
        server_name  localhost;

        ignore_invalid_headers off;
        client_max_body_size 0;
        proxy_buffering off;
        proxy_request_buffering off;

        location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 300;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            chunked_transfer_encoding off;
            proxy_pass http://nacos;
        }
    }
    
}

stream {
    upstream nacos-grpc {
        server nacos1:9848 weight=1 max_fails=2 fail_timeout=5s;
        server nacos2:19848 weight=1 max_fails=2 fail_timeout=5s;
        server nacos3:29848 weight=1 max_fails=2 fail_timeout=5s;
    }

    server {
        listen 9848;
        listen [::]:9848;

        proxy_connect_timeout 1s;
        proxy_timeout 3s;
        proxy_pass nacos-grpc;
    }
}
```

latest yaml:
```yaml
version: "3.8"

x-nacos-common: &nacos-common
  image: nacos/nacos-server:${NACOS_VERSION}
  volumes:
    - ./conf/application.properties:/home/nacos/conf/application.properties
  env_file:
    - ./env/nacos-hostname.env
  restart: always
  depends_on:
    mysql:
      condition: service_healthy
  healthcheck:
    test: ["CMD-SHELL", "curl -f --head --connect-timeout 5 http://localhost:8848/nacos || exit 1"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 40s

services:
  nacos1:
    <<: *nacos-common
    hostname: nacos1
    container_name: nacos1
    volumes:
      - /data/nacos/cluster-logs/nacos1:/home/nacos/logs
    ports:
      - "7848:7848"
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"

  nacos2:
    <<: *nacos-common
    hostname: nacos2
    container_name: nacos2
    volumes:
      - /data/nacos/cluster-logs/nacos2:/home/nacos/logs
    ports:
      - "17848:7848"
      - "18848:8848"
      - "19848:9848"
      - "19849:9849"

  nacos3:
    <<: *nacos-common
    hostname: nacos3
    container_name: nacos3
    volumes:
      - /data/nacos/cluster-logs/nacos3:/home/nacos/logs
    ports:
      - "27848:7848"
      - "28848:8848"
      - "29848:9848"
      - "29849:9849"

  mysql:
    container_name: mysql
    image: freemankevin/nacos-mysql:v8
    restart: unless-stopped
    env_file:
      - ./env/mysql.env
    volumes:
      - /data/nacos/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

  nginx:
    image: nginx:1.25.3-alpine
    hostname: nginx
    container_name: nginx-nacos
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - /data/nacos/nginx/logs:/var/log/nginx:rw 
    ports:
      - "38848:8848"
      - "39848:9848"
    depends_on:
      - nacos1
      - nacos2
      - nacos3
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f --head --connect-timeout 5 http://localhost:8848/nacos || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
```
