### ISSUE TITLE
K8S环境部署nacos 1.4.2集群失败

### ISSUE THREAD

**Issue by Leon-pan** [alibaba/nacos#6342]
yaml文件
```
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  labels:
    app: nacos
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - port: 8848
      name: server
      targetPort: 8848
  clusterIP: None
  selector:
    app: nacos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
data:
  mysql.service.db.name: "nacos-mysql"
  mysql.service.host: "172.16.26.143"
  mysql.service.port: "3306"
#  mysql.slave.port: "3306"
  mysql.service.user: "root"
  mysql.service.password: "password"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
spec:
  serviceName: nacos-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos
              topologyKey: "kubernetes.io/hostname"
      #      serviceAccountName: nfs-client-provisioner
      initContainers:
        - name: peer-finder-plugin-install
          image: nacos/nacos-peer-finder-plugin:1.1
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/home/nacos/plugins/peer-finder"
              name: plugindir
      containers:
        - name: nacos
          imagePullPolicy: Always
          image: nacos/nacos-server:1.4.2
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8848
              name: client-port
          env:
            - name: NACOS_REPLICAS
              value: "3"
            - name: SERVICE_NAME
              value: "nacos-headless"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.service.host
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.service.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.service.port
#            - name: MYSQL_SLAVE_SERVICE_PORT
#              valueFrom:
#                configMapKeyRef:
#                  name: nacos-cm
#                  key: mysql.slave.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.service.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.service.password
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
          volumeMounts:
            - name: plugindir
              mountPath: /home/nacos/plugins/peer-finder
            - name: datadir
              mountPath: /home/nacos/data
            - name: logdir
              mountPath: /home/nacos/logs
      volumes:
        - name: plugindir
          persistentVolumeClaim:
            claimName: plugindir
        - name: datadir
          persistentVolumeClaim:
            claimName: datadir
        - name: logdir
          persistentVolumeClaim:
            claimName: logdir
  #  volumeClaimTemplates:
  #    - metadata:
  #        name: plugindir
  #        annotations:
  #          volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
  #      spec:
  #        accessModes: [ "ReadWriteMany" ]
  #        resources:
  #          requests:
  #            storage: 5Gi
  #    - metadata:
  #        name: datadir
  #        annotations:
  #          volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
  #      spec:
  #        accessModes: [ "ReadWriteMany" ]
  #        resources:
  #          requests:
  #            storage: 5Gi
  #    - metadata:
  #        name: logdir
  #        annotations:
  #          volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
  #      spec:
  #        accessModes: [ "ReadWriteMany" ]
  #        resources:
  #          requests:
  #            storage: 5Gi
  selector:
    matchLabels:
      app: nacos

```
