### ISSUE TITLE
使用nacos作为配置中心，并且开启了认证模式，自建一个logback-custom.xml日志配置文件.springboot启动是获取不到logback-custom.xml，提示403

### ISSUE THREAD

**Issue by jiangjun0130** [alibaba/nacos#6344]
nacos server开启认证（NACOS_AUTH_ENABLE=true ），集成了config之后，配置如下：
```
spring:
  application:
    name: app-name
  cloud:
    nacos:
      username: username
      password: pwd
      discovery:
        server-addr: nacos.nacos:8848
        namespace: test-name
      config:
        server-addr: nacos.nacos:8848
        namespace:test-name
        file-extension: yml
        shared-configs[0]:
          data-id: app-base.yml
          group: DEFAULT_GROUP
          refresh: true

logging:
  config: http://${spring.cloud.nacos.config.server-addr}/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=${spring.cloud.nacos.config.namespace}&dataId=logback-custom.xml
```
启动之后提示获取不到logback-custom.xml，日志如下：
Error opening logging config file http://nacos.nacos:8848/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=xxx&dataId=logback-custom.xml

Server returned HTTP response code: 403 for URL: http://nacos.nacos:8848/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=xxx&dataId=logback-custom.xml

尝试过在url上手动加上accessToken参数就能获取到，但是在yml中怎么配置logging.config的url中加上accessToken呢？
