### ISSUE TITLE
nacos 2.0.2 docker cluster Data Inconsistent.数据不一致问题.

### ISSUE THREAD

**Issue by moyu-jun** [alibaba/nacos#6514]
**Describe the bug**

I deployed Nacos 2.0.2 cluster on three physical machines using docker. Then I registered a number of services. 

Then I manually shut down one of the Nacos and restart it. However, when I looked at the `naming-server.log` of this Nacos, I found that double write still needs to be turned off, so I requested to turn off the double write API. The log shows success. 

But I still use  `nacos/v1/ns/upgrade/ops/metrics`  API views information on three physical machines.However, the data of this newly launched Nacos is inconsistent with that of other Nacos.Moreover, when I query the service list on the console, I have a chance to query the empty service list (in fact, there are services).

我在三台物理机上使用 docker 部署了 nacos 2.0.2 集群，然后注册了一些服务。
然后我手动关闭了其中一台 nacos 并重启了它。当然选举成功后，我查看了这台 nacos 的 `naming-server.log` 日志。发现双写需要关闭，所以我请求了关闭双写的接口，日志显示关闭成功。
但是当我使用 `nacos/v1/ns/upgrade/ops/metrics` 接口查看信息时发现新启动的 nacos 的数据和其他的不同。而且我在控制台查询服务列表，有几率查询到空的服务列表（其实是有服务的）。

**Correct data**
![](https://cdn.jsdelivr.net/gh/moyu-jun/resource/img/20210731113453.png)

**Abnormal data**
![](https://cdn.jsdelivr.net/gh/moyu-jun/resource/img/20210731113452.png)

**Expected behavior**
Data consistency.

**Acutally behavior**
Data Inconsistent.

**How to Reproduce**
1. deployed Nacos 2.0.2 cluster on three physical machines using docker.
2. turn off the double write.
3. registered a number of services on multiple namaspace.
4. manually shut down one of the Nacos and restart it.
5. turn off the double write on this nacos.
6. requested to `nacos/v1/ns/upgrade/ops/metrics` API on three physical machines.
7. See Data Inconsistent.

**Desktop (please complete the following information):**
 - OS: Centos 7.9
 - Version: Nacos server 2.0.2
 - Docker: 20.10.7
 - Docker Compose: 1.29.2
 - Nacos DataSource: MySQL

**Comment by realJackSun** [comment]
排查一下网络是否畅通

**Comment by moyu-jun** [comment]
> 排查一下数据不一致的机器网络是否畅通

网络是通的，刚开始是部署好的集群模式，可以正常使用，后面手动关闭了其中一台，然后再启动之后出现的问题。

**Comment by moyu-jun** [comment]
> 排查一下数据不一致的机器网络是否畅通

这是我部署使用的 `docker-compose` 文件

```yaml
version: "3"
services:
  nacos:
    image: nacos/nacos-server:2.0.2
    container_name: nacos
    volumes:
      - ./logs:/home/nacos/logs
      - ./config/custom.properties:/home/nacos/init.d/custom.properties
    environment:
      - "NACOS_SERVERS=172.16.211.155:15000 172.16.211.156:15000 172.16.211.153:15000"
      - "NACOS_SERVER_IP=172.16.211.153"
      - "NACOS_APPLICATION_PORT=15000"
      - "SPRING_DATASOURCE_PLATFORM=mysql"
      - "MYSQL_SERVICE_HOST=remote_mysql_ip"
      - "MYSQL_SERVICE_PORT=3306"
      - "MYSQL_SERVICE_DB_NAME=nacos"
      - "MYSQL_SERVICE_USER=username"
      - "MYSQL_SERVICE_PASSWORD=password"
      - "NACOS_AUTH_ENABLE=true"
      - "JVM_XMS=2g"
      - "JVM_XMX=2g"
      - "JVM_XMN=1g"
    ports:
      - 14000:14000
      - 15000:15000
      - 16000:16000
      - 16001:16001
    restart: always
```
