### ISSUE TITLE
heart-beat-interval:在nacos的在线配置里设置了, 但是感觉没生效,还是要等10秒, 每次写完代码重启服务都要等10秒nacos才识别到微服务

### ISSUE THREAD

**Issue by gclsoft** [alibaba/nacos#6552]
```
spring:
  cloud:
    nacos:
      discovery:
        heart-beat-interval: 300
        heart-beat-timeout: 60000
```
这个在nacos的在线配置里设置了, 但是感觉没生效,还是要等10秒, 每次写完代码重启服务都要等10秒nacos才识别到微服务

Wait every 10 seconds after restart micro server, how to make it no wait
