### ISSUE TITLE
nacos 可以读取配置文件但是无法注册进去

### ISSUE THREAD

**Issue by JingYueZheng** [alibaba/nacos#6624]
bootstrap.yml 配置如下
```
 server:
  port: 8001

spring:
  application:
    name: shop-order
  profiles:
    active: dev

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.178:8848
        namespace: dev
        register-enabled: true
      config:
        namespace: dev
        file-extension: yml
        refresh-enabled: true
        shared-configs:
          - dataId: mybatis-plus.yml
            refresh: true
```
版本如下
![image](https://user-images.githubusercontent.com/46444566/128984595-06584888-4097-46a5-8279-57738b4bf1ac.png)

nacos如下：
![image](https://user-images.githubusercontent.com/46444566/128985019-f238e133-9c5e-458e-9930-95f6d306c09c.png)
