### ISSUE TITLE
nacos.core.auth.enabled=true nacos开启鉴权，sentinel网关流控监控面板空白

### ISSUE THREAD

**Issue by jsercom** [alibaba/nacos#6682]
```
    cloud:
    sentinel:
      filter:
        enabled: true # Sentinel 网关流控默认的粒度是 route 维度以及自定义 API 分组维度，默认不支持 URL 粒度。
      transport:
        dashboard: 127.0.0.1:8080
      datasource:
        ds1:
          nacos:
            username: nacos
            password: nacos910
            data-type: json
            rule-type: gw-flow # 网关流控
            server-addr: 127.0.0.1:8848
            data-id: iJudge-sentinel
            namespace: 87008ba1-cd19-4164-b5f6-bbe3e14265cb
            group-id: DEFAULT_GROUP
    nacos:
      username: nacos
      password: nacos910
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          name: gateway
        namespace: 87008ba1-cd19-4164-b5f6-bbe3e14265cb
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        namespace: 87008ba1-cd19-4164-b5f6-bbe3e14265cb
```

nacos增加鉴权后
sentinel 配置的网关流控监控不到了 

nacos 1.4.1
sentinel 1.8.0
