### ISSUE TITLE
nacos + gateway + loadbalancer After specifying the namespace and group of nacos, it will prompt "no servers available for service"

### ISSUE THREAD

**Issue by ozygod** [alibaba/nacos#6750]
**Describe the bug**
指定namespace和group后，通过网关请求服务会提示：no servers available for service，配置如下：
```
spring:
  application:
    name: xxl-auth
  main:
    allow-bean-definition-overriding: true
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    nacos:
      discovery:
        server-addr: ${REGISTER_HOST:localhost}:${REGISTER_PORT:8848}
        namespace: ${REGISTER_NAMESPACE:0313b22f-e389-47d4-8f70-5796d4143e8e}
        group: AUTH_GROUP
      config:
        server-addr: ${REGISTER_HOST:localhost}:${REGISTER_PORT:8848}
        file-extension: yml
        namespace: ${REGISTER_NAMESPACE:0313b22f-e389-47d4-8f70-5796d4143e8e}
        group: AUTH_GROUP
```

当去掉namespace后，问题消失
```
spring:
  application:
    name: xxl-auth
  main:
    allow-bean-definition-overriding: true
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    nacos:
      discovery:
        server-addr: ${REGISTER_HOST:localhost}:${REGISTER_PORT:8848}
      config:
        server-addr: ${REGISTER_HOST:localhost}:${REGISTER_PORT:8848}
        file-extension: yml
```
**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: Win10
 - Version SpringCloud 2020.0.3, SpringCloud Alibaba 2021.1 nacos 2.0.2
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
