### ISSUE TITLE
似乎需要等待Nacos选举完成才能正常连接，在K8S中如何知道什么时候选举完成？

### ISSUE THREAD

**Issue by bigfacewo** [alibaba/nacos#6813]
**Describe the bug**
我的服务依赖于nacos，所以必须等待nacos启动完成才启动当前服务，我在K8S资源清单中定义initContainers:
```
  initContainers:
  - name: wait-nacos
    image: busybox:1.28
    command:
    - sh
    - -c
    - 'while true;do echo "Waiting for nacos to come up...";wget http://nacos-headless.default.svc.cluster.local:8848/nacos -q -T 1 -O /dev/null >/dev/null 2>/dev/null && break; sleep 1;done; sleep 30; echo "Nacos is up!"'
```
但是经常会报这样的错误：
```

com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance/list after all servers([nacos-headless.default.svc.cluster.local:8848]) tried: ErrCode:503, ErrMsg:server is DOWNnow, detailed error message: Optional[Distro protocol is not initialized]

```
但是等待一会儿重启我的服务是可以正常连接的，所以我在检查nacos是否准备好的脚本后面加入了一段休眠了30s的代码，但是他仍然有同样的问题，似乎领导选举花费的时间超过了30s。

我想知道有什么好的办法通过HTTP请求知道领导选举完成这一事件，以在合适的时间点启动我的其他服务。

**Expected behavior**
启动nacos后，其他服务能正常连接。

**Acutally behavior**
启动nacos后，其他服务不能正常连接。

**Desktop (please complete the following information):**
 - OS: docker, imagebase: java
 - Version nacos-server 2.0.3 nacos-client 1.4.1
 - SDK spring-cloud-starter-alibaba-nacos-discovery 2.2.5.RELEASE
