### ISSUE TITLE
Configuration Center, does it support yml writing?

### ISSUE THREAD

**Issue by qq12157138** [alibaba/nacos#708]
如下面这样：
```
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: host_route
        uri: lb://bs-aa-service
        predicates:
        - Path=/aa/**
        filters:
        - Post
        - Pre
        - StripPrefix=1
        - name: Retry
          args:
            retries: 3          
            status: 404         
            statusSeries: 500   
            method: GET        
```

因为properties文件数组类型写法不是很直观，比较喜欢yml的写法

**Comment by qq12157138** [comment]
```
spring:
  cloud:
    nacos:
      config:
        file-extension: yml
```
