### ISSUE TITLE
Nacos客户端不停的打印config changed，初步怀疑是服务端返回了旧版本配置

### ISSUE THREAD

**Issue by FrankChen021** [alibaba/nacos#7246]
版本：1.4.1

有很多类似的问题反馈：#2684，#3211，#6642

现象：在nacos控制台修改配置后，client间隔30s疯狂不停的打印config changed。

与上述不同的是：
1. 已经升级到1.3以上版本，因此排除MD5值client和server计算不同的问题。
2. 项目中配置了namespace，因此排除是配置namespace为public的问题

简单定位后发现，客户端请求server端的`/nacos/v1/cs/configs?dataId=XXX&group=DEFAULT_GROUP&tenant=XXX`接口后，该接口返回的数据不一致。

```bash
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 
< Server: SGW
< Date: Wed, 17 Nov 2021 04:16:06 GMT
< Content-Type: text/plain;charset=UTF-8
< Content-Length: 4492
< Connection: keep-alive
< Vary: Accept-Encoding
< Config-Type: yaml
< Content-MD5: d8356ad9163aa3a28c4986dae7b30032
< Pragma: no-cache
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Cache-Control: no-cache,no-store
< Last-Modified: Wed, 17 Nov 2021 02:43:38 GMT
```

再次执行后返回的MD5跳变

```
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 
< Server: SGW
< Date: Wed, 17 Nov 2021 04:16:49 GMT
< Content-Type: text/plain;charset=UTF-8
< Content-Length: 4493
< Connection: keep-alive
< Vary: Accept-Encoding
< Config-Type: yaml
< Content-MD5: b2259c7abbf4dcf5a835533748169110
< Pragma: no-cache
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Cache-Control: no-cache,no-store
< Last-Modified: Wed, 17 Nov 2021 04:07:50 GMT
```

第一个MD5是一个历史版本的配置；后一个返回的MD5是最新版本的MD5。当然并不是总是按上述顺序返回。有时前几次请求都是返回新版本的配置，然后又返回一个旧版本配置。

目前怀疑是server返回了不同版本的配置，导致客户端有时拿到的是旧版本的配置，进而导致不停的请求server端刷新。

**Comment by FrankChen021** [comment]
此问题导致根本无法使用Nacos作为配置中心，还请各位大佬协助。

**Comment by onewe** [comment]
@FrankChen021 服务端版本是多少?

**Comment by onewe** [comment]
@FrankChen021 能提供详细的配置信息吗?

**Comment by FrankChen021** [comment]
> @FrankChen021 服务端版本是多少?

1.4.1

**Comment by FrankChen021** [comment]
> @FrankChen021 能提供详细的配置信息吗?

具体是指什么配置？

**Comment by onewe** [comment]
@FrankChen021 客户端的配置,我看我这边能不能按照你描述复现一下.

**Comment by FrankChen021** [comment]
> @FrankChen021 客户端的配置,我看我这边能不能按照你描述复现一下.

```yaml
spring:
  application:
    name: gateway
  cloud:
    nacos:
      config:
        file-extension: yaml
        server-addr: nacos:80
        namespace: ed648b6e-d350-4755-ab1a-28721fc79cfa
        refresh-enabled: true
        group: DEFAULT_GROUP
```

**Comment by onewe** [comment]
@FrankChen021 
```
相关依赖版本:
spring-boot-starter-parent: 2.4.2
spring-cloud-alibaba-dependencies: 2021.1
spring-cloud-dependencies: 2020.0.2
nacos-client: 1.4.1
```

bootstrap.yaml
```yaml
server:
  port: 8081
spring:
  application:
    name: gateway
  cloud:
    nacos:
      config:
        file-extension: yaml
        server-addr: 127.0.0.1:8848
        namespace: 5dc92bfc-34be-48a6-a68e-7408dcba1d22
        refresh-enabled: true
        group: DEFAULT_GROUP
```

nacos-server: 1.4.1

我没有复现你说的问题,是我的配置跟你有差异吗?
