### ISSUE TITLE
Yaml parsed

### ISSUE THREAD

**Issue by JasonFCN** [alibaba/nacos#7423]
#### Safely parse the configuration information entered by the user

The configuration information entered by the user should be parsed safely. Rather than intentionally or unintentionally without any prompts.

Example:

```yaml
service:
  a:
    url: www.xxx.com
service:
  b:
    name: b
```

==The configuration information should not be released due to format issues. But now Nacos allows this to happen.==
