### ISSUE TITLE
nacos yaml类型配置context-path失效问题

### ISSUE THREAD

**Issue by 501956430** [alibaba/nacos#7857]
nacos-server:2.0.2
springboot2.0版以上
项目中使用依赖版本：nacos-config-spring-boot-starter:0.2.10

在远程yaml类型文件配置:
```
server:
  servlet:
    context-path: /demo
  port: 8089
#或
spring:
  mvc:
    servlet:
      path: /demo
```
两种方式的配置都尝试，结果都失效仅端口配置有效，但在项目本地appliection.yaml中配置都正常，旧项目使用Properties类型文件配置都正常。

**Comment by realJackSun** [comment]
spring boot 是哪个版本的？怎样配置的？

**Comment by 501956430** [comment]
@realJackSun spring boot  2.3.12.RELEASE

```
spring:
  application:
    name: demo
  profiles:
    active: dev

#这段配置放nacos远程配置中
server:
  servlet:
    context-path: /demo

nacos:
  config:
    bootstrap:
      enable: true
    auto-refresh: true
    server-addr: nacos.xxx.cn
    data-id: ${spring.application.name}
    namespace: ${spring.profiles.active}
    group: DEFAULT_GROUP
    username: xxx
    password: xxx
    config-long-poll-timeout: 46000
    config-retry-time: 2333
    type: yaml
    context-path: ${server.servlet.context-path}/actuator
```
