### ISSUE TITLE
修改redis或数据库连接串后，没有动态更新配置；No dynamic configuration updates after redis or database connection string changes

### ISSUE THREAD

**Issue by lvhejin** [alibaba/nacos#8026]
After modifying the redis or database connection string, the configuration is not dynamically updated

step:
1. Configure the correct connection string in nacos
2. Start the service (spring boot)
3. The access interface redis reads and writes normally
4. Modify the IP address in the connection string in nacos to a wrong IP
5. Access the interface and find that you can read and write redis data normally (at this time, you should not be able to read and write redis data)

nacos config：
```
# spring config
spring: 
  redis:
    host:  127.0.0.1
    port: 6379
    password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
```

java code：
```
package io.soundsright.lyrra.controller;

import io.soundsright.common.redis.service.RedisService;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.cloud.context.config.annotation.RefreshScope;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDateTime;
import java.util.concurrent.TimeUnit;

 
@RestController
@RefreshScope
@RequestMapping("/system")
public class SystemController {

    private final RedisService redis;

    public SystemController(RedisService redis) {
        this.redis = redis;
    }

    @Value("${spring.redis.host}")
    private String redisHost;

    @GetMapping("/hello")
    public String hello(){
        redis.setCacheObject("admin","dk-"+ LocalDateTime.now(),5L, TimeUnit.MINUTES);
        String admin = redis.getCacheObject("admin");
        return "hello,redisHost:"+redisHost+";admin:"+admin;
    }

}
```
