### ISSUE TITLE
does nameservice support namespace?

### ISSUE THREAD

**Issue by kaybinwong** [alibaba/nacos#806]
namespace not working with nacos 0.8. Naming service support namespace?
```
spring:
  cloud:
    nacos:
      config:
        prefix: urm
        server-addr: svc-center.xx.cc:80
        file-extension: yaml
        namespace: 61130b18-3967-4862-9919-04b5697f19eb
      discovery:
        server-addr: svc-center.xx.cc:80
        namespace: 61130b18-3967-4862-9919-04b5697f19eb
  application:
    name: urm-restapi
```
