### ISSUE TITLE
nacos-server 2.0.3，2.0.4 出现 no datasource set

### ISSUE THREAD

**Issue by leilei0220** [alibaba/nacos#8106]
nacos-server 2.0.3，2.0.4 出现 no datasource set(已确定连接与数据库脚本初始化正确），需要重启数据库才能解决

mysql数据库版本 5.7.30

**Comment by Oliverwqcwrw** [comment]
The nacos don't report 'no datasource set' although do not set the 'mysql'

**Comment by KomachiSion** [comment]
那肯定是配置有问题，或者数据库有问题无法链接导致的，建议排查环境和配置，还无法解决建议提供更过报错和日志信息。

**Comment by HeyChiang** [comment]
> 那肯定是配置有问题，或者数据库有问题无法链接导致的，建议排查环境和配置，还无法解决建议提供更过报错和日志信息。

我遇到了同样的问题，无论我如何尝试都是no datasource set。请求官网制作人员把问题更加具体的抛出，而不是一个no datasource set，这样更方便于其他程序员排查问题
`
docker run -e PREFER_HOST_MODE=hostname  -e MODE=standalone -e SPRING_DATASOURCE_PLATFORM=mysql -e MYSQL_MASTER_SERVICE_HOST=192.168.xxx.xxx -e MYSQL_MASTER_SERVICE_PORT=3306 -e MYSQL_MASTER_SERVICE_USER=root -e MYSQL_MASTER_SERVICE_PASSWORD="test-2021" -e MYSQL_MASTER_SERVICE_DB_NAME=nacos_devtest -e MYSQL_SERVICE_DB_PARAM="characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&serverTimezone=UTC" --name nacos -p 8848:8848 --restart=always nacos/nacos-server:v2.0.4
`

**Comment by HeyChiang** [comment]
我又拿docker反复试了几个小时，确保命令是正确的，今天就是天皇老子过来，也是docker设置外部mysql储存有问题！！！

**Comment by onewe** [comment]
我也拿docker 试了一下没有复现这个问题
docker-compose.yaml
```yaml
version: "2"
services:
  nacos:
    image: nacos/nacos-server:v2.0.4
    container_name: nacos-standalone-mysql
    env_file:
      - ./nacos-standlone-mysql.env
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: on-failure
  
  mysql:
    container_name: mysql
    image: mysql:5.7
    env_file:
      - ./mysql.env
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
```

mysql.env
```env
MYSQL_ROOT_PASSWORD=root
MYSQL_DATABASE=nacos_devtest
MYSQL_USER=nacos
MYSQL_PASSWORD=nacos
```

nacos-standlone-mysql.env
```env
PREFER_HOST_MODE=hostname
MODE=standalone
SPRING_DATASOURCE_PLATFORM=mysql
MYSQL_SERVICE_HOST=mysql
MYSQL_SERVICE_DB_NAME=nacos_devtest
MYSQL_SERVICE_PORT=3306
MYSQL_SERVICE_USER=nacos
MYSQL_SERVICE_PASSWORD=nacos
MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
```

在`docker-entrypoint-initdb.d`目录下放入了nacos-2.0.4中的`nacos-mysql.sql`文件,作初始化数据库使用.

@HeyChiang
