### ISSUE TITLE
Unable to get configuration When manually setting the namespace default to public

### ISSUE THREAD

**Issue by myifeng** [alibaba/nacos#8211]
**Describe the bug**

If I don't set the `NACOS_NAMESPACE` environment variable, I can't get the configuration.

I have the same problem even if I change `public` to `""`

But it works when i don't set the value of namespace or the value is not `public`,

```
spring:
  application:
    name: demo
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER_ADDR:http://10.20.19.166:8848}
        file-extension: ${NACOS_FILE_EXTENSION:yaml}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        namespace: ${NACOS_NAMESPACE:public}
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:http://10.20.19.166:8848}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        namespace: ${NACOS_NAMESPACE:public}
```

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [nacos-server 2.0.2, nacos-client 2.0.2]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
