### ISSUE TITLE
springboot整合nacos做配置中心，使用@NacosConfigurationProperties注解注入bean属性，当nacos客户端没有配置这个bean的属性，项目代码本地文件application.yml配置了，此时bean的属性并没有注入进来

### ISSUE THREAD

**Issue by ShepherdZFJ** [alibaba/nacos#8226]
问题示例如下：

nacos客户端：没有配置要注入的bean属性

![](https://markdown-file-zfj.oss-cn-hangzhou.aliyuncs.com/nacostest)

代码如下：

项目代码本地配置application.yml配置：

```yaml
nacos:
  config:
    server-addr: 127.0.0.1:8848
    namespace: 6de43a50-61da-426a-9b2c-df474034c13d
    type: properties
    data-id: example.properties

user1:
  name: shepherd-local
  age: 18
  id: 127
```

注入如下：

```java
@Data
@Component
@NacosConfigurationProperties(prefix = "user1", autoRefreshed = true, dataId = "example.properties")
//@ConfigurationProperties(prefix = "user1")
public class User {
    private String name;
    private Integer age;
    private Long id;
}
```

启动项目，查看user bean对象属性并没有注入成功。。。。。。
