### ISSUE TITLE
2.1.0 关于多环境配置文件的诡异现象

### ISSUE THREAD

**Issue by pkaq** [alibaba/nacos#8376]
最新版本的spring cloud 已经将 spring.profiles.active标记废弃,推荐了新的配置方式 ,然鹅 采用新的方式 放到bootstrap.yaml里 启动的时候nacos总会去找 localhost:8848 放到 application.yaml里会直接导致本地application.yaml中的所有配置被无视
而采用标记启用的老方式则没有任何问题
```yaml
spring:
  config:
    activate:
      on-profile: dev
```
