### ISSUE TITLE
Spring Boot 2.4及以上版本 spring.profiles已经过时 Spring Boot 2.4 and later spring.profiles is outdated

### ISSUE THREAD

**Issue by dixtdf** [alibaba/nacos#8662]
**Describe the bug**
Spring Boot 2.4及以上版本 spring.profiles已经过时

**Actually behavior**
我想通过spring.profiles配置dataid就像${prefix}-${spring.profiles.active}.${file-extension}，但是spring.profile已经过时了
我的版本
    <properties>
        <java.version>1.8</java.version>
        <spring-boot.version>2.7.1</spring-boot.version>
        <spring-cloud.version>2021.0.3</spring-cloud.version>
        <alibaba-cloud.version>2021.0.1.0</alibaba-cloud.version>
        <nacos.version>2.1.0</nacos.version>
    </properties>

**Additional context**
现在我不想配置spring.profiles 我目前通过 spring.config配置active，有什么替代方式

**Describe the bug**
Spring Boot 2.4 and later spring.profiles is outdated
**Actually behavior**
I wanted to configure dataid with spring.profiles like ${prefix}-${spring.profiles.active}.${file-extension}, but spring.profile is out of date
My version
    <properties>
        <java.version>1.8</java.version>
        <spring-boot.version>2.7.1</spring-boot.version>
        <spring-cloud.version>2021.0.3</spring-cloud.version>
        <alibaba-cloud.version>2021.0.1.0</alibaba-cloud.version>
        <nacos.version>2.1.0</nacos.version>
    </properties>
**Additional context**
Right now I don't want to configure spring.profiles I currently configure active through spring.config, what is the alternative

**Comment by YunWZ** [comment]
> Config your `application.yml` or `application.properties`:
> 
> ```yaml
> server:
>   port: 8888
> spring:
>   application:
>     name: nacos-config-import-example
>   cloud:
>     nacos:
>       config:
>         group: DEFAULT_GROUP
>         server-addr: 127.0.0.1:8848
>   config:
>     import:
>       - nacos:test.yml
>       - optional:nacos:test01.yml?group=group_02
>       - optional:nacos:test02.yml?group=group_03&refreshEnabled=false
> ```
> 
> As above, you could add *optional:` before nacos config file if that is an optional file.

Of cause, you could config default `prefix`, `fileExtension` and so on as default value, like below:
```yaml
spring:
  application:
    name: nacos-config-import-example
  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
        prefix: xx # the default value is ${spring.application.name}
        file-extension: properties # default value
```

**Comment by dixtdf** [comment]
The configuration is invalid in application.yml, so I try to put it in bootstrap.yml
The actual import is not loaded in the ideal state

```
bootstrap.yml

spring:
  application:
    name: demo-web
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: ${spring.application.name}
        namespace: f7cf501d-b632-4370-ba1e-f8d13c98950d
        group: @profiles.active@
        metadata:
          user.name: "admin"
          user.password: "123456"
      config:
        server-addr: 127.0.0.1:8848
        # prefix: 文件名前缀，默认是spring.application.name
        # 如果没有指定命令空间，则默认命令空间为PUBLIC
        namespace: f7cf501d-b632-4370-ba1e-f8d13c98950d
        # 如果没有配置Group，则默认值为DEFAULT_GROUP
        group: @profiles.active@
        #指定yaml格式的配置
        file-extension: yaml
        # 从Nacos读取配置项的超时时间
        timeout: 5000
        # 长轮询超时时间
        config-long-poll-timeout: 10000
        # 轮询的重试时间
        config-retry-time: 2000
        # 长轮询最大重试次数
        max-retry: 3
        # 开启监听和自动刷新
        refresh-enabled: true
    import:
      - optional:nacos:application-@profiles.active@.yaml
      - optional:nacos:${spring.application.name}-@profiles.active@.yaml?group=@profiles.active@&refreshEnabled=true

pom.xml
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
    </dependencies>
```
![image](https://user-images.githubusercontent.com/106577535/176809342-29c70de7-fadf-4f49-9717-78efc291bbd8.png)
![image](https://user-images.githubusercontent.com/106577535/176809512-df1a3972-b250-498f-84a3-5e7ab6807d02.png)
![image](https://user-images.githubusercontent.com/106577535/176809488-9eb6d93a-7c9c-4118-a90c-897866be1515.png)

**Comment by YunWZ** [comment]
The `import` property full name is `spring.config.import` instead of `spring.cloud.import`

**Comment by dixtdf** [comment]
哈哈哈 好低级的错误 不过又出现了新的问题 没法指定 namespace 这样是不生效的😅
```
spring:
  application:
    name: demo-web
  config:
    import:
      - optional:nacos:application-@profiles.active@.yaml
      - optional:nacos:${spring.application.name}-@profiles.active@.yaml?namespace=f7cf501d-b632-4370-ba1e-f8d13c98950d&group=@profiles.active@&refreshEnabled=true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: ${spring.application.name}
        namespace: f7cf501d-b632-4370-ba1e-f8d13c98950d
        group: @profiles.active@
      config:
        server-addr: 127.0.0.1:8848
        namespace: f7cf501d-b632-4370-ba1e-f8d13c98950d
```
