### ISSUE TITLE
k8s 搭建，配置了多个节点，选举时只有一个节点。

### ISSUE THREAD

**Issue by min1854** [alibaba/nacos#8823]
**Describe the bug**

~~~
nacos.log
[root@nacos-cluster-statefulset-2 nacos]# more  logs/nacos.log 
2022-07-28 14:50:07,658 INFO The server IP list of Nacos is [nacos-cluster-statefulset-0.nacos-cluster-service.default.svc.cluster.local:8848, nacos-cluster-statefulset-1.nacos-cluster
-service.default.svc.cluster.local:8848, nacos-cluster-statefulset-2.nacos-cluster-service.default.svc.cluster.local:8848]

2022-07-28 14:50:07,722 INFO Starting Nacos v1.4.1 on nacos-cluster-statefulset-2.nacos-cluster-statefulset-service.default.svc.cluster.local with PID 19 (/home/nacos/target/nacos-serv
er.jar started by root in /home/nacos)

2022-07-28 14:50:07,723 INFO No active profile set, falling back to default profiles: default
~~~

naming-raft.log 
~~~
[root@nacos-cluster-statefulset-2 nacos]# more  logs/naming-raft.log 
2022-07-28 14:50:42,586 INFO raft peers changed: [Member{ip='192.168.8.148', port=8848, state=UP, extendInfo={raftPort=7848, version=1.4.1}}]

2022-07-28 14:50:42,785 INFO initializing Raft sub-system

2022-07-28 14:50:42,787 INFO finish loading all datums, size: 0 cost 0 ms.

2022-07-28 14:50:42,791 INFO cache loaded, datum count: 0, current term: 0

2022-07-28 14:50:42,798 INFO finish to load data from disk, cost: 12 ms.

2022-07-28 14:50:42,834 INFO timer started: leader timeout ms: 15000, heart-beat timeout ms: 5000

2022-07-28 14:50:47,496 WARN start to close old raft protocol!!!

2022-07-28 14:50:47,498 WARN stop old raft protocol task for notifier

2022-07-28 14:50:47,501 WARN stop old raft protocol task for master task

2022-07-28 14:50:47,502 WARN stop old raft protocol task for heartbeat task
~~~

请求节点列表，显示服务端错误，但可以进入页面访问显示正常，但只有一个节点。
`
[root@nacos-cluster-statefulset-2 nacos]# curl -X GET '127.0.0.1:8848/nacos/v1/ns/operator/servers'
server is DOWN now, please try again later!
`

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
configmap
```yml
apiVersion: v1
kind: ConfigMap
metadata:
  # 不能有大写字母
  name: nacos-cluster-configmap
data:
  # 这里是不用写 - 号的，他是个 map 。。。。。map 是这个意思吗。。。。
  JVM_XMS: 512M
  JVM_XMX: 512M
  JVM_XMN: 512M
  JVM_MMS: 512M



  MYSQL_SERVICE_DB_NAME: nacos
  MYSQL_SERVICE_USER: root
  MYSQL_SERVICE_PASSWORD: root
  MYSQL_SERVICE_HOST: mysql-nacos-connect-service # statefulSet 可以通过 serviceName 进行访问
  MYSQL_SERVICE_PORT: "3306"
  SPRING_DATASOURCE_PLATFORM: mysql

  # 纯数字需要双引号
  NACOS_APPLICATION_PORT: "8848"
  # `statefuleSet.metadata.name` + `-` + 从 0 开始的编号 + `.` + `service.metadata.name` +  `.default.svc.cluster.local` + `:` + 端口号
  # nacos-0.nacos-headless.default.svc.cluster.local:8848
  # 这种情况每次都是单一个节点，并不报错
#  NACOS_SERVERS: nacos-cluster-statefulset-0.nacos-cluster-service.default.svc.cluster.local:8848 nacos-cluster-statefulset-1.nacos-cluster-service.default.svc.cluster.local:8848 nacos-cluster-statefulset-2.nacos-cluster-service.default.svc.cluster.local:8848
#  NACOS_SERVERS: nacos-cluster-statefulset-0:8848 nacos-cluster-statefulset-1:8848 nacos-cluster-statefulset-2:8848
  NACOS_SERVERS: "nacos-cluster-statefulset-0.nacos-cluster-service.default.svc.cluster.local:8848 nacos-cluster-statefulset-1.nacos-cluster-service.default.svc.cluster.local:8848 nacos-cluster-statefulset-2.nacos-cluster-service.default.svc.cluster.local:8848"

  PREFER_HOST_MODE: hostname
  #NACOS_SERVER_IP: ${HOSTNAME}
```

service
```yml
apiVersion: v1
kind: Service
metadata:
  name: nacos-cluster-service
spec:
  type: ClusterIP
  ports:
    - port: 8848
      name: nacos-port
      targetPort: 8848
    - port: 7848
      name: raft-port
      targetPort: 7848
    - port: 9848
      name: client-rpc
      targetPort: 9848
    - port: 9849
      name: raft-rpc
      targetPort: 9849
  selector:
    app: nacos-cluster
```

statefulSet
```yml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  # 不能有大写字母
  name: nacos-cluster-statefulset
spec:
  selector:
    matchLabels:
      app: nacos-cluster
  replicas: 3
  # 不能有大写字母
  serviceName: nacos-cluster-statefulset-service
  template:
    metadata:
      labels:
        app: nacos-cluster
    spec:
      containers:
        - name: nacos
          image: nacos/nacos-server:1.4.1
          imagePullPolicy: IfNotPresent
          env:
            - name: JVM_XMS
              valueFrom:
                configMapKeyRef:
                  name: nacos-cluster-configmap
                  key: JVM_XMS
            - name: JVM_XMX
              valueFrom:
                configMapKeyRef:
                  name: nacos-cluster-configmap
                  key: JVM_XMX
            - name: JVM_XMN
              valueFrom:
                configMapKeyRef:
                  name: nacos-cluster-configmap
                  key: JVM_XMN
            - name: JVM_MMS
              valueFrom:
                configMapKeyRef:
                  name: nacos-cluster-configmap
                  key: JVM_MMS

            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cluster-configmap
                  key: MYSQL_SERVICE_DB_NAME
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cluster-configmap
                  key: MYSQL_SERVICE_USER
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cluster-configmap
                  key: MYSQL_SERVICE_PASSWORD
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-cluster-configmap
                  key: MYSQL_SERVICE_HOST
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cluster-configmap
                  key: MYSQL_SERVICE_PORT
            - name: SPRING_DATASOURCE_PLATFORM
              valueFrom:
                configMapKeyRef:
                  name: nacos-cluster-configmap
                  key: MYSQL_SERVICE_PORT



            
            - name: NACOS_APPLICATION_PORT
              valueFrom:
                configMapKeyRef:
                  key: NACOS_APPLICATION_PORT
                  name: nacos-cluster-configmap
            - name: PREFER_HOST_MODE
              valueFrom:
                configMapKeyRef:
                  key: PREFER_HOST_MODE
                  name: nacos-cluster-configmap
            - name: NACOS_SERVER_IP
              valueFrom:
                # 获取 pod 的 ip
                fieldRef:
                  fieldPath: status.podIP
            - name: NACOS_SERVERS
              valueFrom:
                configMapKeyRef:
                  key: NACOS_SERVERS
                  name: nacos-cluster-configmap
          ports:
            - containerPort: 8848
              name: nacos-port
            - containerPort: 7848
              name: raft-port
            - containerPort: 9848
              name: client-rpc
            - containerPort: 9849
              name: raft-rpc

          volumeMounts:
            - mountPath: /home/nacos/logs
              name: nacos-logs
            - mountPath: /etc/timezone
              name: timezone
            - mountPath: /etc/localtime
              name: localtime
      
      
      volumes:
        - name: nacos-logs
          emptyDir: {}
        - name: timezone
          hostPath:
            path: /etc/timezone
        - name: localtime
          hostPath:
            path: /etc/localtime


```

**Desktop (please complete the following information):**
- k8s版本 v1.19.4
- nacos 版本 v1.4.1

**Additional context**

**Comment by KomachiSion** [comment]
如果需要使用域名作为服务端节点，需要开启nacos的域名模式。

nacos.inetutils.prefer-hostname-over-ip=true

nacos-k8s中有对应的example

**Comment by min1854** [comment]
> 如果需要使用域名作为服务端节点，需要开启nacos的域名模式。
> 
> nacos.inetutils.prefer-hostname-over-ip=true
> 
> nacos-k8s中有对应的示例

我在 cluster.conf 中加入了 。配置变成如下。
```
[root@nacos-cluster-statefulset-0 nacos]# cat conf/cluster.conf 
nacos.inetutils.prefer-hostname-over-ip=true
nacos-cluster-statefulset-0.nacos-cluster-statefulset-service.default.svc.cluster.local
nacos-cluster-statefulset-1.nacos-cluster-statefulset-service.default.svc.cluster.local
nacos-cluster-statefulset-2.nacos-cluster-statefulset-service.default.svc.cluster.local
```


但仍是只有一个节点。

```
[root@nacos-cluster-statefulset-0 nacos]# more logs/naming-raft.log 
2022-07-29 14:58:25,593 INFO raft peers changed: [Member{ip='nacos-cluster-statefulset-0.nacos-cluster-statefulset-service.default.svc.cluster.local', port=8848, state=UP, extendInfo={
raftPort=7848, version=1.4.1}}]
```


```yml
apiVersion: v1
kind: Service
metadata:
  name: nacos-cluster-nodeport-service
spec:
  type: NodePort
  # nodePort 不能设置为 None
  #clusterIP: None
  ports:
    - port: 8848
      name: nacos-port
      targetPort: 8848
      nodePort: 30848
  selector:
    app: nacos-cluster


---

apiVersion: v1
kind: Service
metadata:
  name: nacos-cluster-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8848
      name: server
      targetPort: 8848
    - port: 9848
      name: client-rpc
      targetPort: 9848
    - port: 9849
      name: raft-rpc
      targetPort: 9849
    ## 兼容1.4.x版本的选举端口
    - port: 7848
      name: old-raft-rpc
      targetPort: 7848
  selector:
    app: nacos-cluster



---

apiVersion: v1
kind: ConfigMap
metadata:
  # 不能有大写字母
  name: nacos-cluster-configmap
data:
  # 这里是不用写 - 号的，他是个 map 。。。。。map 是这个意思吗。。。。
  JVM_XMS: 512M
  JVM_XMX: 512M
  JVM_XMN: 512M
  JVM_MMS: 512M



  MYSQL_SERVICE_DB_NAME: nacos
  MYSQL_SERVICE_USER: root
  MYSQL_SERVICE_PASSWORD: root
  MYSQL_SERVICE_HOST: mysql-nacos-connect-service # statefulSet 可以通过 serviceName 进行访问
  MYSQL_SERVICE_PORT: "3306"
  SPRING_DATASOURCE_PLATFORM: mysql

  # 纯数字需要双引号
  NACOS_APPLICATION_PORT: "8848"
  # `statefuleSet.metadata.name` + `-` + 从 0 开始的编号 + `.` + `service.metadata.name` +  `.default.svc.cluster.local` + `:` + 端口号
  # nacos-0.nacos-headless.default.svc.cluster.local:8848
  # 这种情况每次都是单一个节点，并不报错
  #NACOS_SERVERS: nacos-cluster-statefulset-0.nacos-cluster-service.default.svc.cluster.local:8848 nacos-cluster-statefulset-1.nacos-cluster-service.default.svc.cluster.local:8848 nacos-cluster-statefulset-2.nacos-cluster-service.default.svc.cluster.local:8848
  #  NACOS_SERVERS: nacos-cluster-statefulset-0:8848 nacos-cluster-statefulset-1:8848 nacos-cluster-statefulset-2:8848
  NACOS_SERVERS: nacos-cluster-statefulset-0.nacos-cluster-statefulset-service.default.svc.cluster.local:8848 nacos-cluster-statefulset-1.nacos-cluster-statefulset-service.default.svc.cluster.local:8848 nacos-cluster-statefulset-2.nacos-cluster-statefulset-service.default.svc.cluster.local:8848

  cluster.conf: |
    nacos.inetutils.prefer-hostname-over-ip=true
    nacos-cluster-statefulset-0.nacos-cluster-statefulset-service.default.svc.cluster.local
    nacos-cluster-statefulset-1.nacos-cluster-statefulset-service.default.svc.cluster.local
    nacos-cluster-statefulset-2.nacos-cluster-statefulset-service.default.svc.cluster.local

  PREFER_HOST_MODE: "hostname"
  serverList.sh: curl -X GET '127.0.0.1:8848/nacos/v1/ns/operator/servers'


---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  # 不能有大写字母
  name: nacos-cluster-statefulset
spec:
  selector:
    matchLabels:
      app: nacos-cluster
  replicas: 3
  # 不能有大写字母
  serviceName: nacos-cluster-statefulset-service
  template:
    metadata:
      labels:
        app: nacos-cluster
    spec:
      containers:
        - name: nacos
          image: nacos/nacos-server:1.4.1
          imagePullPolicy: IfNotPresent
          env:
            - name: JVM_XMS
              valueFrom:
                configMapKeyRef:
                  name: nacos-cluster-configmap
                  key: JVM_XMS
            - name: JVM_XMX
              valueFrom:
                configMapKeyRef:
                  name: nacos-cluster-configmap
                  key: JVM_XMX
            - name: JVM_XMN
              valueFrom:
                configMapKeyRef:
                  name: nacos-cluster-configmap
                  key: JVM_XMN
            - name: JVM_MMS
              valueFrom:
                configMapKeyRef:
                  name: nacos-cluster-configmap
                  key: JVM_MMS

            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cluster-configmap
                  key: MYSQL_SERVICE_DB_NAME
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cluster-configmap
                  key: MYSQL_SERVICE_USER
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cluster-configmap
                  key: MYSQL_SERVICE_PASSWORD
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-cluster-configmap
                  key: MYSQL_SERVICE_HOST
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cluster-configmap
                  key: MYSQL_SERVICE_PORT
            - name: SPRING_DATASOURCE_PLATFORM
              valueFrom:
                configMapKeyRef:
                  name: nacos-cluster-configmap
                  key: MYSQL_SERVICE_PORT



            
            - name: NACOS_APPLICATION_PORT
              valueFrom:
                configMapKeyRef:
                  key: NACOS_APPLICATION_PORT
                  name: nacos-cluster-configmap
#            - name: NACOS_SERVER_IP
#              valueFrom:
#                # 获取 pod 的 ip
#                fieldRef:
#                  fieldPath: status.podIP
            - name: PREFER_HOST_MODE
              valueFrom:
                configMapKeyRef:
                  key: PREFER_HOST_MODE
                  name: nacos-cluster-configmap
            - name: NACOS_SERVERS
              valueFrom:
                configMapKeyRef:
                  key: NACOS_SERVERS
                  name: nacos-cluster-configmap
          ports:
            - containerPort: 8848
              name: client
            - containerPort: 9848
              name: client-rpc
            - containerPort: 9849
              name: raft-rpc
            - containerPort: 7848
              name: old-raft-rpc

          volumeMounts:
            - mountPath: /home/nacos/logs
              name: nacos-logs
            - mountPath: /etc/timezone
              name: timezone
            - mountPath: /etc/localtime
              name: localtime
            - mountPath: /home/nacos/conf/cluster.conf
              subPath: cluster.conf
              name: cluster-conf
            - mountPath: /home/nacos/serverList.sh
              subPath: serverList.sh
              name: server-list
      
      volumes:
        - name: nacos-logs
          emptyDir: {}
        - name: timezone
          hostPath:
            path: /etc/timezone
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: cluster-conf
          configMap:
            name: nacos-cluster-configmap
            items:
              - key: cluster.conf
                # 是将键映射到的文件的相对路径。不能是绝对路径。不能包含路径元素 “..”。不能以字符串 “..” 开头。
                path: cluster.conf
        - name: server-list
          configMap:
            name: nacos-cluster-configmap
            items:
              - key: serverList.sh
                path: serverList.sh

```
