### ISSUE TITLE
Param 'serviceName' is illegal, serviceName is blank

### ISSUE THREAD

**Issue by LiJunYi2** [alibaba/nacos#8827]
## Issue Description

**An exception occurred while I was consolidating the spring-cloud-starter-gateway，But in the business module it is normal**

![image](https://user-images.githubusercontent.com/40384503/181669765-3bbb911e-87fa-4d6a-b0c8-4c00ff5aeeaa.png)

**The service module starts normally**
![image](https://user-images.githubusercontent.com/40384503/181669999-1eff4a4b-b151-4b98-843e-350011a3f3a0.png)

### Describe what you expected to happen
**Normally should start after the service list has gateway service**

### How to reproduce it (as minimally and precisely as possible)

1. 父pom

```xml
<spring-boot.version>2.7.2</spring-boot.version>
<spring-cloud.version>2021.0.3</spring-cloud.version>
<spring-cloud-alibaba.version>2021.0.1.0</spring-cloud-alibaba.version>
<alibaba.nacos.version>2.1.0</alibaba.nacos.version>
```

2.Gateway service - pom
```xml
        <!--gateway-->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>

        <!--nacos-->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <!-- bootstrap 启动器 -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
``` 
3.bootstrap.yml
```yaml
server:
  port: 9527
spring:
  application:
    name: security-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: ${spring.application.name}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: security-system
          uri: lb://security-system
          predicates:
            - Path=/sys/**
```
