### ISSUE TITLE
关于使用nacos配置中心，丢失部分配置问题

### ISSUE THREAD

**Issue by 790712946** [alibaba/nacos#8863]
![image](https://user-images.githubusercontent.com/18082424/182514348-6301d8d9-5d28-438a-afec-69629afea7a1.png)
上图是我的原始配置，可以看到最后以true结尾。
![image](https://user-images.githubusercontent.com/18082424/182514413-2d988ae7-a8df-4256-bdd7-19c4aeefce7b.png)
上图是发布对比图，可以看到true结尾丢失。发布后在应用服务拿到的值也是没有该配置的。

**Comment by chenhao26-nineteen** [comment]
> ![image](https://user-images.githubusercontent.com/18082424/182514348-6301d8d9-5d28-438a-afec-69629afea7a1.png) 上图是我的原始配置，可以看到最后以true结尾。 ![image](https://user-images.githubusercontent.com/18082424/182514413-2d988ae7-a8df-4256-bdd7-19c4aeefce7b.png) 上图是发布对比图，可以看到true结尾丢失。发布后在应用服务拿到的值也是没有该配置的。

Can you post the configured text format, and then please provide the versions of Nacos client and server.

**Comment by vergilyn** [comment]
`nacos: 2.1.0`，未发现丢失情况。
```YAML
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:23306/nacos_v210?characterEncoding=utf8&connectTimeout=1000&socketTimeout=300011111112222221111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111122222222222222222222222222222222222222222222222222222222222222222222222&autoReconnect=true 
```

内容比较那个页面，如果太长了，最后看的的显示确实少了一部分。
可以尝试 复制出来， 或者用键盘 → 看后面缺少的部分
