### ISSUE TITLE
How to mount a data volume when deploy in standalone mode inside docker

### ISSUE THREAD

**Issue by li-zheng-hao** [alibaba/nacos#8975]
i see offical demo is :
```yaml
nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone
    environment:
    - PREFER_HOST_MODE=hostname
    - MODE=standalone
    volumes:
    - ./standalone-logs/:/home/nacos/logs
    - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
    - "8848:8848"
    - "9848:9848"
 ```

it seems not mount data volume? when i remove this container, the data in configuration center  will lost?
