### ISSUE TITLE
InstanceId generator snowflake not work!

### ISSUE THREAD

**Issue by chenws1012** [alibaba/nacos#9001]
NACOS verson: 2.1.0
This is my config of spring cloud:
```yaml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR}:${NACOS_PORT:8848}
        namespace: ${NACOS_NAMESPACE}
        ip: ${PAAS_NAMESPACE}-ms-product
        metadata:
          preserved.instance.id.generator: snowflake
```

The Log output：
```json
{
  "name": "DEFAULT_GROUP@@ms-product",
  "clusters": "DEFAULT",
  "cacheMillis": 10000,
  "hosts": [
    {
      "instanceId": "test-ms-product#8080#DEFAULT#DEFAULT_GROUP@@ms-product",
      "ip": "test-ms-product",
      "port": 8080,
      "weight": 1,
      "healthy": true,
      "enabled": true,
      "ephemeral": true,
      "clusterName": "DEFAULT",
      "serviceName": "DEFAULT_GROUP@@ms-product",
      "metadata": {
        "preserved.register.source": "SPRING_CLOUD",
        "preserved.instance.id.generator": "snowflake"
      },
      "instanceIdGenerator": "snowflake",
      "instanceHeartBeatTimeOut": 15000,
      "ipDeleteTimeout": 30000,
      "instanceHeartBeatInterval": 5000
    }
  ],
  "lastRefTime": 1660881435685,
  "checksum": "",
  "allIPs": false,
  "reachProtectionThreshold": false,
  "valid": true
}
```
the "instanceIdGenerator" is  "snowflake", but "instanceId" is still "test-ms-product#8080#DEFAULT#DEFAULT_GROUP@@ms-product"
