### ISSUE TITLE
服务注册成功，但是服务列表报错：server is DOWNnow, detailed error message: Optional[Distro protocol is not initialized]

### ISSUE THREAD

**Issue by deephon** [alibaba/nacos#9116]
UI正常访问使用，没有问题，注册服务也没有问题，但就使用服务列表时，报错如题：server is DOWNnow, detailed error message: Optional[Distro protocol is not initialized]

基本配置条件：3台服务器集群，Nginx代理转发。
版本：v2.1.1
部署方式：Docker

Docker启动参数如下：
```bash
docker run -d --name hct-nacos --restart=always \
-p 8848:8848 -p 9848:9848 -p 9849:9849 \
-e TZ=Asiz/Shanghai \
-e NACOS_SERVERS="172.30.0.15:8848 172.30.0.11:8848 172.30.0.8:8848" \
-e MYSQL_SERVICE_HOST="172.30.0.10" \
-e MYSQL_SERVICE_DB_NAME="nacos" \
-e MYSQL_SERVICE_USER="nacos" \
-e MYSQL_SERVICE_PASSWORD="******" \
-e JVM_XMS="256M" \
--privileged=true \
nacos/nacos-server:v2.1.1
```

nginx有以下配置：
```nginx
http {
    ......
   upstream nacos_cluster {
        server 172.30.0.15:8848;
        server 172.30.0.11:8848;
        server 172.30.0.8:8848;
}

server {
    listen       7846;
    server_name  _;
        charset utf-8;
    location / {
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header   Host             $http_host;
        proxy_pass         http://nacos_cluster/;
    }
        #access_log  /data/nginx/logs/nacos.log;
        #error_log  /data/nginx/logs/nacos.log;
}
}
stream {
upstream lb-nacos-tcp {
        server 172.30.0.15:9848;
        server 172.30.0.11:9848;
        server 172.30.0.8:9848;
}
server {
        listen 8846;
        proxy_pass lb-nacos-tcp;
}
upstream lb-nacos-tcp2 {
        server 172.30.0.15:9849;
        server 172.30.0.11:9849;
        server 172.30.0.8:9849;
}
server {
        listen 8847;
        proxy_pass lb-nacos-tcp2;
}
}
```

服务使用config没有问题：
![image](https://user-images.githubusercontent.com/31088164/189069445-691127f7-28b9-4540-baa9-de2316e19803.png)

服务显示注册服务没有问题：
![image](https://user-images.githubusercontent.com/31088164/189069579-3179b844-086d-4ac0-8fd9-e2d15d1220b1.png)

服务的配置信息：
```yaml
spring:
  application:
    # 应用名称
    name: hct-gateway
  profiles:
    # 环境配置
    active: prod
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: nacos:7846
        namespace: hct-cloud
        group: DEFAULT_GROUP
      config:
        # 配置中心地址
        server-addr: nacos:7846
        namespace: hct-cloud
        group: DEFAULT_GROUP
        # 配置文件格式
        file-extension: yml
        # 共享配置
        shared-configs:
          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
```
