### ISSUE TITLE
配置文件加载规则

### ISSUE THREAD

**Issue by liruhui** [alibaba/nacos#9174]
# 1:问题描述
```properties
 加载配置时 指定prefix 获取不到配置信息
```
# 2: 问题重现
## 2.1: 第一步 nacos中添加配置
![QQ截图20220919123511](https://user-images.githubusercontent.com/24687986/190950865-0e739777-7415-40b3-8d96-0484d6877c44.jpg)
## 2.2: 第二步 客户端添加配置
```yaml
spring:
  cloud:
    nacos:
      config:
        namespace: 28e48cd3-732e-435b-8de5-b2a2155bb6e2
        group: DEFAULT_GROUP
        file-extension: yml 
        server-addr: localhost:8848
        prefix: aaa
  profiles:
    active: prod
```
# 3: 不理解的点
```properties
 指定了prefix , 也指定了profile 也指定了 file-extension    但启动报错 加载不到 为什么
```
