### ISSUE TITLE
nacos shuts down automatically.  nacos 自动关闭

### ISSUE THREAD

**Issue by ljz572000** [alibaba/nacos#9469]
**Describe the bug**

Using nacos as the config center, nacos shutsdown automatically after successful getting the configuration file.

使用nacos 作为配置中心，成功获取配置文件后，nacos 自动关闭

Spring Boot Version: v2.7.5

jdk: openjdk 11

nacos version: 2.1.1

       <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.12</version>
        </dependency>

log:

![image](https://user-images.githubusercontent.com/44089237/200562200-f12473ff-7b0c-4dd1-a7a7-cf20a4a6a272.png)

文件夹截图

![image](https://user-images.githubusercontent.com/44089237/200560154-7d8c45de-08ac-4e3a-9d76-b6c22349b9d8.png)

application.yml

```yaml
nacos:
  # Nacos 配置中心的配置项，对应 NacosConfigProperties 配置类
  config:
    server-addr: 127.0.0.1:8848?username=nacos&password=nacos # Nacos 服务器地址
    bootstrap:
#    这里，我们设置为 true，保证使用 @Value 和 @ConfigurationProperties 注解，可以读取到来自 Nacos 的配置项。
      enable: true # 是否开启 Nacos 配置预加载功能。默认为 false。
#    这里，我们设置为 true，保证 Spring Boot 应用的 Logger 能够使用来自 Nacos 的配置项。
      log-enable: true # 是否开启 Nacos 支持日志级别的加载时机。默认为 false。
    data-id: example # 使用的 Nacos 配置集的 dataId。
    type: YAML # 使用的 Nacos 配置集的配置格式。默认为 PROPERTIES。
    group: DEFAULT_GROUP # 使用的 Nacos 配置分组，默认为 DEFAULT_GROUP。
    namespace: # 使用的 Nacos 的命名空间，默认为 null。
```

Application,java

```java
@SpringBootApplication
// @NacosPropertySource(dataId = "example", type = ConfigType.YAML)
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Component
    public class OrderPropertiesCommandLineRunner implements CommandLineRunner {

        private final Logger logger = LoggerFactory.getLogger(getClass());

        @Autowired
        private OrderProperties orderProperties;

        @Override
        public void run(String... args) {
            logger.info("payTimeoutSeconds:" + orderProperties.getPayTimeoutSeconds());
            logger.info("createFrequencySeconds:" + orderProperties.getCreateFrequencySeconds());
        }

    }

    @Component
    public class ValueCommandLineRunner implements CommandLineRunner {

        private final Logger logger = LoggerFactory.getLogger(getClass());

        //        @NacosValue(value = "${order.pay-timeout-seconds}")
        @Value(value = "${order.pay-timeout-seconds}")
        private Integer payTimeoutSeconds;

        //        @NacosValue(value = "${order.create-frequency-seconds}")
        @Value(value = "${order.create-frequency-seconds}")
        private Integer createFrequencySeconds;

        @Override
        public void run(String... args) {
            logger.info("payTimeoutSeconds:" + payTimeoutSeconds);
            logger.info("createFrequencySeconds:" + createFrequencySeconds);
        }
    }

}

```

OrderProperties.java

```java

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

@Component
//@NacosConfigurationProperties(prefix = "order", dataId = "${nacos.config.data-id}", type = ConfigType.YAML)
@ConfigurationProperties(prefix = "order")
public class OrderProperties {

    /**
     * 订单支付超时时长，单位：秒。
     */
    private Integer payTimeoutSeconds;

    /**
     * 订单创建频率，单位：秒
     */
    private Integer createFrequencySeconds;

//    /**
//     * 配置描述
//     */
//    private String desc;

    public Integer getPayTimeoutSeconds() {
        return payTimeoutSeconds;
    }

    public OrderProperties setPayTimeoutSeconds(Integer payTimeoutSeconds) {
        this.payTimeoutSeconds = payTimeoutSeconds;
        return this;
    }

    public Integer getCreateFrequencySeconds() {
        return createFrequencySeconds;
    }

    public OrderProperties setCreateFrequencySeconds(Integer createFrequencySeconds) {
        this.createFrequencySeconds = createFrequencySeconds;
        return this;
    }

//    public String getDesc() {
//        return desc;
//    }
//
//    public OrderProperties setDesc(String desc) {
//        this.desc = desc;
//        return this;
//    }

}

```

nacos 配置文件截图

![image](https://user-images.githubusercontent.com/44089237/200559720-a010bf2c-e723-43cc-b2d6-97a6b3b6a3b5.png)
