### ISSUE TITLE
是否支持使用application-dev.yml中指定nacos config

### ISSUE THREAD

**Issue by zhonghuafy** [alibaba/nacos#9522]
在bootstrap.properties中指定spring.profiles.active=dev，然后在bootstrap-dev.properties中指定dev环境的nacos config信息，可以正常加载nacos的配置。
但是不想使用bootstrap.properties和bootstrap-dev.properties文件，希望能在application.yml中指定spring.profiles.active=dev，将dev环境的nacos config信息放在application-dev.yml中。
但是似乎没有加载到nacos的配置。是我哪里配置的有问题还是nacos不支持？
奇怪的sentinel却支持这种配置方式。在sentinel中能成功读取到nacos中配的限流信息。

以下是我的application-dev.yml配置：
```    
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: DEFAULT_GROUP
        namespace: c2897240-442e-4e0e-be5a-eef34d65341d
      config:
        import-check:
          enabled: false
        server-addr: localhost:8848
        file-extension: yml
        group: DEFAULT_GROUP
        namespace: c2897240-442e-4e0e-be5a-eef34d65341d
        username: nacos
        password: nacos
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      eager: true
      datasource:
        flow:
          nacos:
            server-addr: localhost:8848
            data-id: ${spring.application.name}-flow-rules
            group-id: DEFAULT_GROUP
            namespace: c2897240-442e-4e0e-be5a-eef34d65341d
            data-type: json
            rule-type: flow
            username: nacos
            password: nacos
```
