### ISSUE TITLE
docker-stack部署如何区分实例

### ISSUE THREAD

**Issue by liruhui** [alibaba/nacos#9778]
# 场景说明
```properties 
 在docker-swarm集群环境下 部署微服务  每个服务都部署多个实例 服务之间使用openFeign远程调用
```
# 问题演示
## 1.1.  项目启动注册到nacos 
```properties
   注册到nacos中的时候  nacos中能够展示集群信息，但是展示的是docker容器的内部ip(如下图)   导致openFeign访问失败
```
![{ZI$}_@K(TPS2$US7PKNRWJ](https://user-images.githubusercontent.com/24687986/210160048-d48bd5ab-bb3f-44a2-9371-5027389d4256.png)

## 1.2. 修改项目指定ip 
```yml
spring: 
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.191.148:8848
        ip: 192.168.191.148
```
## 1.3. 重新打包重新运行
```properties
  此时因为在配置文件中指定了ip   运行多个实例时  在nacos中只展示一个实例（如下图）
```
![3{J92@DZ)}ZSMPEJ 8$QYPL](https://user-images.githubusercontent.com/24687986/210159727-e9f095b7-0e53-4713-984a-a61de4e5c18b.png)

# 问题总结
```
 docker stack 部署多个副本时 不手动指定ip nacos注册中心会展示多个实例，但是ip是docker容器内部ip openFeign调用失败
如果手动指定ip  虽然说启动了多个副本 但是nacos中只有1个实例 展示的实例数量不对
```
#  问题提问
```
能不能做到 nacos展示多个实例  nacos能够区分多个实例 并且openFeign也能调用成功呢
```
