### ISSUE TITLE
macOS配置了server-addr，启动还是找loclahost

### ISSUE THREAD

**Issue by aomsir** [alibaba/nacos#9793]
```yaml
spring:
  profiles:
    #引用application-common.yml文件
    include: common
  application:
    name: bff-driver
  redis:
    database: 3
    host: 192.168.212.144
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  cloud:
    inetutils:
      #子系统注册到Nacos上的IP地址
      preferred-networks: 192.168.212.144
    nacos:
      #配置子系统在Web管理页面上的注册信息
      config:
        group: DEFAULT_GROUP
        file-extension: yaml
        server-addr: 192.168.212.144:8848
        prefix: ${spring.application.name}
        namespace: hxds
      #配置子系统在Nacos上的注册信息
      discovery:
        namespace: hxds
        username: nacos
        password: nacos
        server-addr: 192.168.212.144:8848
        heart-beat-interval: 1000
        heart-beat-timeout: 1000
        group: DEFAULT_GROUP
```
如上配置，启动老师报错，如下
<img width="1647" alt="image" src="https://user-images.githubusercontent.com/60360782/210355941-a1785025-9ecb-4cea-a37a-05248117bcfd.png">
