### ISSUE TITLE
gRPC 反向代理 和 Auth 问题

### ISSUE THREAD

**Issue by wenerme** [alibaba/nacos#9999]
gRPC 有用到 auth 么？

想要把 grpc 反向代理出去到相同域名上需要知道用到的 grpc 服务

```yaml
spec:
  rules:
  - host: nacos.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nacos-headless
            port:
              name: server
      - path: /用到了哪些服务呢？
        pathType: Prefix
        backend:
          service:
            name: nacos-headless
            port:
              name: client-rpc
```

**Comment by YunWZ** [comment]
1. 只要开启鉴权功能，http和grpc请求都需要鉴权--客户端均需要携带鉴权信息；
2. grpc端口默认为base_port+1000, base_port默认是8080， 因此nacos-server默认的grpc监听端口为9080. 

因此你可以试一下给予端口路由，而不是基于请求路径。
如果你的nacos服务端需要兼容1.x的客户端，则需要配置请求路径。

**Comment by wenerme** [comment]
grpc 本质也是 http，可以一起暴露，只是需要知道服务名字，在这个仓库里没找到 grpc 的 proto

**Comment by YunWZ** [comment]
> grpc 本质也是 http，可以一起暴露，只是需要知道服务名字，在这个仓库里没找到 grpc 的 proto

```protobuf
service Request {
  // Sends a commonRequest
  rpc request (Payload) returns (Payload) {
  }
}

service BiRequestStream {
  // Sends a biStreamRequest
  rpc requestBiStream (stream Payload) returns (stream Payload) {
  }
}
```

**Comment by wenerme** [comment]
好吧，只是作为 transport，我还以为不是这个，我试试

**Comment by wenerme** [comment]
没问题

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nacos-grpc
  labels:
    app: nacos
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    haproxy.org/server-proto: h2
spec:
  rules:
  - host: nacos.wener.me
    http:
      paths:
      - path: /Request
        pathType: Prefix
        backend:
          service:
            name: nacos-headless
            port:
              name: client-rpc
      - path: /BiRequestStream
        pathType: Prefix
        backend:
          service:
            name: nacos-headless
            port:
              name: client-rpc
  tls:
  - hosts:
    - nacos.wener.me
```
